# 1. IMPORTACIÓN DE DATOS

In [1]:
# Parámetros a definir

    # lesk: True/False
        # True --> Synset se elige utilizando el desambiguador de Lesk
        # False --> Synset es el más común 
    # tipo_bow: --> Categorías de synsets que cogeremos para hacer los cálculos
        # todos (1) --> Todos los synsets
        # nv (2) --> Solo nombres y adjetivos
    # metodo_frase: lw / Ariadna / Agirre
    # partición: numero entero
        # fragmento del corpus que se procesa.
        

desambiguar = True

expandir_contracciones = False

tipo_bow = 'nv'

metodo_frase = 'lw'

particion = 1

print_info = False

importar_librerias = True

importar_datos = True

criterios = 'Lesk-' + str(desambiguar) + ', tipo_bow-' + str(tipo_bow) + ', metodo-' + str(metodo_frase) + ', particion-' + str(particion)

print()
print('Desambiguación desambiguar:', desambiguar)
print('Tipo de BoW:', tipo_bow)
print('Método de comparación a nivel de frase:', metodo_frase)
print('Particion de filas a importar:', particion)
print('Importar librerías:', importar_librerias)
print('Importar datos:', importar_datos)

print(criterios)

Desambiguación desambiguar: True
Tipo de BoW: nv
Método de comparación a nivel de frase: lw
Particion de filas a importar: 1
Importar librerías: True
Importar datos: True
Lesk-True, tipo_bow-nv, metodo-lw, particion-1

In [2]:
# Importación de librerías

if importar_librerias:
    
    import time
    import datetime

    import csv

    import pandas as pd
    pd.options.display.max_rows  # Para mostrar todas las columnas
    pd.set_option('display.max_colwidth', -1)  # Para incluir todo el contenido de una celda, sin truncar contenido.
    pd.set_option('display.max_columns', 500)  # Para incluir todas las columnas (no serán más de 500)
    pd.set_option('display.max_rows', 6000)  # Para incluir todas las columnas (no serán más de 6000)

    import numpy as np

    from nltk.corpus import wordnet as wn

    from nltk.corpus import wordnet_ic
    ic_brown = wordnet_ic.ic('ic-brown.dat')
    ic_semcor = wordnet_ic.ic('ic-semcor.dat')

    from nltk.corpus import genesis
    ic_genesis = wn.ic(genesis, False, 0.0)
    
    if desambiguar == True:
        from nltk.wsd import lesk

In [3]:
# Funciones generales

# función coseno
    # Entrada: dos vectores
    # Salida: Un número real entre [0,1] (coseno entre los dos vectores)

def coseno(v1, v2):
    
    coseno = v1.dot(v2) / np.sqrt(v1.dot(v1) * v2.dot(v2))
    
    return(coseno)

# Ejemplo para comprobar funcionamiento coseno()

print('****** EJEMPLO coseno() ********')   
v1 = np.array([1,2,3])
v2 = np.array([1,0,1])
print('Coseno:', coseno(v1,v1))
print('Coseno:', coseno(v1,v2))
print('****')

****** EJEMPLO coseno() ********
Coseno: 1.0
Coseno: 0.7559289460184544
****

In [4]:
# Importación de los datos del fichero sts-train.csv a un dataframe

start_total = time.time()

if importar_datos:

    file = 'stsbenchmark\sts-train.csv'
    corpus = pd.read_csv(file, sep='\t', error_bad_lines=False, quoting=csv.QUOTE_NONE, usecols=range(7), header=-1)
    corpus.head()
    corpus.columns = ['genre', 'file', 'year', 'id', 'gold_score', 'sent1', 'sent2']


end_total = time.time()

print('TIEMPO TRANSCURRIDO:', end_total-start_total)

corpus.sample(5)

TIEMPO TRANSCURRIDO: 0.037199974060058594

,genre,file,year,id,gold_score,sent1,sent2
1309,main-captions,images,2014,450,3.8,Black and white cow standing in grassy field.,A black and white horned cow standing in a field.
3710,main-news,deft-news,2014,260,2.0,north korean officials are suspected of building nuclear weapons.,north korea is currently in the process of dismantling its nuclear weapons program.
5206,main-news,headlines,2015,638,0.4,More rain hampers Indian flood rescue,US tourist gang-raped in northern India: Police
569,main-captions,MSRvid,2012train,110,2.0,A person is slicing a scallop.,A person is slicing octopus.
1002,main-captions,images,2014,3,3.2,A large boat in the water at the marina.,A large boat on the sea.

# 2. ANÁLISIS 1: REVISIÓN DE LOS DATOS BRUTOS (...)

In [5]:
# Eliminación de duplicados

if importar_datos:

    corpus.drop_duplicates(['sent1', 'sent2'], keep='first', inplace=True)

end_total = time.time()
print('TIEMPO TRANSCURRIDO:', end_total-start_total)

TIEMPO TRANSCURRIDO: 0.0793619155883789

In [6]:
# Creación de un corpus c reducido con filas representativas del corpus original

    # Para realizar pre-procesamientos que nos permitan verificar la adecuación de los algoritmos
    # en un tiempo reducido.

particion = particion

c = corpus.iloc[::particion, :].copy()
num_filas = 'Número de filas incluídas en el dataframe: ' + str(c.shape[0])

print(num_filas)

end_total = time.time()
print('TIEMPO TRANSCURRIDO:', end_total-start_total)

c.head(12)

Número de filas incluídas en el dataframe: 5706
TIEMPO TRANSCURRIDO: 0.08878397941589355

,genre,file,year,id,gold_score,sent1,sent2
0,main-captions,MSRvid,2012test,1,5.00,A plane is taking off.,An air plane is taking off.
1,main-captions,MSRvid,2012test,4,3.80,A man is playing a large flute.,A man is playing a flute.
2,main-captions,MSRvid,2012test,5,3.80,A man is spreading shreded cheese on a pizza.,A man is spreading shredded cheese on an uncooked pizza.
3,main-captions,MSRvid,2012test,6,2.60,Three men are playing chess.,Two men are playing chess.
4,main-captions,MSRvid,2012test,9,4.25,A man is playing the cello.,A man seated is playing the cello.
5,main-captions,MSRvid,2012test,11,4.25,Some men are fighting.,Two men are fighting.
6,main-captions,MSRvid,2012test,12,0.50,A man is smoking.,A man is skating.
7,main-captions,MSRvid,2012test,13,1.60,The man is playing the piano.,The man is playing the guitar.
8,main-captions,MSRvid,2012test,14,2.20,A man is playing on a guitar and singing.,A woman is playing an acoustic guitar and singing.
9,main-captions,MSRvid,2012test,16,5.00,A person is throwing a cat on to the ceiling.,A person throws a cat on the ceiling.
10,main-captions,MSRvid,2012test,17,4.20,The man hit the other man with a stick.,The man spanked the other man with a stick.
11,main-captions,MSRvid,2012test,18,4.60,A woman picks up and holds a baby kangaroo.,A woman picks up and holds a baby kangaroo in her arms.

# 3. TOKENIZACION, LIMPIEZA Y ANOTACIÓN

In [7]:
# Pre procesamiento
# https://www.linkedin.com/pulse/processing-normalizing-text-data-saurav-ghosh/
# http://xperimentallearning.blogspot.com/2018/05/nlppython.html

# ========================================
# 3. TOKENIZACION, LIMPIEZA Y ANOTACIÓN
# ========================================

import nltk

def expandir_contracciones(texto):
    # specific
    texto = re.sub(r"won\'t", "will not", texto)
    texto = re.sub(r"can\'t", "can not", texto)

    # general
    texto = re.sub(r"n\'t", " not", texto)
    texto = re.sub(r"\'re", " are", texto)
    texto = re.sub(r"\'s", " is", texto)
    texto = re.sub(r"\'d", " would", texto)
    texto = re.sub(r"\'ll", " will", texto)
    texto = re.sub(r"\'t", " not", texto)
    texto = re.sub(r"\'ve", " have", texto)
    texto = re.sub(r"\'m", " am", texto)
    return texto

def tokenizar(sent, print_tokenizar =False):
    
    # tokens que aceptaremos (de nltk.org/book/ch03). Output: cadena de palabras.
   
    if print_tokenizar == True: print('Frase a tokenizar:', sent)
        
    pattern = r'''(?x)       # set flag to allow verbose regexps
        (?:[A-Z]\.)+         # abbreviations, e.g. U.S.A. ?: needs to be added to specify that the parenthesis specify the scope of the disjunction, not the selection o strings to be extracted
       | \w+(?:-\w+)*        # words with optional internal hyphens
       | [\$,\€]?\d+(?:\.\d+)?%?  # currency and percentages, e.g. $12.40, 82%
    '''
    if print_tokenizar == True: print('pattern:', pattern)
    '''
    AMPLIAR.
    - Analizar errores
    - Alguna solución para detectar phrasal verbs?
    '''

    # tokenización. Output: lista
   
    tokens = nltk.regexp_tokenize(sent, pattern, gaps=False)
    
    # limpieza 1: mayúsculas
    
    tokens = [token.lower() for token in tokens]   
    if print_tokenizar == True: print('Tokens:', tokens)
 
    # anotación POS. Output: lista de tuplas
    
    tagged_tokens = nltk.pos_tag(tokens, tagset='universal')
    
    # Convertimos las etiquetas gramaticales en notación Lesk;
        
    for i, tagged_token in enumerate(tagged_tokens):
        if tagged_tokens[i][1] == 'NOUN': tagged_tokens[i] = (tagged_tokens[i][0], 'n')
        if tagged_tokens[i][1] == 'VERB': tagged_tokens[i] = (tagged_tokens[i][0], 'v')
        if tagged_tokens[i][1] == 'ADJ': tagged_tokens[i] = (tagged_tokens[i][0], 'a')
        if tagged_tokens[i][1] == 'ADV': tagged_tokens[i] = (tagged_tokens[i][0], 'r')
    if print_tokenizar == True: print('Tagged_tokens:', tagged_tokens)
    
    # limipieza 2: stopwords - REVISAR si queremos/podemos incluir phrasal verbs, determinantes, pronombres...
            
                # Wordnet no incluye determinantes o preposiciones, de forma que "a" es asociado por Lesk 
                # al Synset('deoxyadenosine_monophosphate.n.01'), lo cual no nos conviene.
                # Por otro lado, Lesk utiliza para desambiguar solo las palabras que aparecen en Wordnet,
                # de modo que limpiar antes o después de Lesk las stopwords no debería afectar al resultado.
   
    if print_tokenizar == True: print('Limpieza de stopwords')
    stopwords = nltk.corpus.stopwords.words('english')
    tagged_stops = [tagged_stop for tagged_stop in tagged_tokens if tagged_stop[0] in stopwords]
    if print_tokenizar == True: print('Stopwords eliminadas:', tagged_stops)
    tokens = [token for token in tokens if token not in stopwords]
    tagged_tokens = [tagged_token for tagged_token in tagged_tokens if tagged_token[0] not in stopwords]
    if print_tokenizar == True: print('Tagged tokens sin stopwords:', tagged_tokens)

    return(tokens, tagged_tokens, tagged_stops)

# Ejemplo para comprobar funcionamiento tokenizar()
   
sent = "I'll always love my sweet baby"

print('****** EJEMPLO tokenizar() ********')
tokens = tokenizar(sent, print_tokenizar=True)
print('****')

end_total = time.time()
print('TIEMPO TRANSCURRIDO:', end_total-start_total)

****** EJEMPLO tokenizar() ********
Frase a tokenizar: I'll always love my sweet baby
pattern: (?x)       # set flag to allow verbose regexps
        (?:[A-Z]\.)+         # abbreviations, e.g. U.S.A. ?: needs to be added to specify that the parenthesis specify the scope of the disjunction, not the selection o strings to be extracted
       | \w+(?:-\w+)*        # words with optional internal hyphens
       | [\$,\€]?\d+(?:\.\d+)?%?  # currency and percentages, e.g. $12.40, 82%

Tokens: ['i', 'll', 'always', 'love', 'my', 'sweet', 'baby']
Tagged_tokens: [('i', 'n'), ('ll', 'v'), ('always', 'r'), ('love', 'v'), ('my', 'PRON'), ('sweet', 'a'), ('baby', 'n')]
Limpieza de stopwords
Stopwords eliminadas: [('i', 'n'), ('ll', 'v'), ('my', 'PRON')]
Tagged tokens sin stopwords: [('always', 'r'), ('love', 'v'), ('sweet', 'a'), ('baby', 'n')]
****
TIEMPO TRANSCURRIDO: 0.2549440860748291

In [8]:
c.head()

,genre,file,year,id,gold_score,sent1,sent2
0,main-captions,MSRvid,2012test,1,5.00,A plane is taking off.,An air plane is taking off.
1,main-captions,MSRvid,2012test,4,3.80,A man is playing a large flute.,A man is playing a flute.
2,main-captions,MSRvid,2012test,5,3.80,A man is spreading shreded cheese on a pizza.,A man is spreading shredded cheese on an uncooked pizza.
3,main-captions,MSRvid,2012test,6,2.60,Three men are playing chess.,Two men are playing chess.
4,main-captions,MSRvid,2012test,9,4.25,A man is playing the cello.,A man seated is playing the cello.

In [9]:
# Tokenización de c

c['tokens1'], c['tokens2'] = '', ''
c['tagged_tokens1'], c['tagged_tokens2'] = '', ''
c['stops1'], c['stops2'] = '', ''

print_tokenizar = False

for i in c.index:
    c.at[i, 'tokens1'] = tokenizar(c.at[i, 'sent1'], print_tokenizar)[0]
    c.at[i, 'tokens2'] = tokenizar(c.at[i, 'sent2'], print_tokenizar)[0]
    c.at[i, 'tagged_tokens1'] = tokenizar(c.at[i, 'sent1'], print_tokenizar)[1]
    c.at[i, 'tagged_tokens2'] = tokenizar(c.at[i, 'sent2'], print_tokenizar)[1]
    c.at[i, 'stops1'] = tokenizar(c.at[i, 'sent1'], print_tokenizar)[2]
    c.at[i, 'stops2'] = tokenizar(c.at[i, 'sent2'], print_tokenizar)[2]

end_total = time.time()
print('TIEMPO TRANSCURRIDO:', end_total-start_total)

c.head()

TIEMPO TRANSCURRIDO: 49.33565402030945

,genre,file,year,id,gold_score,sent1,sent2,tokens1,tokens2,tagged_tokens1,tagged_tokens2,stops1,stops2
0,main-captions,MSRvid,2012test,1,5.00,A plane is taking off.,An air plane is taking off.,"[plane, taking]","[air, plane, taking]","[(plane, n), (taking, v)]","[(air, n), (plane, n), (taking, v)]","[(a, DET), (is, v), (off, PRT)]","[(an, DET), (is, v), (off, PRT)]"
1,main-captions,MSRvid,2012test,4,3.80,A man is playing a large flute.,A man is playing a flute.,"[man, playing, large, flute]","[man, playing, flute]","[(man, n), (playing, v), (large, a), (flute, n)]","[(man, n), (playing, v), (flute, n)]","[(a, DET), (is, v), (a, DET)]","[(a, DET), (is, v), (a, DET)]"
2,main-captions,MSRvid,2012test,5,3.80,A man is spreading shreded cheese on a pizza.,A man is spreading shredded cheese on an uncooked pizza.,"[man, spreading, shreded, cheese, pizza]","[man, spreading, shredded, cheese, uncooked, pizza]","[(man, n), (spreading, v), (shreded, v), (cheese, n), (pizza, n)]","[(man, n), (spreading, v), (shredded, v), (cheese, n), (uncooked, a), (pizza, n)]","[(a, DET), (is, v), (on, ADP), (a, DET)]","[(a, DET), (is, v), (on, ADP), (an, DET)]"
3,main-captions,MSRvid,2012test,6,2.60,Three men are playing chess.,Two men are playing chess.,"[three, men, playing, chess]","[two, men, playing, chess]","[(three, NUM), (men, n), (playing, v), (chess, n)]","[(two, NUM), (men, n), (playing, v), (chess, n)]","[(are, v)]","[(are, v)]"
4,main-captions,MSRvid,2012test,9,4.25,A man is playing the cello.,A man seated is playing the cello.,"[man, playing, cello]","[man, seated, playing, cello]","[(man, n), (playing, v), (cello, n)]","[(man, n), (seated, v), (playing, v), (cello, n)]","[(a, DET), (is, v), (the, DET)]","[(a, DET), (is, v), (the, DET)]"

In [10]:
# ========================================
# 4. ASIGNACIÓN DE SYNSETS DE WORDNET
# ========================================

# Asignación de synsets 
    # Entrada: lista de tuplas con tokens y sus correspondientes etiquetas gramaticales
    # Argumentos: 
         # lesk: Opción de aplicar el algoritmo de Lesk  [Lesk 1986] de la librería wsd para desambiguar
                # Opción por defecto: n (no) --> Se asignará el primer synset del grupo de synsets (el más común)
                # Opción: s (sí) --> Asignar el synset determinado por Lesk
                
def syns(tagged_tokens, desambiguar=desambiguar):
    from nltk.wsd import lesk
    for i in c.index:
        syns = list()
        errors = list()
        if desambiguar == True:
            for j in tagged_tokens:
                if lesk([token for token, tag in tagged_tokens], j[0], j[1]) is not None:
                    syns.append(lesk([token for token, tag in tagged_tokens], j[0], j[1]))
                else:
                    errors.append(j)
        else: 
            for j in tagged_tokens:
                try: syns.append(wn.synsets(j[0],j[1])[0])
                except: errors.append(j)
        return(syns, errors)
    
# Ejemplo para comprobar funcionamiento syns()

desambiguar = True

print('Desambiguación Lesk:', desambiguar)

tagged_tokens = c['tagged_tokens1'][151]
syns1 = syns(tagged_tokens, desambiguar)

end_total = time.time()
print('TIEMPO TRANSCURRIDO:', end_total-start_total)

print('****** EJEMPLO syns() ********')   
print('tagged_tokens:', tagged_tokens)
print('syns(tagged_tokens):', syns1[0])
print('syns(tagged_tokens) - Errors:', syns1[1])
print('****')

desambiguar = False

print('Desambiguación Lesk:', desambiguar)

tagged_tokens = c['tagged_tokens1'][151]
syns1 = syns(tagged_tokens, desambiguar)

end_total = time.time()
print('TIEMPO TRANSCURRIDO:', end_total-start_total)

print('****** EJEMPLO syns() ********')   
print('tagged_tokens:', tagged_tokens)
print('syns(tagged_tokens):', syns1[0])
print('syns(tagged_tokens) - Errors:', syns1[1])
print('****')

Desambiguación Lesk: True
TIEMPO TRANSCURRIDO: 49.38971710205078
****** EJEMPLO syns() ********
tagged_tokens: [('man', 'n'), ('cutting', 'v'), ('fish', 'a')]
syns(tagged_tokens): [Synset('world.n.08'), Synset('cut.v.24')]
syns(tagged_tokens) - Errors: [('fish', 'a')]
****
Desambiguación Lesk: False
TIEMPO TRANSCURRIDO: 49.39117670059204
****** EJEMPLO syns() ********
tagged_tokens: [('man', 'n'), ('cutting', 'v'), ('fish', 'a')]
syns(tagged_tokens): [Synset('man.n.01'), Synset('cut.v.01')]
syns(tagged_tokens) - Errors: [('fish', 'a')]
****

In [11]:
# Asignacion de synsets a los tokens de c

desambiguar = desambiguar
print('Desambiguación Lesk:', desambiguar)
tipo_bow = tipo_bow
print('Tipo_bow:', tipo_bow)

c['syns1'] = ''
c['syns2'] = ''
c['errors1'] = ''
c['errors2'] = ''
c['syns1_nv'] = ''
c['syns2_nv'] = ''
c['syns1_resto'] = ''
c['syns2_resto'] = ''

for i in c.index:
    c.at[i,'syns1'] = syns(c.at[i, 'tagged_tokens1'])[0]
    c.at[i,'syns2'] = syns(c.at[i, 'tagged_tokens2'])[0]
    c.at[i,'errors1'] = syns(c.at[i, 'tagged_tokens1'])[1]
    c.at[i,'errors2'] = syns(c.at[i, 'tagged_tokens2'])[1]
    
    if tipo_bow == 'nv':
        c.at[i,'syns1_nv'] = [syn for syn in c.at[i,'syns1'] if syn.pos() in ['n', 'v']]
        c.at[i,'syns2_nv'] = [syn for syn in c.at[i,'syns2'] if syn.pos() in ['n', 'v']]
        c.at[i,'syns1_resto'] = [syn for syn in c.at[i,'syns1'] if syn.pos() not in ['n', 'v']]
        c.at[i,'syns2_resto'] = [syn for syn in c.at[i,'syns2'] if syn.pos() not in ['n', 'v']]


end_total = time.time()
print('TIEMPO TRANSCURRIDO:', end_total-start_total)

c.sample(5)

Desambiguación Lesk: False
Tipo_bow: nv
TIEMPO TRANSCURRIDO: 65.75818014144897

,genre,file,year,id,gold_score,sent1,sent2,tokens1,tokens2,tagged_tokens1,tagged_tokens2,stops1,stops2,syns1,syns2,errors1,errors2,syns1_nv,syns2_nv,syns1_resto,syns2_resto
1264,main-captions,images,2014,387,2.2,Red double decker bus taking on passengers.,A red double decker bus driving down a street.,"[red, double, decker, bus, taking, passengers]","[red, double, decker, bus, driving, street]","[(red, a), (double, a), (decker, n), (bus, n), (taking, v), (passengers, n)]","[(red, a), (double, a), (decker, n), (bus, n), (driving, v), (street, n)]","[(on, ADP)]","[(a, DET), (down, PRT), (a, DET)]","[Synset('double.a.04'), Synset('dekker.n.01'), Synset('busbar.n.01'), Synset('remove.v.01'), Synset('passenger.n.01')]","[Synset('double.a.04'), Synset('dekker.n.01'), Synset('busbar.n.01'), Synset('drive.v.03'), Synset('street.n.05')]","[(red, a)]","[(red, a)]","[Synset('dekker.n.01'), Synset('busbar.n.01'), Synset('remove.v.01'), Synset('passenger.n.01')]","[Synset('dekker.n.01'), Synset('busbar.n.01'), Synset('drive.v.03'), Synset('street.n.05')]",[Synset('double.a.04')],[Synset('double.a.04')]
1093,main-captions,images,2014,130,3.8,Two cats sitting together on the sofa looking out the window.,Two cats are looking at a window.,"[two, cats, sitting, together, sofa, looking, window]","[two, cats, looking, window]","[(two, NUM), (cats, n), (sitting, v), (together, r), (sofa, n), (looking, v), (window, n)]","[(two, NUM), (cats, n), (looking, v), (window, n)]","[(on, ADP), (the, DET), (out, PRT), (the, DET)]","[(are, v), (at, ADP), (a, DET)]","[Synset('caterpillar.n.02'), Synset('sit_down.v.01'), Synset('together.r.05'), Synset('sofa.n.01'), Synset('search.v.02'), Synset('windowpane.n.01')]","[Synset('caterpillar.n.02'), Synset('search.v.02'), Synset('windowpane.n.01')]","[(two, NUM)]","[(two, NUM)]","[Synset('caterpillar.n.02'), Synset('sit_down.v.01'), Synset('sofa.n.01'), Synset('search.v.02'), Synset('windowpane.n.01')]","[Synset('caterpillar.n.02'), Synset('search.v.02'), Synset('windowpane.n.01')]",[Synset('together.r.05')],[]
4559,main-news,headlines,2014,264,2.6,George Zimmerman found not guilty of Trayvon Martin murder,Protests and appeals for calm after Zimmerman acquitted of Trayvon Martin murder,"[george, zimmerman, found, guilty, trayvon, martin, murder]","[protests, appeals, calm, zimmerman, acquitted, trayvon, martin, murder]","[(george, n), (zimmerman, n), (found, v), (guilty, a), (trayvon, n), (martin, n), (murder, n)]","[(protests, n), (appeals, n), (calm, n), (zimmerman, n), (acquitted, v), (trayvon, n), (martin, n), (murder, n)]","[(not, r), (of, ADP)]","[(and, CONJ), (for, ADP), (after, ADP), (of, ADP)]","[Synset('george.n.07'), Synset('establish.v.08'), Synset('guilty.a.01'), Synset('martin.n.05'), Synset('murder.n.01')]","[Synset('protest.n.03'), Synset('solicitation.n.02'), Synset('composure.n.01'), Synset('behave.v.02'), Synset('martin.n.05'), Synset('murder.n.01')]","[(zimmerman, n), (trayvon, n)]","[(zimmerman, n), (trayvon, n)]","[Synset('george.n.07'), Synset('establish.v.08'), Synset('martin.n.05'), Synset('murder.n.01')]","[Synset('protest.n.03'), Synset('solicitation.n.02'), Synset('composure.n.01'), Synset('behave.v.02'), Synset('martin.n.05'), Synset('murder.n.01')]",[Synset('guilty.a.01')],[]
429,main-captions,MSRvid,2012test,642,2.8,The woman is pencilling on eye shadow.,The girl is using an eye pencil on her eyelid.,"[woman, pencilling, eye, shadow]","[girl, using, eye, pencil, eyelid]","[(woman, n), (pencilling, v), (eye, n), (shadow, n)]","[(girl, n), (using, v), (eye, n), (pencil, n), (eyelid, n)]","[(the, DET), (is, v), (on, ADP)]","[(the, DET), (is, v), (an, DET), (on, ADP), (her, PRON)]","[Synset('womanhood.n.02'), Synset('pencil.v.01'), Synset('eye.n.05'), Synset('trace.n.02')]","[Synset('girlfriend.n.02'), Synset('use.v.04'), Synset('eye.n.05'), Synset('pencil.n.04'), Synset('eyelid.n.01')]",[],[],"[Synset('womanhood.n.02'), Synset('pencil.v.01'), Synset('eye.n.05'), Synset('trace.n.02')]","[Synset('girlfriend.n.02'), Synset('use.v.04'), Synset('eye.n.05'), Synset('pencil.n.04'), Synset('eyelid.n.01')]",[],[]
1384,main-captions,images,2014,568,2.6,Two brown horses standing in a green meadow.,A brown horse stands in tall grass.,"[two, brown, horses, standing, green, meadow]","[brown, horse, stands, tall, grass]","[(two, NUM), (brown, a), (horses, n), (standing, v), (green, a), (meadow, n)]","[(brown, a), (horse, n), (stands, n), (tall, a), (grass, n)]","[(in, ADP), (a, DET)]","[(a, DET), (in, ADP)]","[Synset('knight.n.02'), Synset('stand.v.12'), Synset('green.a.03'), Synset('hayfield.n.01')]","[Synset('sawhorse.n.01'), Synset('stand.n.02'), Synset('tall.a.01'), Synset('eatage.n.01')]","[(two, NUM), (brown, a)]","[(brown, a)]","[Synset('knight.n.02'), Synset('stand.v.12'), Synset('hayfield.n.01')]","[Synset('sawhorse.n.01'), Synset('stand.n.02'), Synset('eatage.n.01')]",[Synset('green.a.03')],[Synset('tall.a.01')]

# 4. ANÁLISIS 2: TIPO Y DISTRIBUCIÓN DE TOKENS Y SYNSETS (...)
# 5. BAG OF WORDS (BoW)

In [12]:
# ========================================
# 5. BAG OF WORDS
# ========================================

# Creación de la Bag of Words (BoW) (de hecho, será una "Bag of synsets")
    # La necesitaremos luego como espacio vectorial para aplicar el método [Liu 2013] de similitud a nivel de frase.

tipo_bow = tipo_bow
print('Tipo_bow:', tipo_bow)
    
c['bow'] = c['syns1'] + c['syns2']
c['bow_errors'] =  c['errors1'] + c['errors2']
c['bow_nv'] =  c['syns1_nv'] + c['syns2_nv']
c['bow_resto'] =  c['syns1_resto'] + c['syns2_resto']

for i in c.index:
    c.at[i, 'bow'] = list(set(c.at[i, 'bow']))
    c.at[i, 'bow_errors'] = list(set(c.at[i, 'bow_errors']))    
    if tipo_bow == 'nv':
        c.at[i, 'bow_nv'] = list(set(c.at[i, 'bow_nv']))
        c.at[i, 'bow_resto'] = list(set(c.at[i, 'bow_resto']))

end_total = time.time()
print('TIEMPO TRANSCURRIDO:', end_total-start_total)

c.sample(5)

Tipo_bow: nv
TIEMPO TRANSCURRIDO: 66.24676990509033

,genre,file,year,id,gold_score,sent1,sent2,tokens1,tokens2,tagged_tokens1,tagged_tokens2,stops1,stops2,syns1,syns2,errors1,errors2,syns1_nv,syns2_nv,syns1_resto,syns2_resto,bow,bow_errors,bow_nv,bow_resto
3661,main-news,deft-news,2014,211,5.0,putin stated that the russian government could withdraw from the treaty altogether if western nations refuse to ratify the amended treaty.,putin stated that russia could discard the treaty entirely if western nations refuse to ratify its amended version.,"[putin, stated, russian, government, could, withdraw, treaty, altogether, western, nations, refuse, ratify, amended, treaty]","[putin, stated, russia, could, discard, treaty, entirely, western, nations, refuse, ratify, amended, version]","[(putin, n), (stated, v), (russian, a), (government, n), (could, v), (withdraw, v), (treaty, n), (altogether, r), (western, a), (nations, n), (refuse, v), (ratify, v), (amended, v), (treaty, n)]","[(putin, n), (stated, v), (russia, n), (could, v), (discard, v), (treaty, n), (entirely, r), (western, a), (nations, n), (refuse, v), (ratify, v), (amended, a), (version, n)]","[(that, ADP), (the, DET), (from, ADP), (the, DET), (if, ADP), (to, PRT), (the, DET)]","[(that, ADP), (the, DET), (if, ADP), (to, PRT), (its, PRON)]","[Synset('putin.n.01'), Synset('submit.v.02'), Synset('russian.a.01'), Synset('politics.n.02'), Synset('retire.v.02'), Synset('treaty.n.01'), Synset('wholly.r.01'), Synset('western.a.01'), Synset('state.n.04'), Synset('reject.v.06'), Synset('sign.v.02'), Synset('rectify.v.04'), Synset('treaty.n.01')]","[Synset('putin.n.01'), Synset('submit.v.02'), Synset('soviet_union.n.01'), Synset('discard.v.01'), Synset('treaty.n.01'), Synset('wholly.r.01'), Synset('western.a.01'), Synset('state.n.04'), Synset('reject.v.06'), Synset('sign.v.02'), Synset('amended.a.01'), Synset('version.n.06')]","[(could, v)]","[(could, v)]","[Synset('putin.n.01'), Synset('submit.v.02'), Synset('politics.n.02'), Synset('retire.v.02'), Synset('treaty.n.01'), Synset('state.n.04'), Synset('reject.v.06'), Synset('sign.v.02'), Synset('rectify.v.04'), Synset('treaty.n.01')]","[Synset('putin.n.01'), Synset('submit.v.02'), Synset('soviet_union.n.01'), Synset('discard.v.01'), Synset('treaty.n.01'), Synset('state.n.04'), Synset('reject.v.06'), Synset('sign.v.02'), Synset('version.n.06')]","[Synset('russian.a.01'), Synset('wholly.r.01'), Synset('western.a.01')]","[Synset('wholly.r.01'), Synset('western.a.01'), Synset('amended.a.01')]","[Synset('western.a.01'), Synset('soviet_union.n.01'), Synset('russian.a.01'), Synset('sign.v.02'), Synset('version.n.06'), Synset('state.n.04'), Synset('retire.v.02'), Synset('politics.n.02'), Synset('treaty.n.01'), Synset('rectify.v.04'), Synset('reject.v.06'), Synset('wholly.r.01'), Synset('submit.v.02'), Synset('putin.n.01'), Synset('amended.a.01'), Synset('discard.v.01')]","[(could, v)]","[Synset('soviet_union.n.01'), Synset('sign.v.02'), Synset('version.n.06'), Synset('state.n.04'), Synset('retire.v.02'), Synset('politics.n.02'), Synset('treaty.n.01'), Synset('rectify.v.04'), Synset('reject.v.06'), Synset('submit.v.02'), Synset('putin.n.01'), Synset('discard.v.01')]","[Synset('western.a.01'), Synset('wholly.r.01'), Synset('russian.a.01'), Synset('amended.a.01')]"
278,main-captions,MSRvid,2012test,414,3.4,A man is swinging from a rope attached to the ceiling.,A man is swinging on a rope.,"[man, swinging, rope, attached, ceiling]","[man, swinging, rope]","[(man, n), (swinging, v), (rope, n), (attached, v), (ceiling, n)]","[(man, n), (swinging, v), (rope, n)]","[(a, DET), (is, v), (from, ADP), (a, DET), (to, PRT), (the, DET)]","[(a, DET), (is, v), (on, ADP), (a, DET)]","[Synset('world.n.08'), Synset('swing.v.03'), Synset('rope.n.01'), Synset('attach.v.03'), Synset('ceiling.n.04')]","[Synset('world.n.08'), Synset('swing.v.03'), Synset('rope.n.01')]",[],[],"[Synset('world.n.08'), Synset('swing.v.03'), Synset('rope.n.01'), Synset('attach.v.03'), Synset('ceiling.n.04')]","[Synset('world.n.08'), Synset('swing.v.03'), Synset('rope.n.01')]",[],[],"[Synset('swing.v.03'), Synset('world.n.08'), Synset('rope.n.01'), Synset('ceiling.n.04'), Synset('attach.v.03')]",[],"[Synset('swing.v.03'), Synset('world.n.08'), Synset('rope.n.01'), Synset('ceiling.n.04'), Synset('attach.v.03')]",[]
870,main-captions,MSRvid,2012train,550,0.5,A woman is cooking broccoli.,A man is eating his food.,"[woman, cooking, broccoli]","[man, eating, food]","[(woman, n), (cooking, v), (broccoli, n)]","[(man, n), (eating, v), (food, n)]","[(a, DET), (is, v)]","[(a, DET), (is, v), (his, PRON)]","[Synset('womanhood.n.02'), Synset('fudge.v.01'), Synset('broccoli.n.02')]","[Synset('world.n.08'), Synset('eat.v.01'), Synset('food.n.03')]",[],[],"[Synset('womanhood.n.02'), Synset('fudge.v.01'), Synset('broccoli.n.02')]","[Synset('world.n.08'), Synset('eat.v.01'), Synset('food.n.03')]",[],[],"[Synset('food.n.03'), Synset('broccoli.n.02'), Synset('womanhood.n.02'), Synset('world.n.08'), Synset('eat.v.01'), Synset('fudge.v.01')]",[],"[Synset('food.n.03'), Synset('broccoli.n.02'), Synset('womanhood.n.02'), Synset('world.n.08'), Synset('eat.v.01'), Synset('fudge.v.01')]",[]
3266,main-news,MSRpar,2012train,486,4.0,But the inadequate performance of students in various subgroups tagged the state as deficient under the federal No Child Left Behind act.,"But the inadequate performance of students in various subgroups, such as race, pushed the state onto the needs-improvement list under the federal No Child Left Behind Act.","[inadequate, performance, students, various, subgroups, tagged, state, deficient, federal, child, left, behind, act]","[inadequate, performance, students, various, subgroups, race, pushed, state, onto, needs-improvement, list, federal, child, left, behind, act]","[(inadequate, a), (performance, n), (students, n), (various, a), (subgroups, n), (tagged, v), (state, n), (deficient, n), (federal, a), (child, n), (left, v), (behind, PRT), (act, n)]","[(inadequate, a), (performance, n), (students, n), (various, a), (subgroups, n), (race, n), (pushed, v), (state, n), (onto, ADP), (needs-improvement, a), (list, n), (federal, a), (child, n), (left, v), (behind, PRT), (act, n)]","[(but, CONJ), (the, DET), (of, ADP), (in, ADP), (the, DET), (as, ADP), (under, ADP), (the, DET), (no, DET)]","[(but, CONJ), (the, DET), (of, ADP), (in, ADP), (such, a), (as, ADP), (the, DET), (the, DET), (under, ADP), (the, DET), (no, DET)]","[Synset('inadequate.a.01'), Synset('performance.n.03'), Synset('student.n.01'), Synset('subgroup.n.02'), Synset('tag.v.05'), Synset('state.n.06'), Synset('federal.a.04'), Synset('child.n.04'), Synset('leave.v.03'), Synset('act.n.04')]","[Synset('inadequate.a.01'), Synset('performance.n.03'), Synset('student.n.01'), Synset('subgroup.n.02'), Synset('subspecies.n.01'), Synset('push.v.01'), Synset('state.n.06'), Synset('tilt.n.04'), Synset('federal.a.04'), Synset('child.n.04'), Synset('leave.v.03'), Synset('act.n.04')]","[(various, a), (deficient, n), (behind, PRT)]","[(various, a), (onto, ADP), (needs-improvement, a), (behind, PRT)]","[Synset('performance.n.03'), Synset('student.n.01'), Synset('subgroup.n.02'), Synset('tag.v.05'), Synset('state.n.06'), Synset('child.n.04'), Synset('leave.v.03'), Synset('act.n.04')]","[Synset('performance.n.03'), Synset('student.n.01'), Synset('subgroup.n.02'), Synset('subspecies.n.01'), Synset('push.v.01'), Synset('state.n.06'), Synset('tilt.n.04'), Synset('child.n.04'), Synset('leave.v.03'), Synset('act.n.04')]","[Synset('inadequate.a.01'), Synset('federal.a.04')]","[Synset('inadequate.a.01'), Synset('federal.a.04')]","[Synset('subgroup.n.02'), Synset('federal.a.04'), Synset('tilt.n.04'), Synset('inadequate.a.01'), Synset('act.n.04'), Synset('student.n.01'), Synset('performance.n.03'), Synset('state.n.06'), Synset('subspecies.n.01'), Synset('tag.v.05'), Synset('push.v.01'), Synset('leave.v.03'), Synset('child.n.04')]","[(deficient, n), (behind, PRT), (onto, ADP), (various, a), (needs-improvement, a)]","[Synset('subgroup.n.02'), Synset('tilt.n.04'), Synset('act.n.04'), Synset('student.n.01'), Synset('performance.n.03'), Synset('state.n.06'), Synset('subspecies.n.01'), Synset('tag.v.05'), Synset('push.v.01'), Synset('leave.v.03'), Synset('child.n.04')]","[Synset('federal.a.04'), Synset('inadequate.a.01')]"
3968,main-news,headlines,2013,271,1.0,Santorum Romping To Minnesota Victory,Santorum wins Kansas caucuses,"[santorum, romping, minnesota, victory]","[santorum, wins, kansas, caucuses]","[(santorum, n), (romping, v), (minnesota, v), (victory, n)]","[(santorum, n), (wins, v), (kansas, a), (caucuses, n)]","[(to, PRT)]",[],"[Synset('romp.v.03'), Synset('victory.n.01')]","[Synset('win.v.01'), Synset('caucus.n.01')]","[(santorum, n), (minnesota, v)]","[(santorum, n), (kansas, a)]","[Synset('romp.v.03'), Synset('victory.n.01')]","[Synset('win.v.01'), Synset('caucus.n.01')]",[],[],"[Synset('caucus.n.01'), Synset('win.v.01'), Synset('romp.v.03'), Synset('victory.n.01')]","[(santorum, n), (kansas, a), (minnesota, v)]","[Synset('caucus.n.01'), Synset('win.v.01'), Synset('romp.v.03'), Synset('victory.n.01')]",[]

# 6. SIMILITUD A NIVEL LÉXICO - MÉTODOS INCLUÍDOS EN WORDNET

In [13]:
# ========================================
# 6. SIMILITUD A NIVEL LÉXICO - MÉTODOS INCLUÍDOS EN WORDNET
# ========================================

# Ejemplos de funciones de similitud integradas en Wordnet

    # ps --> path_similarity (POR DEFECTO). Rango: [0:1]
    # lch --> Leacock Chodorow. Rango: [0:3.64?] 
    # wup --> Wu_Palmer
    # res --> Resknik (requiere corpus ic)
    # jcn --> Jiang-Conrath (requiere corpus ic)
    # lin --> Lin (requiere corpus ic)

# Ejemplos para comprobar funcionamiento de los distintos métodos de simlitud de wordnet
    
syn1 = wn.synset('dog.n.01')
syn2 = wn.synset('cat.n.01')
syn3 = wn.synset('black.a.01')
syn4 = wn.synset('white.a.01')

try: print('wn.path_similarity(', syn1, syn1, '):',  wn.path_similarity(syn1, syn1))
except Exception as e: print('ERROR', e)
try: print('wn.path_similarity(', syn1, syn2, '):',  wn.path_similarity(syn1, syn2))
except Exception as e: print('ERROR', e)
try: print('wn.path_similarity(', syn1, syn3, '):',  wn.path_similarity(syn1, syn3))
except Exception as e: print('ERROR', e)
try: print('wn.path_similarity(', syn3, syn4, '):',  wn.path_similarity(syn3, syn4))
except Exception as e: print('ERROR', e)
    
print()

try: print('wn.lch_similarity(', syn1, syn1, '):',  wn.lch_similarity(syn1, syn1))
except Exception as e: print('ERROR', e)
try: print('wn.lch_similarity(', syn1, syn2, '):',  wn.lch_similarity(syn1, syn2))
except Exception as e: print('ERROR', e)
try: rint('wn.lch_similarity(', syn1, syn3, '):',  wn.lch_similarity(syn1, syn3))
except Exception as e: print('ERROR', e)
try: print('wn.lch_similarity(', syn3, syn4, '):',  wn.lch_similarity(syn3, syn4))
except Exception as e: print('ERROR', e)    

print()

try: print('wn.wup_similarity(', syn1, syn1, '):',  wn.wup_similarity(syn1, syn1))
except Exception as e: print('ERROR', e)
try: print('wn.wup_similarity(', syn1, syn2, '):',  wn.wup_similarity(syn1, syn2))
except Exception as e: print('ERROR', e)
try: print('wn.wup_similarity(', syn1, syn3, '):',  wn.wup_similarity(syn1, syn3))
except Exception as e: print('ERROR', e)
try: print('wn.wup_similarity(', syn3, syn4, '):',  wn.wup_similarity(syn3, syn4))
except Exception as e: print('ERROR', e)    

print()

ic = ic_brown
print('ic_brown')
try: print('wn.lch_similarity(', syn1, syn1, '):',  wn.res_similarity(syn1, syn1, ic))
except Exception as e: print('ERROR', e)
try: print('wn.lch_similarity(', syn1, syn2, '):',  wn.res_similarity(syn1, syn2, ic))
except Exception as e: print('ERROR', e)
try: print('wn.lch_similarity(', syn1, syn3, '):',  wn.res_similarity(syn1, syn3, ic))
except Exception as e: print('ERROR', e)
try: print('wn.lch_similarity(', syn3, syn4, '):',  wn.res_similarity(syn3, syn4, ic))
except Exception as e: print('ERROR', e)

print()

try: print('wn.jcn_similarity(', syn1, syn1, '):',  wn.jcn_similarity(syn1, syn1, ic))
except Exception as e: print('ERROR', e)
try: print('wn.jcn_similarity(', syn1, syn2, '):',  wn.jcn_similarity(syn1, syn2, ic))
except Exception as e: print('ERROR', e)
try: print('wn.jcn_similarity(', syn1, syn3, '):',  wn.jcn_similarity(syn1, syn3, ic))
except Exception as e: print('ERROR', e)
try: print('wn.jcn_similarity(', syn3, syn4, '):',  wn.jcn_similarity(syn3, syn4, ic))
except Exception as e: print('ERROR', e)

print()

try: print('wn.lin_similarity(', syn1, syn1, '):',  wn.lin_similarity(syn1, syn1, ic))
except Exception as e: print('ERROR', e)
try: print('wn.lin_similarity(', syn1, syn2, '):',  wn.lin_similarity(syn1, syn2, ic))
except Exception as e: print('ERROR', e)
try: print('wn.lin_similarity(', syn1, syn3, '):',  wn.lin_similarity(syn1, syn3, ic))
except Exception as e: print('ERROR', e)
try: print('wn.lin_similarity(', syn3, syn4, '):',  wn.lin_similarity(syn3, syn4, ic))
except Exception as e: print('ERROR', e)

print()

ic = ic_semcor
print('ic_brown')
try: print('wn.lch_similarity(', syn1, syn1, '):',  wn.res_similarity(syn1, syn1, ic))
except Exception as e: print('ERROR', e)
try: print('wn.lch_similarity(', syn1, syn2, '):',  wn.res_similarity(syn1, syn2, ic))
except Exception as e: print('ERROR', e)
try: print('wn.lch_similarity(', syn1, syn3, '):',  wn.res_similarity(syn1, syn3, ic))
except Exception as e: print('ERROR', e)
try: print('wn.lch_similarity(', syn3, syn4, '):',  wn.res_similarity(syn3, syn4, ic))
except Exception as e: print('ERROR', e)

print()

try: print('wn.jcn_similarity(', syn1, syn1, '):',  wn.jcn_similarity(syn1, syn1, ic))
except Exception as e: print('ERROR', e)
try: print('wn.jcn_similarity(', syn1, syn2, '):',  wn.jcn_similarity(syn1, syn2, ic))
except Exception as e: print('ERROR', e)
try: print('wn.jcn_similarity(', syn1, syn3, '):',  wn.jcn_similarity(syn1, syn3, ic))
except Exception as e: print('ERROR', e)
try: print('wn.jcn_similarity(', syn3, syn4, '):',  wn.jcn_similarity(syn3, syn4, ic))
except Exception as e: print('ERROR', e)

print()

try: print('wn.lin_similarity(', syn1, syn1, '):',  wn.lin_similarity(syn1, syn1, ic))
except Exception as e: print('ERROR', e)
try: print('wn.lin_similarity(', syn1, syn2, '):',  wn.lin_similarity(syn1, syn2, ic))
except Exception as e: print('ERROR', e)
try: print('wn.lin_similarity(', syn1, syn3, '):',  wn.lin_similarity(syn1, syn3, ic))
except Exception as e: print('ERROR', e)
try: print('wn.lin_similarity(', syn3, syn4, '):',  wn.lin_similarity(syn3, syn4, ic))
except Exception as e: print('ERROR', e)

print()

ic = ic_genesis
print('ic_brown')
try: print('wn.lch_similarity(', syn1, syn1, '):',  wn.res_similarity(syn1, syn1, ic))
except Exception as e: print('ERROR', e)
try: print('wn.lch_similarity(', syn1, syn2, '):',  wn.res_similarity(syn1, syn2, ic))
except Exception as e: print('ERROR', e)
try: print('wn.lch_similarity(', syn1, syn3, '):',  wn.res_similarity(syn1, syn3, ic))
except Exception as e: print('ERROR', e)
try: print('wn.lch_similarity(', syn3, syn4, '):',  wn.res_similarity(syn3, syn4, ic))
except Exception as e: print('ERROR', e)

print()

try: print('wn.jcn_similarity(', syn1, syn1, '):',  wn.jcn_similarity(syn1, syn1, ic))
except Exception as e: print('ERROR', e)
try: print('wn.jcn_similarity(', syn1, syn2, '):',  wn.jcn_similarity(syn1, syn2, ic))
except Exception as e: print('ERROR', e)
try: print('wn.jcn_similarity(', syn1, syn3, '):',  wn.jcn_similarity(syn1, syn3, ic))
except Exception as e: print('ERROR', e)
try: print('wn.jcn_similarity(', syn3, syn4, '):',  wn.jcn_similarity(syn3, syn4, ic))
except Exception as e: print('ERROR', e)

print()

try: print('wn.lin_similarity(', syn1, syn1, '):',  wn.lin_similarity(syn1, syn1, ic))
except Exception as e: print('ERROR', e)
try: print('wn.lin_similarity(', syn1, syn2, '):',  wn.lin_similarity(syn1, syn2, ic))
except Exception as e: print('ERROR', e)
try: print('wn.lin_similarity(', syn1, syn3, '):',  wn.lin_similarity(syn1, syn3, ic))
except Exception as e: print('ERROR', e)
try: print('wn.lin_similarity(', syn3, syn4, '):',  wn.lin_similarity(syn3, syn4, ic))
except Exception as e: print('ERROR', e)

print()

end_total = time.time()
print('TIEMPO TRANSCURRIDO:', end_total-start_total)

wn.path_similarity( Synset('dog.n.01') Synset('dog.n.01') ): 1.0
wn.path_similarity( Synset('dog.n.01') Synset('cat.n.01') ): 0.2
wn.path_similarity( Synset('dog.n.01') Synset('black.a.01') ): None
wn.path_similarity( Synset('black.a.01') Synset('white.a.01') ): None

wn.lch_similarity( Synset('dog.n.01') Synset('dog.n.01') ): 3.6375861597263857
wn.lch_similarity( Synset('dog.n.01') Synset('cat.n.01') ): 2.0281482472922856
ERROR name 'rint' is not defined
wn.lch_similarity( Synset('black.a.01') Synset('white.a.01') ): None

wn.wup_similarity( Synset('dog.n.01') Synset('dog.n.01') ): 0.9285714285714286
wn.wup_similarity( Synset('dog.n.01') Synset('cat.n.01') ): 0.8571428571428571
wn.wup_similarity( Synset('dog.n.01') Synset('black.a.01') ): None
wn.wup_similarity( Synset('black.a.01') Synset('white.a.01') ): None

ic_brown
wn.lch_similarity( Synset('dog.n.01') Synset('dog.n.01') ): 9.006014398918229
wn.lch_similarity( Synset('dog.n.01') Synset('cat.n.01') ): 7.911666509036577
ERROR Computing the least common subsumer requires Synset('dog.n.01') and Synset('black.a.01') to have the same part of speech.
ERROR Information content file has no entries for part-of-speech: a

wn.jcn_similarity( Synset('dog.n.01') Synset('dog.n.01') ): 1e+300
wn.jcn_similarity( Synset('dog.n.01') Synset('cat.n.01') ): 0.4497755285516739
ERROR Computing the least common subsumer requires Synset('dog.n.01') and Synset('black.a.01') to have the same part of speech.
ERROR Information content file has no entries for part-of-speech: a

wn.lin_similarity( Synset('dog.n.01') Synset('dog.n.01') ): 1.0
wn.lin_similarity( Synset('dog.n.01') Synset('cat.n.01') ): 0.8768009843733973
ERROR Computing the least common subsumer requires Synset('dog.n.01') and Synset('black.a.01') to have the same part of speech.
ERROR Information content file has no entries for part-of-speech: a

ic_brown
wn.lch_similarity( Synset('dog.n.01') Synset('dog.n.01') ): 7.7404081579094255
wn.lch_similarity( Synset('dog.n.01') Synset('cat.n.01') ): 7.2549003421277245
ERROR Computing the least common subsumer requires Synset('dog.n.01') and Synset('black.a.01') to have the same part of speech.
ERROR Information content file has no entries for part-of-speech: a

wn.jcn_similarity( Synset('dog.n.01') Synset('dog.n.01') ): 1e+300
wn.jcn_similarity( Synset('dog.n.01') Synset('cat.n.01') ): 0.537382154955756
ERROR Computing the least common subsumer requires Synset('dog.n.01') and Synset('black.a.01') to have the same part of speech.
ERROR Information content file has no entries for part-of-speech: a

wn.lin_similarity( Synset('dog.n.01') Synset('dog.n.01') ): 1.0
wn.lin_similarity( Synset('dog.n.01') Synset('cat.n.01') ): 0.8863288628086228
ERROR Computing the least common subsumer requires Synset('dog.n.01') and Synset('black.a.01') to have the same part of speech.
ERROR Information content file has no entries for part-of-speech: a

ic_brown
wn.lch_similarity( Synset('dog.n.01') Synset('dog.n.01') ): 9.955559304416786
wn.lch_similarity( Synset('dog.n.01') Synset('cat.n.01') ): 7.204023991374837
ERROR Computing the least common subsumer requires Synset('dog.n.01') and Synset('black.a.01') to have the same part of speech.
wn.lch_similarity( Synset('black.a.01') Synset('white.a.01') ): 0

wn.jcn_similarity( Synset('dog.n.01') Synset('dog.n.01') ): 1e+300
wn.jcn_similarity( Synset('dog.n.01') Synset('cat.n.01') ): 0.28539390848096946
ERROR Computing the least common subsumer requires Synset('dog.n.01') and Synset('black.a.01') to have the same part of speech.
wn.jcn_similarity( Synset('black.a.01') Synset('white.a.01') ): 0.04872272997299587

wn.lin_similarity( Synset('dog.n.01') Synset('dog.n.01') ): 1.0
wn.lin_similarity( Synset('dog.n.01') Synset('cat.n.01') ): 0.8043806652422293
ERROR Computing the least common subsumer requires Synset('dog.n.01') and Synset('black.a.01') to have the same part of speech.
wn.lin_similarity( Synset('black.a.01') Synset('white.a.01') ): 0.0

TIEMPO TRANSCURRIDO: 74.99766564369202

# 7. SIMILITUD A NIVEL DE FRASE - LIU-WANG

In [14]:
# ========================================
# 8. SIMILITUD A NIVEL DE FRASE - LIU-WANG
# ========================================

# 8.1 Vector semántico
    # Entrada: Un conjunto de synsets (frase) y una bag of words (bow) conteniendo el conjunto de synsets
        # si el parámetro "info" es "print", se mostrará información durante el proceso de cálculo
    # Argumentos: 
        # medida : función de similitud léxica que se quiere usar:
            # ps --> path_similarity (POR DEFECTO). 
                # Rango: [0:1]
            # lch --> Leacock Chodorow. 
                # Rango: [0:3.64?] 
            # wup --> Wu_Palmer
                # Rango: ]
            # res --> Resknik (requiere corpus ic)
                # Rango = [0-14,47]
                # Mismo synset --> Depende del synset (IC)
                # La palabra no está en el corpus --> infinito
                    # MODIFICACIÓN: Asignamos la media ponderada dentro del rango --> 9,04
            # jcn --> Jiang-Conrath (requiere corpus ic)
                # Rango = [0,1]
                # Mismo synset --> similitud = infinito (e+300)
                    # MODIFICACIÓN: Asignamos mismo synset --> similitud = 1
            # lin --> Lin (requiere corpus ic)
            # lw --> Liu-Wang
        # ic: corpus ic, para las funciones que lo requieran.
            # Intentar reproducir https://www.kdnuggets.com/2017/11/building-wikipedia-text-corpus-nlp.html
        # info: si 'print', se imprimirá información sobre el procesamiento.
    # Requerimientos: Haber importado wordnet_ic (si se utilizan las opciones res,jcn,lin)
    # Salida: Vector semántico del conjunto de synsets en el espacio definido por bow

def v_semantico(syns, bow, medida='ps', ic = '', info=''):
    v = np.zeros(len(bow), dtype=np.float)    

    if info == 'print': 
        print('bow:', bow)
        print('syns:', syns)
        print()
        print('Cálculo del vector semántico v correspondiente a syns en el espacio bow')
        print('v:', v)
        print()    
        print('Método de similitud léxica:', medida)
        print()       

    for index, synset in enumerate(bow):  
        if info == 'print': 
            print('Componente de v (index):', index)
            print('synset de bow correspondiente a index =',index, ':', synset)
            print('Valor inicial de la componente v', index, ':', v[index])
            print()
            print('Calculo del valor de la componente v', index)
            print()
        sims = list()
        for syn in syns:
            if info == 'print':
                print('Cálculo de la similitud de synset de bow con synset de syns:', synset, '<-->', syn)
                print()
            sim = 0.0
            if syn.pos() == synset.pos():
                if medida == 'ps':
                    sim = wn.path_similarity(syn, synset)
                elif medida == 'lch':
                    sim = wn.lch_similarity(syn, synset)
                elif medida == 'wup':
                    sim = wn.wup_similarity(syn, synset)
                elif medida == 'res':                    
                    sim = wn.res_similarity(syn, synset, ic)
                    if sim == 1.00000000e+300:
                        sim = 9.04
                elif medida == 'jcn':
                    if syn == synset:
                        sim = 1
                    else:
                        sim = wn.jcn_similarity(syn, synset, ic)
                elif medida == 'lin':
                    sim = wn.lin_similarity(syn, synset, ic)
                if info == 'print':
                    print('similitud:', sim)
                if sim is None: continue
                    
            else:
                sim = 0.0
                if info == 'print':
                    print(synset, 'y', syn, 'no pertenecen a la misma categoría gramatical')    
                    print('Similitud Liu ', synset, '<-->', syn, ':', sim)
            if sim != 'nan': 
                sims.append(sim)
            if info == 'print': print()
        v[index] = max(sims)
        if info == 'print':
            print('Valores de las similitudes:', sims)
            print("Valor de la componente v", index, '(máximo de las similitudes):', v[index])
            print()
    if info == 'print': print('v = ', v)
    if info == 'print': print()
    return(v)

    
# Ejemplo para comprobar funcionamiento v_semantico()

print('****** EJEMPLO v_semantico() ********')   

bow = c['bow'][501]
syns1 = c['syns1'][501]
syns2 = c['syns2'][501]
info = ''
ic = ''

print('bow:', bow)
print('syns1:', syns1)
print('syns2:', syns2)

print()
print('SIMILITUD LIU - WANG')

medida = 'lw'
print('v_semantico(syns1, bow, medida=\'', medida, '\', info=\'',  info, '\' , ic=\'\'):', v_semantico(syns1, bow, medida=medida, ic=ic, info=info))
print('v_semantico(syns2, bow, medida=\'', medida, '\', info=\'',  info, '\' , ic=\'\'):', v_semantico(syns2, bow, medida=medida, ic=ic, info=info))

print()
print('SIMILITUDES DE WN QUE NO REQUIEREN IC')

medida = 'ps'
print('v_semantico(syns1, bow, medida=\'', medida, '\', info=\'',  info, '\' , ic=\'\'):', v_semantico(syns1, bow, medida=medida, ic=ic, info=info))
print('v_semantico(syns2, bow, medida=\'', medida, '\', info=\'',  info, '\' , ic=\'\'):', v_semantico(syns2, bow, medida=medida, ic=ic, info=info))

medida = 'lch'
print('v_semantico(syns1, bow, medida=\'', medida, '\', info=\'',  info, '\' , ic=\'\'):', v_semantico(syns1, bow, medida=medida, ic=ic, info=info))
print('v_semantico(syns2, bow, medida=\'', medida, '\', info=\'',  info, '\' , ic=\'\'):', v_semantico(syns2, bow, medida=medida, ic=ic, info=info))

medida = 'wup'
print('v_semantico(syns1, bow, medida=\'', medida, '\', info=\'',  info, '\' , ic=\'\'):', v_semantico(syns1, bow, medida=medida, ic=ic, info=info))
print('v_semantico(syns2, bow, medida=\'', medida, '\', info=\'',  info, '\' , ic=\'\'):', v_semantico(syns2, bow, medida=medida, ic=ic, info=info))

print()
print('SIMILITUDES DE WN QUE REQUIEREN IC. IC = BROWN')

ic = ic_brown

medida = 'res'
print('v_semantico(syns1, bow, medida=\'', medida, '\', info=\'',  info, '\' , ic=\'\'):', v_semantico(syns1, bow, medida=medida, ic=ic, info=info))
print('v_semantico(syns2, bow, medida=\'', medida, '\', info=\'',  info, '\' , ic=\'\'):', v_semantico(syns2, bow, medida=medida, ic=ic, info=info))

medida = 'jcn'
print('v_semantico(syns1, bow, medida=\'', medida, '\', info=\'',  info, '\' , ic=\'\'):', v_semantico(syns1, bow, medida=medida, ic=ic, info=info))
print('v_semantico(syns2, bow, medida=\'', medida, '\', info=\'',  info, '\' , ic=\'\'):', v_semantico(syns2, bow, medida=medida, ic=ic, info=info))

medida = 'lin'
print('v_semantico(syns1, bow, medida=\'', medida, '\', info=\'',  info, '\' , ic=\'\'):', v_semantico(syns1, bow, medida=medida, ic=ic, info=info))
print('v_semantico(syns2, bow, medida=\'', medida, '\', info=\'',  info, '\' , ic=\'\'):', v_semantico(syns2, bow,medida=medida, ic=ic, info=info))

print()
print('SIMILITUDES DE WN QUE REQUIEREN IC. IC = SEMCOR')
     
ic = ic_semcor

medida = 'res'
print('v_semantico(syns1, bow, medida=\'', medida, '\', info=\'',  info, '\' , ic=\'semcor\'):', v_semantico(syns1, bow, medida=medida, ic=ic, info=info))
print('v_semantico(syns2, bow, medida=\'', medida, '\', info=\'',  info, '\' , ic=\'semcor\'):', v_semantico(syns2, bow, medida=medida, ic=ic, info=info))

medida = 'jcn'
print('v_semantico(syns1, bow, medida=\'', medida, '\', info=\'',  info, '\' , ic=\'semcor\'):', v_semantico(syns1, bow, medida=medida, ic=ic, info=info))
print('v_semantico(syns2, bow, medida=\'', medida, '\', info=\'',  info, '\' , ic=\'semcor\'):', v_semantico(syns2, bow, medida=medida, ic=ic, info=info))

medida = 'lin'
print('v_semantico(syns1, bow, medida=\'', medida, '\', info=\'',  info, '\' , ic=\'semcor\'):', v_semantico(syns1, bow, medida=medida, ic=ic, info=info))
print('v_semantico(syns2, bow, medida=\'', medida, '\', info=\'',  info, '\' , ic=\'semcor\'):', v_semantico(syns2, bow, medida=medida, ic=ic, info=info))

print()
print('SIMILITUDES DE WN QUE REQUIEREN IC. IC = GENESIS')
     
ic = ic_genesis

medida = 'res'
print('v_semantico(syns1, bow, medida=\'', medida, '\', info=\'',  info, '\' , ic=\'semcor\'):', v_semantico(syns1, bow, medida=medida, ic=ic, info=info))
print('v_semantico(syns2, bow, medida=\'', medida, '\', info=\'',  info, '\' , ic=\'semcor\'):', v_semantico(syns2, bow, medida=medida, ic=ic, info=info))

medida = 'jcn'
print('v_semantico(syns1, bow, medida=\'', medida, '\', info=\'',  info, '\' , ic=\'semcor\'):', v_semantico(syns1, bow, medida=medida, ic=ic, info=info))
print('v_semantico(syns2, bow, medida=\'', medida, '\', info=\'',  info, '\' , ic=\'semcor\'):', v_semantico(syns2, bow, medida=medida, ic=ic, info=info))

medida = 'lin'
print('v_semantico(syns1, bow, medida=\'', medida, '\', info=\'',  info, '\' , ic=\'semcor\'):', v_semantico(syns1, bow, medida=medida, ic=ic, info=info))
print('v_semantico(syns2, bow, medida=\'', medida, '\', info=\'',  info, '\' , ic=\'semcor\'):', v_semantico(syns2, bow, medida=medida, ic=ic, info=info))


print('****')

end_total = time.time()
print('TIEMPO TRANSCURRIDO:', end_total-start_total)

****** EJEMPLO v_semantico() ********
bow: [Synset('cut.v.24'), Synset('womanhood.n.02'), Synset('onion.n.01')]
syns1: [Synset('womanhood.n.02'), Synset('cut.v.24'), Synset('onion.n.01')]
syns2: [Synset('womanhood.n.02'), Synset('cut.v.24'), Synset('onion.n.01')]

SIMILITUD LIU - WANG
v_semantico(syns1, bow, medida=' lw ', info='  ' , ic=''): [0. 0. 0.]
v_semantico(syns2, bow, medida=' lw ', info='  ' , ic=''): [0. 0. 0.]

SIMILITUDES DE WN QUE NO REQUIEREN IC
v_semantico(syns1, bow, medida=' ps ', info='  ' , ic=''): [1. 1. 1.]
v_semantico(syns2, bow, medida=' ps ', info='  ' , ic=''): [1. 1. 1.]
v_semantico(syns1, bow, medida=' lch ', info='  ' , ic=''): [3.25809654 3.63758616 3.63758616]
v_semantico(syns2, bow, medida=' lch ', info='  ' , ic=''): [3.25809654 3.63758616 3.63758616]
v_semantico(syns1, bow, medida=' wup ', info='  ' , ic=''): [1. 1. 1.]
v_semantico(syns2, bow, medida=' wup ', info='  ' , ic=''): [1. 1. 1.]

SIMILITUDES DE WN QUE REQUIEREN IC. IC = BROWN
v_semantico(syns1, bow, medida=' res ', info='  ' , ic=''): [ 9.3067605   8.4253452  11.57522816]
v_semantico(syns2, bow, medida=' res ', info='  ' , ic=''): [ 9.3067605   8.4253452  11.57522816]
v_semantico(syns1, bow, medida=' jcn ', info='  ' , ic=''): [1. 1. 1.]
v_semantico(syns2, bow, medida=' jcn ', info='  ' , ic=''): [1. 1. 1.]
v_semantico(syns1, bow, medida=' lin ', info='  ' , ic=''): [1. 1. 1.]
v_semantico(syns2, bow, medida=' lin ', info='  ' , ic=''): [1. 1. 1.]

SIMILITUDES DE WN QUE REQUIEREN IC. IC = SEMCOR
v_semantico(syns1, bow, medida=' res ', info='  ' , ic='semcor'): [9.04 9.04 9.04]
v_semantico(syns2, bow, medida=' res ', info='  ' , ic='semcor'): [9.04 9.04 9.04]
v_semantico(syns1, bow, medida=' jcn ', info='  ' , ic='semcor'): [1. 1. 1.]
v_semantico(syns2, bow, medida=' jcn ', info='  ' , ic='semcor'): [1. 1. 1.]
v_semantico(syns1, bow, medida=' lin ', info='  ' , ic='semcor'): [1. 1. 1.]
v_semantico(syns2, bow, medida=' lin ', info='  ' , ic='semcor'): [1. 1. 1.]

SIMILITUDES DE WN QUE REQUIEREN IC. IC = GENESIS
v_semantico(syns1, bow, medida=' res ', info='  ' , ic='semcor'): [11.89613931  8.46390443  9.04      ]
v_semantico(syns2, bow, medida=' res ', info='  ' , ic='semcor'): [11.89613931  8.46390443  9.04      ]
v_semantico(syns1, bow, medida=' jcn ', info='  ' , ic='semcor'): [1. 1. 1.]
v_semantico(syns2, bow, medida=' jcn ', info='  ' , ic='semcor'): [1. 1. 1.]
v_semantico(syns1, bow, medida=' lin ', info='  ' , ic='semcor'): [1. 1. 1.]
v_semantico(syns2, bow, medida=' lin ', info='  ' , ic='semcor'): [1. 1. 1.]
****
TIEMPO TRANSCURRIDO: 75.86715269088745

In [15]:
# 8.2 Similitud de frase Liu-Wang
    # Entrada: Dos vectores semánticos
    # Salida: Similitud entre las dos frases, calculada como el coseno entre los dos vectores semánticos
    
def similitud_frase_lw(v1, v2):
        
    sim = coseno(v1, v2)
    
    return(sim)

# Ejemplo para comprobar funcionamiento similitud_frase_liu()

print('****** EJEMPLO similitud_frase() ********')   

v1 = v_semantico(syns1, bow, medida=medida, ic=ic, info=info)
v2 = v_semantico(syns2, bow, medida=medida, ic=ic, info=info)
print('Similitud a nivel de frase', similitud_frase_lw(v1, v2))
print('****')

end_total = time.time()
print('TIEMPO TRANSCURRIDO:', end_total-start_total)

****** EJEMPLO similitud_frase() ********
Similitud a nivel de frase 1.0
****
TIEMPO TRANSCURRIDO: 75.87806558609009

In [16]:
# Cálculo y almacenamiento de la puntuación Liu-Wang a nivel de frase

if metodo_frase == 'lw':

    c['v1_ps'] = ''  # OK
    c['v2_ps'] = ''  # OK

    c['v1_lch'] = ''  # OK
    c['v2_lch'] = ''  # OK

    c['v1_wup'] = '' # OK
    c['v2_wup'] = '' # OK

    c['v1_res_brown'] = '' # Resultats no fiables quan la paraula no està al Corpus --> PROVAR IF ABANS; BoW_nv!!!!
    c['v2_res_brown'] = ''  # Resultats no fiables quan la paraula no està al Corpus --> PROVAR IF ABANS; BoW_nv!!!!

    c['v1_res_semcor'] = ''
    c['v2_res_semcor'] = ''

    c['v1_res_genesis'] = ''
    c['v2_res_genesis'] = ''

    c['v1_jcn_brown'] = '' # Components infinites quan les paraules són iguals --> ESTABLIR UN MÀXIM ; BoW_nv!!!!
    c['v2_jcn_brown'] = '' # Components infinites quan les paraules són iguals --> ESTABLIR UN MÀXIM ; BoW_nv!!!!

    c['v1_jcn_semcor'] = ''
    c['v2_jcn_semcor'] = ''

    c['v1_jcn_genesis'] = ''
    c['v2_jcn_genesis'] = ''

    c['v1_lin_brown'] = ''
    c['v2_lin_brown'] = ''

    c['v1_lin_semcor'] = ''
    c['v2_lin_semcor'] = ''

    c['v1_lin_genesis'] = ''
    c['v2_lin_genesis'] = ''
    

    c['puntuacion_lw_ps'] = 0.0  # OK, Pearson 0.66
    c['puntuacion_lw_lch'] = 0.0  # OK, Pearson 0.49
    c['puntuacion_lw_wup'] = 0.0 # OK, Pearson 0.42
    c['puntuacion_lw_res_brown'] = 0.0 # OK, Pearson 0.77 MILLORABLE 
    c['puntuacion_lw_res_genesis'] = 0.0
    c['puntuacion_lw_jcn_brown'] = 0.0  # Tots els resultats són zero.
    c['puntuacion_lw_jcn_semcor'] = 0.0
    c['puntuacion_lw_jcn_genesis'] = 0.0
    c['puntuacion_lw_lin_brown'] = 0.0
    c['puntuacion_lw_lin_semcor'] = 0.0
    c['puntuacion_lw_lin_genesis'] = 0.0

    # print_info = 's'

    for i in c.index:  
        gold_score = c.at[i, 'gold_score']
        sent1 = c.at[i, 'sent1']
        sent2 = c.at[i, 'sent2']
        syns1 = c.at[i, 'syns1']
        syns2 = c.at[i, 'syns2']
        if tipo_bow == 'nv':
            bow = c.at[i, 'bow_nv']
        else:
            bow = c.at[i, 'bow']
        start = time.time()
        if print_info == 's':
            print('FILA:', i)
            print('Gold score:', c.at[i, 'gold_score'])
            print('sent1:', c.at[i, 'sent1'])
            print('sent2:', c.at[i, 'sent2'])
            print('syns1:', c.at[i, 'syns1'])
            print('syns2:', c.at[i, 'syns2'])
            print('bow:', bow)

        try: c.at[i, 'v1_ps'] = v_semantico(c.at[i, 'syns1'], bow, medida='ps', ic='', info=info)
        except:  c.at[i, 'v1_ps'] = None
        try: c.at[i, 'v2_ps'] = v_semantico(c.at[i, 'syns2'], bow, medida='ps', ic='', info=info)
        except:  c.at[i, 'v2_ps'] = None
        try: c.at[i, 'puntuacion_lw_ps'] = similitud_frase_lw(c.at[i, 'v1_ps'], c.at[i, 'v2_ps'] )
        except:  c.at[i, 'puntuacion_lw_ps'] = None

        if print_info == 's':
            print('v1_ps', i, ': ', c.at[i, 'v1_ps'])
            print('v2_ps', i, ': ', c.at[i, 'v2_ps'])
            print('puntuacion_lw_ps', i, ': ', c.at[i, 'puntuacion_lw_ps'])

        try: c.at[i, 'v1_lch'] = v_semantico(c.at[i, 'syns1'], bow, medida='lch', ic='', info=info)
        except:  c.at[i, 'v1_lch'] = None
        try: c.at[i, 'v2_lch'] = v_semantico(c.at[i, 'syns2'], bow, medida='lch', ic='', info=info)
        except:  c.at[i, 'v2_lch'] = None
        try: c.at[i, 'puntuacion_lw_lch'] = similitud_frase_lw(c.at[i, 'v1_lch'], c.at[i, 'v2_lch'] )
        except:  c.at[i, 'puntuacion_lw_lch'] = None

        if print_info == 's':
            print('v1_lch', i, ': ', c.at[i, 'v1_lch'])
            print('v2_lch', i, ': ', c.at[i, 'v2_lch'])
            print('puntuacion_lw_lch', i, ': ', c.at[i, 'puntuacion_lw_lch'])

        try: c.at[i, 'v1_wup'] = v_semantico(c.at[i, 'syns1'], bow, medida='wup', ic='', info=info)
        except:  c.at[i, 'v1_wup'] = None
        try: c.at[i, 'v2_wup'] = v_semantico(c.at[i, 'syns2'], bow, medida='wup', ic='', info=info)
        except:  c.at[i, 'v2_wup'] = None
        try: c.at[i, 'puntuacion_lw_wup'] = similitud_frase_lw(c.at[i, 'v1_wup'], c.at[i, 'v2_wup'] )
        except:  c.at[i, 'puntuacion_lw_wup'] = None

        if print_info == 's':
            print('v1_wup', i, ': ', c.at[i, 'v1_wup'])
            print('v2_wup', i, ': ', c.at[i, 'v2_wup'])
            print('puntuacion_lw_wup', i, ': ', c.at[i, 'puntuacion_lw_wup'])

        ic = ic_brown

        try: c.at[i, 'v1_res_brown'] = v_semantico(c.at[i, 'syns1'], bow, medida='res', ic=ic_brown, info=info)
        except:  c.at[i, 'v1_res_brown'] = None
        try: c.at[i, 'v2_res_brown'] = v_semantico(c.at[i, 'syns2'], bow, medida='res', ic=ic_brown, info=info)
        except:  c.at[i, 'v2_res_brown'] = None
        try: c.at[i, 'puntuacion_lw_res_brown'] = similitud_frase_lw(c.at[i, 'v1_res_brown'], c.at[i, 'v2_res_brown'] )
        except:  c.at[i, 'puntuacion_lw_res_brown'] = None

        if print_info == 's':
            print('v1_res_brown', i, ': ', c.at[i, 'v1_res_brown'])
            print('v2_res_brown', i, ': ', c.at[i, 'v2_res_brown'])
            print('puntuacion_lw_res_brown', i, ': ', c.at[i, 'puntuacion_lw_res_brown'])      

        try: c.at[i, 'v1_jcn_brown'] = v_semantico(c.at[i, 'syns1'], bow, medida='jcn', ic=ic_brown, info=info)
        except:  c.at[i, 'v1_jcn_brown'] = None
        try: c.at[i, 'v2_jcn_brown'] = v_semantico(c.at[i, 'syns2'], bow, medida='jcn', ic=ic_brown, info=info)
        except:  c.at[i, 'v2_jcn_brown'] = None
        try: c.at[i, 'puntuacion_lw_jcn_brown'] = similitud_frase_lw(c.at[i, 'v1_jcn_brown'], c.at[i, 'v2_jcn_brown'] )
        except:  c.at[i, 'puntuacion_lw_jcn_brown'] = None

        if print_info == 's':
            print('v1_jcn_brown', i, ': ', c.at[i, 'v1_jcn_brown'])
            print('v2_jcn_brown', i, ': ', c.at[i, 'v2_jcn_brown'])
            print('puntuacion_lw_jcn_brown', i, ': ', c.at[i, 'puntuacion_lw_jcn_brown'])

        try: c.at[i, 'v1_lin_brown'] = v_semantico(c.at[i, 'syns1'], bow, medida='lin', ic=ic_brown, info=info)
        except:  c.at[i, 'v1_lin_brown'] = None
        try: c.at[i, 'v2_lin_brown'] = v_semantico(c.at[i, 'syns2'], bow, medida='lin', ic=ic_brown, info=info)
        except:  c.at[i, 'v2_lin_brown'] = None
        try: c.at[i, 'puntuacion_lw_lin_brown'] = similitud_frase_lw(c.at[i, 'v1_lin_brown'], c.at[i, 'v2_lin_brown'] )
        except:  c.at[i, 'puntuacion_lw_lin_brown'] = None

        if print_info == 's':
            print('v1_lin_brown', i, ': ', c.at[i, 'v1_lin_brown'])
            print('v2_lin_brown', i, ': ', c.at[i, 'v2_lin_brown'])
            print('puntuacion_lw_lin_brown', i, ': ', c.at[i, 'puntuacion_lw_lin_brown'])

        ic = ic_semcor

        try: c.at[i, 'v1_res_semcor'] = v_semantico(c.at[i, 'syns1'], bow, medida='res', ic=ic_semcor, info=info)
        except:  c.at[i, 'v1_res_semcor'] = None
        try: c.at[i, 'v2_res_semcor'] = v_semantico(c.at[i, 'syns2'], bow, medida='res', ic=ic_semcor, info=info)
        except:  c.at[i, 'v2_res_semcor'] = None
        try: c.at[i, 'puntuacion_lw_res_semcor'] = similitud_frase_lw(c.at[i, 'v1_res_semcor'], c.at[i, 'v2_res_semcor'])
        except:  c.at[i, 'puntuacion_lw_res_semcor'] = None

        if print_info == 's':
            print('v1_res_semcor', i, ': ', c.at[i, 'v1_res_semcor'])
            print('v2_res_semcor', i, ': ', c.at[i, 'v2_res_semcor'])
            print('puntuacion_lw_res_semcor', i, ': ', c.at[i, 'puntuacion_lw_res_semcor'])

        try: c.at[i, 'v1_jcn_semcor'] = v_semantico(c.at[i, 'syns1'], bow, medida='jcn', ic=ic_semcor, info=info)
        except:  c.at[i, 'v1_jcn_semcor'] = None
        try: c.at[i, 'v2_jcn_semcor'] = v_semantico(c.at[i, 'syns2'], bow, medida='jcn', ic=ic_semcor, info=info)
        except:  c.at[i, 'v2_jcn_semcor'] = None
        try: c.at[i, 'puntuacion_lw_jcn_semcor'] = similitud_frase_lw(c.at[i, 'v1_jcn_semcor'], c.at[i, 'v2_jcn_semcor'] )
        except:  c.at[i, 'puntuacion_lw_jcn_semcor'] = None

        if print_info == 's':
            print('v1_jcn_semcor', i, ': ', c.at[i, 'v1_jcn_semcor'])
            print('v2_jcn_semcor', i, ': ', c.at[i, 'v2_jcn_semcor'])
            print('puntuacion_lw_jcn_semcor', i, ': ', c.at[i, 'puntuacion_lw_jcn_semcor'])

        try: c.at[i, 'v1_lin_semcor'] = v_semantico(c.at[i, 'syns1'], bow, medida='lin', ic=ic_semcor, info=info)
        except:  c.at[i, 'v1_lin_semcor'] = None
        try: c.at[i, 'v2_lin_semcor'] = v_semantico(c.at[i, 'syns2'], bow, medida='lin', ic=ic_semcor, info=info)
        except:  c.at[i, 'v2_lin_semcor'] = None
        try: c.at[i, 'puntuacion_lw_lin_semcor'] = similitud_frase_lw(c.at[i, 'v1_lin_semcor'], c.at[i, 'v2_lin_semcor'] )
        except:  c.at[i, 'puntuacion_lw_lin_semcor'] = None

        if print_info == 's':
            print('v1_lin_semcor', i, ': ', c.at[i, 'v1_lin_semcor'])
            print('v2_lin_semcor', i, ': ', c.at[i, 'v2_lin_semcor'])
            print('puntuacion_lw_lin_semcor', i, ': ', c.at[i, 'puntuacion_lw_lin_semcor'])

        ic = ic_genesis

        try: c.at[i, 'v1_res_genesis'] = v_semantico(c.at[i, 'syns1'], bow, medida='res', ic=ic_genesis, info=info)
        except:  c.at[i, 'v1_res_genesis'] = None
        try: c.at[i, 'v2_res_genesis'] = v_semantico(c.at[i, 'syns2'], bow, medida='res', ic=ic_genesis, info=info)
        except:  c.at[i, 'v2_res_genesis'] = None
        try: c.at[i, 'puntuacion_lw_res_genesis'] = similitud_frase_lw(c.at[i, 'v1_res_genesis'], c.at[i, 'v2_res_genesis'] )
        except:  c.at[i, 'puntuacion_lw_res_genesis'] = None

        if print_info == 's':
            print('v1_res_genesis', i, ': ', c.at[i, 'v1_res_genesis'])
            print('v2_res_genesis', i, ': ', c.at[i, 'v2_res_genesis'])
            print('puntuacion_lw_res_genesis', i, ': ', c.at[i, 'puntuacion_lw_res_genesis'])

        try: c.at[i, 'v1_jcn_genesis'] = v_semantico(c.at[i, 'syns1'], bow, medida='jcn', ic=ic_genesis, info=info)
        except:  c.at[i, 'v1_jcn_genesis'] = None
        try: c.at[i, 'v2_jcn_genesis'] = v_semantico(c.at[i, 'syns2'], bow, medida='jcn', ic=ic_genesis, info=info)
        except:  c.at[i, 'v2_jcn_genesis'] = None
        try: c.at[i, 'puntuacion_lw_jcn_genesis'] = similitud_frase_lw(c.at[i, 'v1_jcn_genesis'], c.at[i, 'v2_jcn_genesis'] )
        except:  c.at[i, 'puntuacion_lw_jcn_genesis'] = None

        if print_info == 's':
            print('v1_jcn_genesis', i, ': ', c.at[i, 'v1_jcn_genesis'])
            print('v2_jcn_genesis', i, ': ', c.at[i, 'v2_jcn_genesis'])
            print('puntuacion_lw_jcn_genesis', i, ': ', c.at[i, 'puntuacion_lw_jcn_genesis'])

        try: c.at[i, 'v1_lin_genesis'] = v_semantico(c.at[i, 'syns1'], bow, medida='lin', ic=ic_genesis, info=info)
        except:  c.at[i, 'v1_lin_genesis'] = None
        try: c.at[i, 'v2_lin_genesis'] = v_semantico(c.at[i, 'syns2'], bow, medida='lin', ic=ic_genesis, info=info)
        except:  c.at[i, 'v2_lin_genesis'] = None
        try: c.at[i, 'puntuacion_lw_lin_genesis'] = similitud_frase_lw(c.at[i, 'v1_lin_genesis'], c.at[i, 'v2_lin_genesis'] )
        except:  c.at[i, 'puntuacion_lw_lin_genesis'] = None

        if print_info == 's':
            print('v1_lin_genesis', i, ': ', c.at[i, 'v1_lin_genesis'])
            print('v2_lin_genesis', i, ': ', c.at[i, 'v2_lin_genesis'])
            print('puntuacion_lw_lin_genesis', i, ': ', c.at[i, 'puntuacion_lw_lin_genesis'])    

        end = time.time()
        print(end-start)


    end_total = time.time()
    print('TIEMPO TRANSCURRIDO:', end_total-start_total)

0.02132725715637207
0.005952119827270508
0.013887882232666016
0.005455970764160156
0.006944417953491211
0.003968000411987305
0.005951404571533203
0.013392210006713867
0.021327495574951172
0.012896299362182617
0.01884770393371582
0.017360448837280273
0.008927345275878906
0.012896060943603516
0.010912895202636719
0.007935047149658203
0.005455970764160156
0.001984119415283203
0.008432865142822266
0.00942373275756836
0.009422540664672852
0.0069310665130615234
0.005456209182739258
0.0029752254486083984
0.004961252212524414
0.006446361541748047
0.003968000411987305
0.005953073501586914
0.012431144714355469
0.008896350860595703
0.009424448013305664
0.0044629573822021484
0.004462480545043945
0.00745844841003418
0.015346050262451172
0.005454063415527344
0.005456209182739258
0.008432149887084961
0.006945610046386719
0.004462242126464844
0.0024797916412353516
0.003968000411987305
0.011904001235961914
0.005953073501586914
0.009918928146362305
0.00793600082397461
0.0077762603759765625
0.007468223571777344
0.00790548324584961
0.007958650588989258
0.007409334182739258
0.011407613754272461
0.004462480545043945
0.01041555404663086
0.011407136917114258
0.007936239242553711
0.003506898880004883
0.008431196212768555
0.0034704208374023438
0.010448217391967773
0.0069675445556640625
0.01587080955505371
0.01686406135559082
0.00843191146850586
0.00592803955078125
0.011408090591430664
0.012897014617919922
0.0034720897674560547
0.00896000862121582
0.008894681930541992
0.010416030883789062
0.006445646286010742
0.005952119827270508
0.008958816528320312
0.013858795166015625
0.006477832794189453
0.0039670467376708984
0.005951642990112305
0.006447553634643555
0.005486011505126953
0.012898683547973633
0.0054531097412109375
0.005455970764160156
0.005951404571533203
0.007936477661132812
0.0029773712158203125
0.005479574203491211
0.007437229156494141
0.014393329620361328
0.01139378547668457
0.005454063415527344
0.007934331893920898
0.003470897674560547
0.002973318099975586
0.005952119827270508
0.007471561431884766
0.013364315032958984
0.007945537567138672
0.010877609252929688
0.006448507308959961
0.0049893856048583984
0.011871576309204102
0.0049593448638916016
0.005456209182739258
0.003999233245849609
0.010415792465209961
0.008402109146118164
0.00743865966796875
0.005982398986816406
0.004960060119628906
0.005424976348876953
0.007441282272338867
0.004460573196411133
0.006445407867431641
0.005982875823974609
0.010387182235717773
0.006447553634643555
0.009426593780517578
0.01094198226928711
0.003968000411987305
0.005951881408691406
0.007964849472045898
0.0049283504486083984
0.0074384212493896484
0.005456209182739258
0.008428812026977539
0.010416269302368164
0.015372991561889648
0.006447315216064453
0.006479740142822266
0.008401870727539062
0.02380657196044922
0.005455493927001953
0.0029764175415039062
0.004960060119628906
0.0014879703521728516
0.008959770202636719
0.012894153594970703
0.012895584106445312
0.009424209594726562
0.0074405670166015625
0.007437944412231445
0.009920358657836914
0.007439851760864258
0.003471851348876953
0.0064470767974853516
0.011904716491699219
0.008929014205932617
0.005950212478637695
0.010912895202636719
0.0049591064453125
0.01735973358154297
0.01587200164794922
0.004959583282470703
0.008926630020141602
0.015906333923339844
0.006914854049682617
0.0014879703521728516
0.007965326309204102
0.0029714107513427734
0.00892782211303711
0.007934331893920898
0.01687169075012207
0.007440328598022461
0.006943702697753906
0.006417989730834961
0.0074384212493896484
0.013371944427490234
0.008433103561401367
0.010910987854003906
0.007970094680786133
0.004961967468261719
0.002477407455444336
0.007465362548828125
0.008428812026977539
0.0034475326538085938
0.00446319580078125
0.002479076385498047
0.0044934749603271484
0.0039675235748291016
0.006448268890380859
0.012402057647705078
0.005919456481933594
0.003494739532470703
0.007938861846923828
0.00793313980102539
0.016867399215698242
0.013363838195800781
0.010450363159179688
0.008427858352661133
0.00839996337890625
0.006943702697753906
0.0044901371002197266
0.005446672439575195
0.00400233268737793
0.009886741638183594
0.0034723281860351562
0.013422012329101562
0.006455421447753906
0.005947589874267578
0.003968000411987305
0.003961086273193359
0.008928775787353516
0.004439353942871094
0.0074694156646728516
0.006439924240112305
0.017836570739746094
0.007438182830810547
0.0074388980865478516
0.00892782211303711
0.008432149887084961
0.0054569244384765625
0.013886690139770508
0.004960060119628906
0.01686263084411621
0.013889789581298828
0.0044934749603271484
0.005952358245849609
0.005951404571533203
0.006418704986572266
0.004988908767700195
0.006450176239013672
0.005454063415527344
0.0014879703521728516
0.010413169860839844
0.0034704208374023438
0.0024809837341308594
0.007938146591186523
0.004462480545043945
0.0044634342193603516
0.008432149887084961
0.007440328598022461
0.005983591079711914
0.004916667938232422
0.010914802551269531
0.003472566604614258
0.007433652877807617
0.007415771484375
0.012895345687866211
0.012896060943603516
0.005456447601318359
0.011408805847167969
0.00942373275756836
0.005949974060058594
0.00548553466796875
0.008463382720947266
0.004957437515258789
0.007440805435180664
0.00945281982421875
0.005453824996948242
0.00842905044555664
0.0103912353515625
0.004492998123168945
0.004959583282470703
0.011407613754272461
0.011902570724487305
0.0064432621002197266
0.0049364566802978516
0.007969856262207031
0.0019834041595458984
0.01041412353515625
0.010415792465209961
0.006937265396118164
0.01239919662475586
0.01190495491027832
0.011405467987060547
0.009424448013305664
0.008432626724243164
0.00896000862121582
0.003967761993408203
0.008400201797485352
0.011408090591430664
0.013887643814086914
0.008430957794189453
0.007439851760864258
0.005456447601318359
0.00895833969116211
0.008925676345825195
0.012898921966552734
0.013857841491699219
0.011407613754272461
0.006942272186279297
0.011903047561645508
0.014912128448486328
0.002945423126220703
0.005949735641479492
0.005486726760864258
0.0034685134887695312
0.008959770202636719
0.0278017520904541
0.0034716129302978516
0.008425235748291016
0.007945060729980469
0.006966829299926758
0.0034728050231933594
0.004961490631103516
0.006946563720703125
0.012894630432128906
0.001982450485229492
0.006945133209228516
0.0069427490234375
0.01488184928894043
0.006916046142578125
0.006943225860595703
0.017857789993286133
0.01689600944519043
0.01732945442199707
0.004960298538208008
0.009947538375854492
0.005479335784912109
0.006448268890380859
0.009434938430786133
0.010876178741455078
0.0059506893157958984
0.006447792053222656
0.009423971176147461
0.01587057113647461
0.005952119827270508
0.003967761993408203
0.003473997116088867
0.005950450897216797
0.01636815071105957
0.015375614166259766
0.021825075149536133
0.009918689727783203
0.0014879703521728516
0.005455732345581055
0.013391256332397461
0.007934808731079102
0.0069427490234375
0.01239919662475586
0.007440328598022461
0.0059511661529541016
0.006479024887084961
0.0069429874420166016
0.004991769790649414
0.00892782211303711
0.01289677619934082
0.003968000411987305
0.006943225860595703
0.003473520278930664
0.009422779083251953
0.005920886993408203
0.017360210418701172
0.020814895629882812
0.01634383201599121
0.01984119415283203
0.007439851760864258
0.010912418365478516
0.004462480545043945
0.008432626724243164
0.011904716491699219
0.010414600372314453
0.007967948913574219
0.02031874656677246
0.017361164093017578
0.009424448013305664
0.008430957794189453
0.010414600372314453
0.00843191146850586
0.005951881408691406
0.006943941116333008
0.017856121063232422
0.006943702697753906
0.00644683837890625
0.008928060531616211
0.026818037033081055
0.010415315628051758
0.0029692649841308594
0.007436513900756836
0.012374401092529297
0.011902570724487305
0.006479501724243164
0.009917736053466797
0.002478361129760742
0.015375137329101562
0.004960536956787109
0.008929729461669922
0.0059506893157958984
0.007439851760864258
0.006447792053222656
0.009425878524780273
0.014384269714355469
0.012398719787597656
0.02033686637878418
0.0059506893157958984
0.007675647735595703
0.008431196212768555
0.006922483444213867
0.003493785858154297
0.006447315216064453
0.010410308837890625
0.008432865142822266
0.008433103561401367
0.008925676345825195
0.014416933059692383

0.011376380920410156
0.007440328598022461
0.012430191040039062
0.011377334594726562
0.01044607162475586
0.013856649398803711
0.014417648315429688
0.009424209594726562
0.005454540252685547
0.01292729377746582
0.019515037536621094
0.007437705993652344
0.008432865142822266
0.011406898498535156
0.01292562484741211
0.011374473571777344
0.028270483016967773
0.013889551162719727
0.01788640022277832
0.006453275680541992
0.009241819381713867
0.009528160095214844
0.009917497634887695
0.013393402099609375
0.013390302658081055
0.005455970764160156
0.008962392807006836
0.00492548942565918
0.008432149887084961
0.010912179946899414
0.011408329010009766
0.006942033767700195
0.014386177062988281
0.012399911880493164
0.007440328598022461
0.010417699813842773
0.013886451721191406
0.014877796173095703
0.014885902404785156
0.012898445129394531
0.008430719375610352
0.012926101684570312
0.014899015426635742
0.009920358657836914
0.008435249328613281
0.007436513900756836
0.00796365737915039
0.005976438522338867
0.014356136322021484
0.01488041877746582
0.011902570724487305
0.008928060531616211
0.004462003707885742
0.027312040328979492
0.015841960906982422
0.01934337615966797
0.012894153594970703
0.006978750228881836
0.0044634342193603516
0.01041555404663086
0.009915828704833984
0.008928775787353516
0.00942683219909668
0.01090240478515625
0.008930206298828125
0.005430698394775391
0.005483865737915039
0.005967855453491211
0.00595402717590332
0.006446123123168945
0.007938861846923828
0.015871286392211914
0.01587200164794922
0.0069429874420166016
0.005457162857055664
0.011437177658081055
0.01088261604309082
0.010942459106445312
0.010445833206176758
0.00893092155456543
0.01189422607421875
0.003448009490966797
0.014383077621459961
0.006966590881347656
0.006456851959228516
0.0069353580474853516
0.012896060943603516
0.015379667282104492
0.01639842987060547
0.005951642990112305
0.008435487747192383
0.008918523788452148
0.00548243522644043
0.014358758926391602
0.006971120834350586
0.012372493743896484
0.007967472076416016
0.009917736053466797
0.005952119827270508
0.004433155059814453
0.006945371627807617
0.0029764175415039062
0.00793600082397461
0.006973743438720703
0.003970146179199219
0.014377832412719727
0.005930423736572266
0.013917684555053711
0.007441997528076172
0.010448455810546875
0.008463859558105469
0.00939321517944336
0.004495143890380859
0.003960132598876953
0.007936716079711914
0.008456707000732422
0.009398460388183594
0.008435487747192383
0.003931522369384766
0.006943941116333008
0.013885498046875
0.007969379425048828
0.005982637405395508
0.005951642990112305
0.003471851348876953
0.0065920352935791016
0.009423971176147461
0.005952119827270508
0.005951881408691406
0.005455493927001953
0.006448268890380859
0.003968000411987305
0.005951881408691406
0.0029761791229248047
0.0034716129302978516
0.0044629573822021484
0.006901741027832031
0.006447792053222656
0.004959821701049805
0.005486965179443359
0.0029604434967041016
0.005976676940917969
0.005952119827270508
0.004959583282470703
0.005455732345581055
0.006918907165527344
0.007441043853759766
0.014384746551513672
0.0069425106048583984
0.008931159973144531
0.014877557754516602
0.008957386016845703
0.005457401275634766
0.0064470767974853516
0.005457639694213867
0.0069427490234375
0.005951404571533203
0.00945425033569336
0.011934041976928711
0.008431434631347656
0.008463859558105469
0.0039348602294921875
0.01441502571105957
0.004960298538208008
0.006448030471801758
0.006936550140380859
0.004961252212524414
0.004439353942871094
0.0049593448638916016
0.015871286392211914
0.01835036277770996
0.01835322380065918
0.005454301834106445
0.008439779281616211
0.007439613342285156
0.0034418106079101562
0.0034711360931396484
0.00446319580078125
0.003968000411987305
0.018351078033447266
0.005455732345581055
0.005952119827270508
0.006446361541748047
0.0014882087707519531
0.013391733169555664
0.004958629608154297
0.008432149887084961
0.007968425750732422
0.006470680236816406
0.007936716079711914
0.00399470329284668
0.01088094711303711
0.009921073913574219
0.00991964340209961
0.0024788379669189453
0.005455493927001953
0.001983642578125
0.017359018325805664
0.00793600082397461
0.00446319580078125
0.003968000411987305
0.008432865142822266
0.008431434631347656
0.0049593448638916016
0.0069425106048583984
0.005455732345581055
0.006445884704589844
0.00545501708984375
0.004462242126464844
0.012895345687866211
0.008462905883789062
0.021332263946533203
0.0074079036712646484
0.004464149475097656
0.006946086883544922
0.007934331893920898
0.007936477661132812
0.00397181510925293
0.007935047149658203
0.014415264129638672
0.010416269302368164
0.004457712173461914
0.0039670467376708984
0.006922245025634766
0.005982398986816406
0.0029754638671875
0.0034418106079101562
0.003967761993408203
0.006477832794189453
0.004954099655151367
0.003943443298339844
0.005952119827270508
0.006978750228881836
0.001979827880859375
0.01040959358215332
0.010416269302368164
0.005451679229736328
0.00647735595703125
0.0059435367584228516
0.0024988651275634766
0.007947683334350586
0.004952907562255859
0.009894847869873047
0.013392925262451172
0.007438182830810547
0.01193857192993164
0.015842199325561523
0.00644993782043457
0.005951881408691406
0.006944179534912109
0.005454301834106445
0.007471799850463867
0.0035021305084228516
0.009911298751831055
0.009429931640625
0.010942697525024414
0.009919881820678711
0.005952596664428711
0.004950284957885742
0.007938385009765625
0.007940292358398438
0.009416580200195312
0.009923219680786133
0.0064487457275390625
0.02033686637878418
0.010911226272583008
0.021358728408813477
0.008937358856201172
0.008926630020141602
0.0059511661529541016
0.005456209182739258
0.007936716079711914
0.00400233268737793
0.006440401077270508
0.012403488159179688
0.007930994033813477
0.005453824996948242
0.006944179534912109
0.0049359798431396484
0.012398719787597656
0.007935523986816406
0.0044634342193603516
0.010416507720947266
0.012396097183227539
0.02780771255493164
0.009887933731079102
0.004462480545043945
0.011903524398803711
0.012895584106445312
0.004985809326171875
0.0024805068969726562
0.0069429874420166016
0.01187276840209961
0.007440805435180664
0.0054852962493896484
0.009914398193359375
0.008423805236816406
0.011412858963012695
0.00941920280456543
0.005455732345581055
0.008436918258666992
0.004935741424560547
0.008462667465209961
0.006418704986572266
0.01884937286376953
0.00795745849609375
0.007441520690917969
0.012398004531860352
0.004462242126464844
0.018351078033447266
0.004462718963623047
0.010943412780761719
0.011902809143066406
0.005942821502685547
0.009428977966308594
0.008925914764404297
0.00944828987121582
0.0034477710723876953
0.0049915313720703125
0.009392261505126953
0.009459495544433594
0.004923582077026367
0.005486011505126953
0.01934337615966797
0.02877020835876465
0.005921602249145508
0.01438283920288086
0.005455970764160156
0.009950399398803711
0.0044634342193603516
0.012865066528320312
0.007470130920410156
0.005424976348876953
0.00746917724609375
0.003968238830566406
0.0034644603729248047
0.025304317474365234
0.003935575485229492
0.008460521697998047
0.006419181823730469
0.012430667877197266
0.009423494338989258
0.018352270126342773
0.0064198970794677734
0.010910987854003906
0.0069446563720703125
0.01587057113647461
0.004464864730834961
0.008429765701293945
0.006945133209228516
0.004957914352416992
0.007936477661132812
0.0089263916015625
0.006943941116333008
0.007439851760864258
0.007440090179443359
0.011904001235961914
0.010911941528320312
0.007961511611938477
0.008891820907592773
0.004464864730834961
0.004959583282470703
0.01140594482421875
0.007441520690917969
0.008432388305664062
0.013905048370361328
0.01289677619934082
0.020335912704467773
0.009423255920410156
0.005951642990112305
0.015871047973632812
0.013889074325561523
0.007936239242553711
0.010415315628051758
0.008433103561401367
0.009422063827514648
0.009425640106201172
0.00396728515625
0.011408329010009766
0.00396728515625
0.007440805435180664
0.0089263916015625
0.003968238830566406
0.009423971176147461
0.030253887176513672
0.009918689727783203
0.007941484451293945
0.009920358657836914
0.0069429874420166016
0.004991054534912109
0.011407852172851562
0.010416746139526367
0.011897087097167969
0.007935762405395508
0.006922245025634766
0.011437416076660156
0.004433870315551758
0.007960319519042969
0.006958723068237305
0.0074160099029541016
0.011934041976928711
0.00942373275756836

0.005425691604614258
0.015401601791381836
0.023345232009887695
0.010877609252929688
0.007445573806762695
0.008432865142822266
0.007439613342285156
0.011407852172851562
0.012894630432128906
0.012927532196044922
0.011904001235961914
0.007439851760864258
0.0034706592559814453
0.0064465999603271484
0.007443666458129883
0.007930517196655273
0.00793600082397461
0.005463361740112305
0.01139974594116211
0.011879205703735352
0.020334720611572266
0.009424209594726562
0.01091146469116211
0.009920597076416016
0.009918212890625
0.007439136505126953
0.008432149887084961
0.01636791229248047
0.028272390365600586
0.024303674697875977
0.0064487457275390625
0.013887405395507812
0.005455493927001953
0.003645658493041992
0.008431196212768555
0.020114421844482422
0.008429527282714844
0.01931452751159668
0.00647735595703125
0.006419181823730469
0.04166579246520996
0.0054547786712646484
0.006449222564697266
0.0054547786712646484
0.007440328598022461
0.005455732345581055
0.005456209182739258
0.0059833526611328125
0.006943702697753906
0.010482072830200195
0.008967161178588867
0.011904001235961914
0.01785588264465332
0.01686382293701172
0.04712104797363281
0.021326303482055664
0.005487203598022461
0.012866497039794922
0.0029752254486083984
0.00747227668762207
0.01140737533569336
0.00992131233215332
0.004434347152709961
0.00945281982421875
0.008928775787353516
0.010880470275878906
0.005952358245849609
0.021329641342163086
0.007474422454833984
0.006909370422363281
0.01884627342224121
0.006448507308959961
0.015872716903686523
0.00396275520324707
0.013392210006713867
0.01587224006652832
0.00945281982421875
0.008403301239013672
0.01388859748840332
0.014878988265991211
0.010415792465209961
0.0074727535247802734
0.004468202590942383
0.006446123123168945
0.00892782211303711
0.006448268890380859
0.015903472900390625
0.006448268890380859
0.0054242610931396484
0.010911703109741211
0.008956193923950195

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: RuntimeWarning: invalid value encountered in double_scalars
  if __name__ == '__main__':

0.027776718139648438
0.02132701873779297
0.023809432983398438
0.013362884521484375
0.0035016536712646484
0.005426168441772461
0.006446123123168945
0.015375852584838867
0.00794529914855957
0.0128936767578125
0.005920886993408203
0.008430719375610352
0.011407852172851562
0.008936166763305664
0.007952451705932617
0.007773637771606445
0.007966995239257812
0.0074100494384765625
0.010441303253173828
0.0163726806640625
0.015840530395507812
0.005455732345581055
0.008961200714111328
0.009498357772827148
0.0053751468658447266
0.010414838790893555
0.008930206298828125
0.00893092155456543
0.01336216926574707
0.012918472290039062
0.006474018096923828
0.011912822723388672
0.005918264389038086
0.009423494338989258
0.028798818588256836
0.005490303039550781
0.010877847671508789
0.018383026123046875
0.014847993850708008
0.008956193923950195
0.008403301239013672
0.001984119415283203
0.025824308395385742
0.005951642990112305
0.004929542541503906
0.010440826416015625
0.01039886474609375
0.017854928970336914
0.032735347747802734
0.005454063415527344
0.007436990737915039
0.010911226272583008
0.014880895614624023
0.011438846588134766
0.01038813591003418
0.020832538604736328
0.02234959602355957
0.010384798049926758
0.014911174774169922
0.03022623062133789
0.026815414428710938
0.011901617050170898
0.009394168853759766
0.009920597076416016
0.011406183242797852
0.010416269302368164
0.011408567428588867
0.023343801498413086
0.015872716903686523
0.011896133422851562
0.011905431747436523
0.02130413055419922
0.013390779495239258
0.027806997299194336
0.006447553634643555
0.004433393478393555
0.03276658058166504
0.017823457717895508
0.00644683837890625
0.013423681259155273
0.017362356185913086
0.008922338485717773
0.00843358039855957
0.010884523391723633
0.00843191146850586
0.0044596195220947266
0.008432149887084961
0.011904001235961914
0.015903949737548828
0.010001659393310547
0.009920120239257812
0.012463569641113281
0.007935762405395508
0.013423919677734375
0.014384746551513672
0.011377573013305664
0.018352508544921875
0.007438182830810547
0.005455732345581055
0.009920120239257812
0.005982637405395508
0.008968114852905273
0.008928298950195312
0.003968000411987305
0.009920358657836914
0.010416030883789062
0.009920120239257812
0.009426593780517578
0.010447263717651367
0.006561279296875
0.008896589279174805
0.005455732345581055
0.00846409797668457
0.009917020797729492
0.005952358245849609
0.014879941940307617
0.020305633544921875
0.005454540252685547
0.00497126579284668
0.003961086273193359
0.0044956207275390625
0.019311189651489258
0.015903949737548828
0.021327733993530273
0.011904716491699219
0.003965854644775391
0.007440328598022461
0.020367860794067383
0.003490447998046875
0.007405757904052734
0.01640033721923828
0.013918161392211914
0.010419845581054688
0.008899450302124023
0.015377521514892578
0.011408329010009766
0.009917736053466797
0.01785588264465332
0.011935710906982422
0.00793600082397461
0.006448268890380859
0.010912179946899414
0.004959821701049805
0.009425640106201172
0.019381999969482422
0.008392572402954102
0.01738882064819336
0.0064160823822021484
0.01245260238647461
0.013393640518188477
0.022350788116455078
0.031713008880615234
0.01884627342224121
0.02480006217956543
0.016399860382080078
0.011376142501831055
0.00892782211303711
0.030752182006835938
0.011904716491699219
0.016366958618164062
0.004959821701049805
0.005951881408691406
0.01686382293701172
0.016367673873901367
0.027775287628173828
0.003473043441772461
0.014382600784301758
0.022815227508544922
0.027280330657958984
0.007436513900756836
0.007935762405395508
0.011903762817382812
0.006478548049926758
0.005953550338745117
0.010910749435424805
0.007935523986816406
0.016864538192749023
0.029233694076538086
0.022353172302246094
0.005945682525634766
0.029288053512573242
0.014879941940307617
0.006440639495849609
0.019343852996826172
0.01138448715209961
0.01639866828918457
0.013361692428588867
0.016368389129638672
0.005951404571533203
0.00743865966796875
0.00496220588684082
0.021328210830688477
0.007937908172607422
0.007440328598022461
0.016863346099853516
0.008431196212768555
0.006943464279174805
0.017359018325805664
0.028303146362304688
0.012369394302368164
0.015376806259155273
0.008960485458374023
0.012994766235351562
0.014846086502075195
0.003471851348876953
0.009920120239257812
0.007935523986816406
0.005455493927001953
0.024828672409057617
0.014861345291137695
0.03571176528930664
0.009422540664672852
0.005951642990112305
0.004464149475097656
0.012896060943603516
0.009920358657836914
0.016863584518432617
0.025295734405517578
0.024803638458251953
0.00942373275756836
0.01735997200012207
0.01686239242553711
0.0034737586975097656
0.010413885116577148
0.006944417953491211
0.01091146469116211
0.010912179946899414
0.017887592315673828
0.010910272598266602
0.013885974884033203
0.00843191146850586
0.005456209182739258
0.0034720897674560547
0.010415792465209961
0.007967710494995117
0.019342422485351562
0.018847227096557617
0.02628803253173828
0.008430242538452148
0.006447792053222656
0.016864299774169922
0.013887882232666016
0.004464626312255859
0.004960298538208008
0.006943225860595703
0.008432626724243164
0.031743526458740234
0.01686382293701172
0.015871286392211914
0.015376091003417969
0.020336627960205078
0.010415315628051758
0.00942373275756836
0.017360210418701172
0.012894868850708008
0.005454301834106445
0.0039670467376708984
0.01240229606628418
0.022345781326293945
0.010386466979980469
0.007934093475341797
0.006448030471801758
0.02777576446533203
0.01488041877746582
0.030751466751098633
0.00644683837890625
0.0064487457275390625
0.008927345275878906
0.008432149887084961
0.01835155487060547
0.01438450813293457
0.015375375747680664
0.0079345703125
0.007935047149658203
0.042191505432128906
0.008429765701293945
0.016382217407226562
0.009389638900756836
0.009425640106201172
0.006946086883544922
0.01884913444519043
0.007934093475341797
0.01739192008972168
0.01837921142578125
0.023810625076293945
0.008401632308959961
0.0029764175415039062
0.010415792465209961
0.007439374923706055
0.009919881820678711
0.007966756820678711
0.011408090591430664
0.008425235748291016
0.006943702697753906
0.013862848281860352
0.008432626724243164
0.007936477661132812
0.014385700225830078
0.019839048385620117
0.008430004119873047
0.018878936767578125
0.020336627960205078
0.03320145606994629
0.052110910415649414
0.013888359069824219
0.014385461807250977
0.007934093475341797
0.011904001235961914
0.0054874420166015625
0.00793004035949707
0.009423255920410156
0.006448268890380859
0.012400388717651367
0.005949497222900391
0.011406898498535156
0.012403726577758789
0.00941610336303711
0.013864517211914062
0.02135777473449707
0.010416984558105469
0.010912179946899414
0.013390302658081055
0.01884937286376953
0.02232074737548828
0.011438369750976562
0.0065534114837646484
0.009951353073120117
0.012895822525024414
0.023807764053344727
0.008432149887084961
0.016865253448486328
0.019374847412109375
0.019809722900390625
0.0034699440002441406
0.015375852584838867
0.01934528350830078
0.03174400329589844
0.00846242904663086
0.028272151947021484
0.009942293167114258
0.021322965621948242
0.0049285888671875
0.022319555282592773
0.004958629608154297
0.013422489166259766
0.009921073913574219
0.008423089981079102
0.00939798355102539
0.015903711318969727
0.01141047477722168
0.011902332305908203
0.01339101791381836
0.005590915679931641
0.006337404251098633
0.007912158966064453
0.009455204010009766
0.012894153594970703
0.010410308837890625
0.006918907165527344
0.0049588680267333984
0.00545501708984375
0.01984119415283203
0.0451662540435791
0.00740814208984375
0.017360448837280273
0.006975889205932617
0.01190638542175293
0.01094365119934082
0.008959531784057617
0.008432626724243164
0.00991964340209961
0.01587200164794922
0.008931398391723633
0.028697490692138672
0.04860687255859375
0.009918928146362305
0.011407136917114258
0.01041412353515625
0.011407613754272461
0.029758691787719727
0.01587200164794922
0.016862869262695312
0.019344091415405273
0.03174471855163574
0.00991964340209961
0.004960298538208008
0.012895822525024414
0.016366958618164062
0.011407136917114258
0.010449409484863281
0.014847993850708008
0.02678394317626953
0.016863584518432617
0.003968000411987305
0.004464149475097656
0.012402534484863281

0.00793600082397461
0.01636791229248047
0.01242971420288086
0.027775287628173828
0.005953073501586914
0.005457162857055664
0.006937265396118164
0.020313024520874023
0.0074694156646728516
0.028768539428710938
0.008401155471801758
0.008464574813842773
0.008398771286010742
0.01739025115966797
0.013886690139770508
0.00942683219909668
0.01689291000366211
0.01537632942199707
0.008928537368774414
0.023808002471923828
0.009423494338989258
0.020336151123046875
0.006448268890380859
0.014383316040039062
0.005944490432739258
0.01687002182006836
0.006445884704589844
0.010911941528320312
0.004983425140380859
0.005952596664428711
0.023814916610717773
0.014848947525024414
0.008430242538452148
0.011409759521484375
0.02628469467163086
0.010414361953735352
0.007472515106201172
0.017358779907226562
0.008898735046386719
0.009450435638427734
0.004466533660888672
0.015373945236206055
0.01338958740234375
0.01190495491027832
0.010905981063842773
0.0163419246673584
0.005953788757324219
0.01391911506652832
0.012895822525024414
0.0253293514251709
0.005917549133300781
0.01094365119934082
0.00944972038269043
0.01931452751159668
0.009919166564941406
0.007470369338989258
0.01941680908203125
0.003966569900512695
0.01636791229248047
0.00793600082397461
0.010908126831054688
0.005952119827270508
0.010910511016845703
0.01041555404663086
0.030256271362304688
0.010415792465209961
0.010415792465209961
0.012400150299072266
0.010416269302368164
0.005952358245849609
0.004464387893676758
0.009425878524780273
0.002480030059814453
0.01339101791381836
0.01190638542175293
0.013918876647949219
0.00599217414855957
0.006946086883544922
0.012866735458374023
0.02978968620300293
0.011408090591430664
0.014880180358886719
0.007938385009765625
0.006943941116333008
0.0431513786315918
0.008404254913330078
0.008957624435424805
0.021824121475219727
0.011408090591430664
0.006448268890380859
0.010418891906738281
0.01636815071105957
0.014882802963256836
0.01041555404663086
0.04064035415649414
0.009422540664672852
0.011935234069824219
0.02976536750793457
0.06298661231994629
0.013392210006713867
0.025760412216186523
0.014879941940307617
0.008928537368774414
0.010415315628051758
0.017856121063232422
0.008432149887084961
0.025297880172729492
0.010910272598266602
0.016367673873901367
0.008928060531616211
0.008432149887084961
0.01636815071105957
0.014385461807250977
0.01735973358154297
0.006447553634643555
0.02827286720275879
0.010416984558105469
0.03372764587402344
0.006446361541748047
0.011408329010009766
0.014383792877197266
0.005951881408691406
0.02281641960144043
0.009920835494995117
0.00991964340209961
0.011902570724487305
0.013887882232666016
0.014879465103149414
0.01488041877746582
0.017856121063232422
0.006482362747192383
0.005457401275634766
0.011870861053466797
0.008928060531616211
0.009423494338989258
0.013888359069824219
0.006943941116333008
0.003471851348876953
0.005952358245849609
0.02678394317626953
0.004464149475097656
0.011407613754272461
0.017856121063232422
0.0049626827239990234
0.004958629608154297
0.019375085830688477
0.009920597076416016
0.0064165592193603516
0.00942540168762207
0.0079345703125
0.017360210418701172
0.011407852172851562
0.023312807083129883
0.00396728515625
0.004463911056518555
0.004463672637939453
0.009920358657836914
0.004960060119628906
0.006448030471801758
0.005950927734375
0.008928060531616211
0.008431196212768555
0.016367435455322266
0.028792142868041992
0.016337871551513672
0.023808002471923828
0.01636815071105957
0.021326065063476562
0.012894153594970703
0.017856121063232422
0.013889312744140625
0.005950212478637695
0.027808666229248047
0.016370773315429688
0.013884544372558594
0.03224968910217285
0.020303726196289062
0.01835179328918457
0.017391443252563477
0.016832828521728516
0.01587200164794922
0.002974271774291992
0.008432149887084961
0.00648045539855957
0.007439851760864258
0.007444858551025391
0.012402057647705078
0.027746200561523438
0.011934995651245117
0.01587200164794922
0.007798433303833008
0.011408090591430664
0.013360738754272461
0.02631998062133789
0.005464315414428711
0.0045659542083740234
0.011906862258911133
0.005949258804321289
0.004463911056518555
0.005953311920166016
0.013425827026367188
0.0044612884521484375
0.013857126235961914
0.013390302658081055
0.00793600082397461
0.006447792053222656
0.026288509368896484
0.03127884864807129
0.02926349639892578
0.02185368537902832
0.014383316040039062
0.004987478256225586
0.004464387893676758
0.01587224006652832
0.017856121063232422
0.005951642990112305
0.014413118362426758
0.03766608238220215
0.01239919662475586
0.008430719375610352
0.009918689727783203
0.005455493927001953
0.007439851760864258
0.010910749435424805
0.00942373275756836
0.03521561622619629
0.013391494750976562
0.01686239242553711
0.010911941528320312
0.013392210006713867
0.00892782211303711
0.010912179946899414
0.012398958206176758
0.02083277702331543
0.005951404571533203
0.02529430389404297
0.011935234069824219
0.02030777931213379
0.017349720001220703
0.009919404983520508
0.003471851348876953
0.023808002471923828
0.010912418365478516
0.0064470767974853516
0.006447792053222656
0.018847942352294922
0.08484911918640137
0.02033686637878418
0.004467010498046875
0.007901430130004883
0.011432409286499023
0.016834259033203125
0.011901617050170898
0.01686382293701172
0.006447792053222656
0.03471994400024414
0.009920120239257812
0.00793600082397461
0.02033543586730957
0.006975650787353516
0.03171706199645996
0.03971362113952637
0.020336151123046875
0.016862869262695312
0.010882139205932617
0.014382123947143555
0.018352270126342773
0.02628779411315918
0.036208152770996094
0.014880180358886719
0.010910987854003906
0.014383554458618164
0.012399673461914062
0.009919881820678711
0.007935762405395508
0.00793600082397461
0.013422489166259766
0.012894868850708008
0.02033686637878418
0.007439613342285156
0.03620791435241699
0.017391204833984375
0.03518342971801758
0.0039670467376708984
0.012398719787597656
0.003968238830566406
0.0049588680267333984
0.011320352554321289
0.008432865142822266
0.019838333129882812
0.015375614166259766
0.0039675235748291016
0.02529597282409668
0.01342010498046875
0.007443904876708984
0.007959127426147461
0.0059545040130615234
0.005450248718261719
0.005460977554321289
0.027781248092651367
0.01137685775756836
0.015405654907226562
0.012368917465209961
0.01140737533569336
0.006479501724243164
0.01587510108947754
0.009423017501831055
0.026258230209350586
0.013919830322265625
0.01091146469116211
0.00892186164855957
0.018848419189453125
0.02430438995361328
0.019375085830688477
0.005952119827270508
0.017858505249023438
0.02780437469482422
0.016369342803955078
0.012398004531860352
0.017885923385620117
0.008442401885986328
0.00843191146850586
0.009917974472045898
0.011907100677490234
0.01389002799987793
0.008927345275878906
0.0059473514556884766
0.003943443298339844
0.011434316635131836
0.022817373275756836
0.037198781967163086
0.01041412353515625
0.00995182991027832
0.006449699401855469
0.007968902587890625
0.02628803253173828
0.01190328598022461
0.012403488159179688
0.017389297485351562
0.00446009635925293
0.024801015853881836
0.02923417091369629
0.023311376571655273
0.003968477249145508
0.011407613754272461
0.018849611282348633
0.00995182991027832
0.00743865966796875
0.04563164710998535
0.005950450897216797
0.010912179946899414
0.017857789993286133
0.028271913528442383
0.006446123123168945
0.026320934295654297
0.026266813278198242
0.006973981857299805
0.007905721664428711
0.02086496353149414
0.018349885940551758
0.004988193511962891
0.008400440216064453
0.007994890213012695
0.010416030883789062
0.005983591079711914
0.032239675521850586
0.01732945442199707
0.01190495491027832
0.017359256744384766
0.021864891052246094
0.01587200164794922
0.014882326126098633
0.005453824996948242
0.004464149475097656
0.010913610458374023
0.007437467575073242
0.004464387893676758
0.009920120239257812
0.011897563934326172
0.006972312927246094
0.006947040557861328
0.006943225860595703
0.007940053939819336
0.013854742050170898
0.006447553634643555
0.007936477661132812
0.021856069564819336
0.00894308090209961
0.011901617050170898
0.01736164093017578
0.030750274658203125
0.015375614166259766
0.004960060119628906
0.02380824089050293
0.012930870056152344
0.01636219024658203
0.004958391189575195

0.05009746551513672
0.016863346099853516
0.02086162567138672
0.01735711097717285
0.03865981101989746
0.010910511016845703
0.010912179946899414
0.007440090179443359
0.003968000411987305
0.014415979385375977
0.008431196212768555
0.0054552555084228516
0.026753902435302734
0.024301767349243164
0.022847414016723633
0.0341944694519043
0.02480006217956543
0.01140594482421875
0.006479978561401367
0.003972768783569336
0.01984429359436035
0.012400388717651367
0.00790548324584961
0.015373706817626953
0.017394304275512695
0.015839338302612305
0.017854690551757812
0.009425640106201172
0.01838207244873047
0.0069692134857177734
0.0723869800567627
0.005453824996948242
0.006447792053222656
0.01835179328918457
0.010944366455078125
0.013387680053710938
0.01686406135559082
0.011376142501831055
0.00744318962097168
0.016865015029907227
0.012896060943603516
0.003965854644775391
0.00896000862121582
0.014882087707519531
0.01239776611328125
0.02135491371154785
0.014879703521728516
0.03273630142211914
0.027262449264526367
0.008462190628051758
0.019840002059936523
0.004431962966918945
0.008461475372314453
0.033202171325683594
0.010449886322021484
0.02380514144897461
0.013391494750976562
0.03273773193359375
0.003968238830566406
0.02377796173095703
0.007934331893920898
0.02380657196044922
0.0322415828704834
0.016367673873901367
0.011437177658081055
0.014881134033203125
0.013889551162719727
0.005950927734375
0.011421680450439453
0.018845558166503906
0.014879941940307617
0.03323101997375488
0.012398958206176758
0.012897014617919922
0.014377355575561523
0.012400150299072266
0.009400367736816406
0.023807287216186523
0.008922815322875977
0.010414361953735352
0.011407136917114258
0.004464864730834961
0.014879226684570312
0.003968715667724609
0.01637434959411621
0.012888431549072266
0.0456387996673584
0.015902042388916016
0.008926868438720703
0.005918979644775391
0.012400627136230469
0.028304100036621094
0.02476644515991211
0.009422063827514648
0.024337291717529297
0.030254602432250977
0.005979776382446289
0.010911941528320312
0.016883373260498047
0.009419918060302734
0.011383056640625
0.021854400634765625
0.006913900375366211
0.015406131744384766
0.01983809471130371
0.004960536956787109
0.017359018325805664
0.016370534896850586
0.009421586990356445
0.004488229751586914
0.047095537185668945
0.009422063827514648
0.00743865966796875
0.04219222068786621
0.016367197036743164
0.00793910026550293
0.005454063415527344
0.02628803253173828
0.027811527252197266
0.009449958801269531
0.027280569076538086
0.03223609924316406
0.01937556266784668
0.019809246063232422
0.009950637817382812
0.0049593448638916016
0.015376091003417969
0.009918451309204102
0.013391733169555664
0.004464387893676758
0.001983642578125
0.004959821701049805
0.004959821701049805
0.019840002059936523
0.006944417953491211
0.011904001235961914
0.009920597076416016
0.015871524810791016
0.005952119827270508
0.023310184478759766
0.02777576446533203
0.01590442657470703
0.012895345687866211
0.006448984146118164
0.021793365478515625
0.019838333129882812
0.007439613342285156
0.006447792053222656
0.01686382293701172
0.00793600082397461
0.011408090591430664
0.006944179534912109
0.019343852996826172
0.04364824295043945
0.024302005767822266
0.027774333953857422
0.015408754348754883
0.018847227096557617
0.01735997200012207
0.008432149887084961
0.03865790367126465
0.01242971420288086
0.024803638458251953
0.020823240280151367
0.00942230224609375
0.028768062591552734
0.015375852584838867
0.01835179328918457
0.025295495986938477
0.0044629573822021484
0.007969856262207031
0.007933378219604492
0.010912656784057617
0.005455493927001953
0.008411407470703125
0.014879703521728516
0.018849611282348633
0.036704063415527344
0.011407136917114258
0.02235102653503418
0.015842676162719727
0.005950450897216797
0.009919881820678711
0.015873432159423828
0.009422540664672852
0.012897729873657227
0.027314424514770508
0.022315025329589844
0.00598597526550293
0.025792837142944336
0.021793365478515625
0.005486488342285156
0.010418891906738281
0.017913103103637695
0.012431859970092773
0.032326698303222656
0.0089263916015625
0.006943702697753906
0.005456447601318359
0.019839763641357422
0.00892782211303711
0.010912418365478516
0.010416269302368164
0.00843191146850586
0.012895584106445312
0.017360210418701172
0.017856597900390625
0.014374494552612305
0.005455970764160156
0.039679765701293945
0.00396728515625
0.01041555404663086
0.012431144714355469
0.034224510192871094
0.005471706390380859
0.011903762817382812
0.0342257022857666
0.01636648178100586
0.006911754608154297
0.03375864028930664
0.011904001235961914
0.021299362182617188
0.022350549697875977
0.014880180358886719
0.02678227424621582
0.023280620574951172
0.03673577308654785
0.009394407272338867
0.042656898498535156
0.008926153182983398
0.008432626724243164
0.007439613342285156
0.011407852172851562
0.010416269302368164
0.019841670989990234
0.004462480545043945
0.019841909408569336
0.010909795761108398
0.01636815071105957
0.0064487457275390625
0.010412454605102539
0.030256032943725586
0.006943702697753906
0.007439613342285156
0.0054547786712646484
0.004959583282470703
0.006943941116333008
0.003966808319091797
0.007440328598022461
0.007953405380249023
0.01041555404663086
0.009397029876708984
0.003966569900512695
0.013391733169555664
0.01987147331237793
0.005426168441772461
0.022320032119750977
0.005952358245849609
0.022814512252807617
0.009424686431884766
0.006944894790649414
0.015871286392211914
0.0049626827239990234
0.004959821701049805
0.007470846176147461
0.011411428451538086
0.004460811614990234
0.02228832244873047
0.006448268890380859
0.010942935943603516
0.007936716079711914
0.011407852172851562
0.022319555282592773
0.034224510192871094
0.009888410568237305
0.02777576446533203
0.014879703521728516
0.00942373275756836
0.008927345275878906
0.017360210418701172
0.003968000411987305
0.01636815071105957
0.005456209182739258
0.011408567428588867
0.007439851760864258
0.022319793701171875
0.00991964340209961
0.010416269302368164
0.008928298950195312
0.0059528350830078125
0.011905431747436523
0.03967905044555664
0.019842147827148438
0.00644683837890625
0.016398906707763672
0.011408567428588867
0.019374608993530273
0.010415792465209961
0.013891935348510742
0.01983356475830078
0.01832294464111328
0.01934528350830078
0.03273320198059082
0.016864299774169922
0.01835155487060547
0.00793766975402832
0.014383792877197266
0.028272390365600586
0.03474998474121094
0.006447792053222656
0.00344085693359375
0.002976655960083008
0.007935285568237305
0.016895771026611328
0.0034384727478027344
0.0019834041595458984
0.006944894790649414
0.0024771690368652344
0.0014884471893310547
0.005455732345581055
0.003471851348876953
0.003967761993408203
0.0044634342193603516
0.0009920597076416016
0.00347137451171875
0.0029752254486083984
0.0049588680267333984
0.006972789764404297
0.0024826526641845703
0.002975940704345703
0.01090860366821289
0.005948781967163086
0.0004956722259521484
0.004960060119628906
0.0019838809967041016
0.003969669342041016
0.004958391189575195
0.007936477661132812
0.005455732345581055
0.004959583282470703
0.0019843578338623047
0.004464864730834961
0.0034732818603515625
0.005950212478637695
0.00148773193359375
0.0019843578338623047
0.00892782211303711
0.011407852172851562
0.0074405670166015625
0.015872955322265625
0.0034704208374023438
0.003473520278930664
0.004464149475097656
0.0009915828704833984
0.002477407455444336
0.0029783248901367188
0.0019838809967041016
0.0029764175415039062
0.006448268890380859
0.003968000411987305
0.0024797916412353516
0.0014879703521728516
0.008463144302368164
0.0034711360931396484
0.005953073501586914
0.0039365291595458984
0.004464149475097656
0.010942220687866211
0.019840002059936523
0.006449699401855469
0.0019516944885253906
0.002479076385498047
0.010946035385131836
0.0019488334655761719
0.01937413215637207
0.010910987854003906
0.012393951416015625
0.0034487247467041016
0.004464864730834961
0.007937908172607422
0.006973981857299805
0.03667330741882324
0.0024785995483398438
0.00350189208984375
0.0029757022857666016
0.008929014205932617
0.010415077209472656
0.005457639694213867
0.0019519329071044922
0.0019829273223876953
0.006974220275878906
0.007936716079711914
0.0019834041595458984
0.0019845962524414062
0.0014872550964355469
0.017824649810791016
0.0010232925415039062
0.0054399967193603516
0.003007173538208008
0.009913921356201172
0.0029783248901367188
0.0034453868865966797
0.006972074508666992
0.0019559860229492188
0.009459257125854492

0.006909370422363281
0.0004954338073730469
0.00148773193359375
0.0009920597076416016
0.005456209182739258
0.003969669342041016
0.0014896392822265625
0.004961729049682617
0.005982160568237305
0.006446361541748047
0.0044574737548828125
0.0014903545379638672
0.008927583694458008
0.013424158096313477
0.009393930435180664
0.004959583282470703
0.0009920597076416016
0.0024802684783935547
0.02483224868774414
0.0069446563720703125
0.005951642990112305
0.001489877700805664
0.0014858245849609375
0.0034689903259277344
0.0029757022857666016
0.0014867782592773438
0.0009906291961669922
0.006974697113037109
0.0049591064453125
0.0024847984313964844
0.0069427490234375
0.001486063003540039
0.006592512130737305
0.0069732666015625
0.002449512481689453
0.001983642578125
0.006951332092285156
0.0014870166778564453
0.0014908313751220703
0.0049626827239990234
0.012895345687866211
0.0030050277709960938
0.00350189208984375
0.003441333770751953
0.003495454788208008
0.003968715667724609
0.004439592361450195
0.0014879703521728516
0.013422727584838867
0.011401176452636719
0.002952098846435547
0.0015132427215576172
0.004956722259521484
0.002950429916381836
0.005951881408691406
0.0004951953887939453
0.02182459831237793
0.021327733993530273
0.015344619750976562
0.005455732345581055
0.005952358245849609
0.0049591064453125
0.012894868850708008
0.007439374923706055
0.010913372039794922
0.0009920597076416016
0.001981973648071289
0.004464149475097656
0.004960298538208008
0.004959583282470703
0.006448268890380859
0.003967761993408203
0.005952119827270508
0.0014879703521728516
0.0049915313720703125
0.0029730796813964844
0.003441333770751953
0.0034711360931396484
0.0034711360931396484
0.00545501708984375
0.013392925262451172
0.0029745101928710938
0.0019826889038085938
0.004961252212524414
0.0029747486114501953
0.013888359069824219
0.0009918212890625
0.010911941528320312
0.0015385150909423828
0.009424209594726562
0.005951642990112305
0.012400150299072266
0.004462480545043945
0.004959821701049805
0.015872478485107422
0.0009915828704833984
0.005952358245849609
0.007441520690917969
0.008455514907836914
0.004956483840942383
0.0054547786712646484
0.00148773193359375
0.0019838809967041016
0.0019838809967041016
0.003471851348876953
0.005456209182739258
0.003968000411987305
0.001983642578125
0.002480745315551758
0.004464149475097656
0.011934280395507812
0.004960060119628906
0.005951404571533203
0.0019850730895996094
0.0049283504486083984
0.001983642578125
0.01587200164794922
0.006447792053222656
0.004463911056518555
0.00843191146850586
0.002480030059814453
0.003742694854736328
0.0036971569061279297
0.004960060119628906
0.0034728050231933594
0.007935285568237305
0.005456447601318359
0.000988006591796875
0.0014882087707519531
0.0034716129302978516
0.003968000411987305
0.002482175827026367
0.010912656784057617
0.001987457275390625
0.011408329010009766
0.013886451721191406
0.001983165740966797
0.002976655960083008
0.014386177062988281
0.003966093063354492
0.003968715667724609
0.004961967468261719
0.007440090179443359
0.004647016525268555
0.012894392013549805
0.001983642578125
0.003471851348876953
0.0009922981262207031
0.004463672637939453
0.003968000411987305
0.0019838809967041016
0.003966331481933594
0.006943941116333008
0.007935762405395508
0.007440090179443359
0.0009920597076416016
0.004456996917724609
0.0014874935150146484
0.0069427490234375
0.0024805068969726562
0.0009913444519042969
0.0009922981262207031
0.0034716129302978516
0.0009918212890625
0.001983165740966797
0.015376091003417969
0.0049593448638916016
0.007439851760864258
0.008432865142822266
0.007935285568237305
0.005455970764160156
0.003061056137084961
0.007967233657836914
0.005456447601318359
0.005952119827270508
0.00145721435546875
0.004980325698852539
0.0014662742614746094
0.013918638229370117
0.004462480545043945
0.0030069351196289062
0.0029458999633789062
0.007463216781616211
0.0034456253051757812
0.004987478256225586
0.007441520690917969
0.001954317092895508
0.013422012329101562
0.00892019271850586
0.0029518604278564453
0.0039670467376708984
0.007469892501831055
0.003470897674560547
0.003501415252685547
0.003968954086303711
0.005950927734375
0.003937721252441406
0.006968498229980469
0.007910013198852539
0.010914087295532227
0.012894153594970703
0.003470897674560547
0.018878936767578125
0.0034723281860351562
0.003937244415283203
0.0024802684783935547
0.0009908676147460938
0.001983642578125
0.003996849060058594
0.003967761993408203
0.00148773193359375
0.0029752254486083984
0.001512765884399414
0.001959562301635742
0.00148773193359375
0.009450912475585938
0.0029485225677490234
0.005952358245849609
0.003966569900512695
0.005950927734375
0.009427785873413086
0.00747227668762207
0.008418560028076172
0.0009899139404296875
0.008928060531616211
0.010942459106445312
0.00793600082397461
0.00145721435546875
0.0014870166778564453
0.007470130920410156
0.006415605545043945
0.005953311920166016
0.0029807090759277344
0.008432388305664062
0.0049593448638916016
0.0024785995483398438
0.0014882087707519531
0.018384218215942383
0.002947092056274414
0.006940603256225586
0.001951456069946289
0.0010192394256591797
0.004460334777832031
0.013399124145507812
0.005486488342285156
0.002944469451904297
0.0034949779510498047
0.0019598007202148438
0.012424468994140625
0.0029511451721191406
0.0014882087707519531
0.007474184036254883
0.0029413700103759766
0.005950927734375
0.007966279983520508
0.0014595985412597656
0.004486799240112305
0.007415294647216797
0.0010154247283935547
0.009923934936523438
0.011378765106201172
0.005951881408691406
0.0069429874420166016
0.005983114242553711
0.00790548324584961
0.002480745315551758
0.007934331893920898
0.0034720897674560547
0.00396728515625
0.015377521514892578
0.0009906291961669922
0.0054552555084228516
0.005951881408691406
0.004461765289306641
0.003968000411987305
0.013886451721191406
0.003471851348876953
0.006975889205932617
0.012897729873657227
0.02529430389404297
0.0009915828704833984
0.020335912704467773
0.01137685775756836
0.004958629608154297
0.00396728515625
0.006448268890380859
0.003968954086303711
0.008927345275878906
0.007936954498291016
0.006941318511962891
0.0049591064453125
0.009424686431884766
0.009919404983520508
0.002975940704345703
0.0024797916412353516
0.0029761791229248047
0.0024785995483398438
0.0009918212890625
0.008928060531616211
0.0004961490631103516
0.003968000411987305
0.0034716129302978516
0.013391971588134766
0.0054585933685302734
0.0049626827239990234
0.0029730796813964844
0.005951404571533203
0.004495143890380859
0.0019524097442626953
0.00843048095703125
0.006975889205932617
0.005921125411987305
0.012424468994140625
0.005954265594482422
0.003469705581665039
0.008455514907836914
0.021328449249267578
0.0064547061920166016
0.0024499893188476562
0.008926153182983398
0.011936426162719727
0.005983829498291016
0.007947444915771484
0.0014574527740478516
0.009449005126953125
0.002454996109008789
0.004959821701049805
0.022815942764282227
0.019840478897094727
0.08481621742248535
0.020337820053100586
0.04020524024963379
0.030200958251953125
0.027776718139648438
0.010909080505371094
0.011410236358642578
0.013417243957519531
0.005978822708129883
0.05158519744873047
0.053040504455566406
0.026319265365600586
0.01537632942199707
0.009423255920410156
0.023314952850341797
0.032207489013671875
0.020830631256103516
0.0411679744720459
0.020830869674682617
0.030785799026489258
0.06001615524291992
0.07387351989746094
0.013390302658081055
0.03422403335571289
0.03620767593383789
0.022352218627929688
0.026782989501953125
0.03865838050842285
0.0253298282623291
0.07241225242614746
0.005945444107055664
0.010391712188720703
0.026323795318603516
0.02228546142578125
0.043677568435668945
0.014384269714355469
0.04463696479797363
0.04659271240234375
0.05009627342224121
0.010414838790893555
0.1284940242767334
0.022849559783935547
0.04162883758544922
0.03323245048522949
0.029263973236083984
0.08680081367492676
0.03769493103027344
0.05902266502380371
0.029263734817504883
0.07241654396057129
0.017360448837280273
0.024799346923828125
0.01735997200012207
0.08035159111022949
0.016863107681274414
0.018847227096557617
0.0764153003692627
0.0059506893157958984
0.009945154190063477
0.012872695922851562
0.021858692169189453
0.03865623474121094
0.020832538604736328
0.05260610580444336
0.013363361358642578
0.02082967758178711
0.024812936782836914

0.10766363143920898
0.024304866790771484
0.023777484893798828
0.024797916412353516
0.08137774467468262
0.06295990943908691
0.017389774322509766
0.030225515365600586
0.03223824501037598
0.0074405670166015625
0.03620743751525879
0.025792360305786133
0.037695884704589844
0.021855831146240234
0.02625417709350586
0.016399860382080078
0.015941858291625977
0.046129465103149414
0.03422284126281738
0.021327495574951172
0.013888359069824219
0.022319793701171875
0.030751705169677734
0.04169464111328125
0.04761648178100586
0.04811549186706543
0.012398481369018555
0.02628779411315918
0.018848419189453125
0.04860877990722656
0.010415077209472656
0.022321462631225586
0.015374422073364258
0.01391911506652832
0.01187443733215332
0.014877557754516602
0.03971076011657715
0.019870281219482422
0.025265932083129883
0.02579021453857422
0.01488184928894043
0.02231907844543457
0.0332331657409668
0.03127789497375488
0.016336441040039062
0.01835155487060547
0.020335674285888672
0.009920120239257812
0.017391443252563477
0.024272918701171875
0.03274679183959961
0.01388692855834961
0.052575111389160156
0.05108952522277832
0.014878273010253906
0.013423681259155273
0.010384798049926758
0.025821685791015625
0.03518486022949219
0.029790878295898438
0.04709053039550781
0.024829387664794922
0.01835179328918457
0.038689613342285156
0.016336441040039062
0.053101539611816406
0.0520787239074707
0.05555295944213867
0.02235126495361328
0.024303436279296875
0.03868889808654785
0.022815942764282227
0.0381929874420166
0.037786245346069336
0.029895305633544922
0.010910749435424805
0.01190185546875
0.06147193908691406
0.04765009880065918
0.015372276306152344
0.021327733993530273
0.018321990966796875
0.01644277572631836
0.031247854232788086
0.018848180770874023
0.014880180358886719
0.003471851348876953
0.04364728927612305
0.0421907901763916
0.02377796173095703
0.028766393661499023
0.05161595344543457
0.047119140625
0.024768829345703125
0.007935047149658203
0.027280092239379883
0.01686573028564453
0.026317358016967773
0.016896724700927734
0.03322863578796387
0.04463672637939453
0.022816896438598633
0.012399911880493164
0.035712480545043945
0.05806279182434082
0.011409521102905273
0.11110091209411621
0.014383316040039062
0.022847414016723633
0.007442474365234375
0.024301528930664062
0.07390403747558594
0.038191795349121094
0.04020571708679199
0.007905244827270508
0.024331331253051758
0.03918147087097168
0.058030128479003906
0.058065176010131836
0.02133941650390625
0.0218198299407959
0.024303674697875977
0.017855167388916016
0.02529621124267578
0.032241106033325195
0.02331066131591797
0.014862298965454102
0.05009627342224121
0.040670156478881836
0.04960012435913086
0.04315352439880371
0.010910511016845703
0.031248092651367188
0.037696123123168945
0.02083277702331543
0.008432149887084961
0.03868865966796875
0.03422355651855469
0.05852770805358887
0.04414248466491699
0.027776002883911133
0.037697553634643555
0.06401515007019043
0.0550234317779541
0.007439851760864258
0.002480030059814453
0.05657601356506348
0.02132701873779297
0.026287317276000977
0.020832061767578125
0.05849862098693848
0.030254840850830078
0.013392210006713867
0.00892949104309082
0.05505537986755371
0.0540618896484375
0.015375852584838867
0.08881711959838867
0.053070068359375
0.028769969940185547
0.015306472778320312
0.022817134857177734
0.020830869674682617
0.020831584930419922
0.02380847930908203
0.025791406631469727
0.007440090179443359
0.014881372451782227
0.017358064651489258
0.008928060531616211
0.04463982582092285
0.045135498046875
0.016399621963500977
0.06844830513000488
0.03275465965270996
0.020335912704467773
0.007471799850463867
0.015377521514892578
0.03273463249206543
0.011901378631591797
0.04414534568786621
0.04560065269470215
0.017854928970336914
0.026782512664794922
0.06348490715026855
0.007439613342285156
0.012896060943603516
0.031248092651367188
0.024799346923828125
0.0421600341796875
0.004464149475097656
0.01983952522277832
0.01041555404663086
0.03521585464477539
0.019839763641357422
0.013391494750976562
0.02929544448852539
0.008432388305664062
0.009919404983520508
0.035184621810913086
0.04116988182067871
0.026784896850585938
0.04215860366821289
0.019343852996826172
0.02334761619567871
0.01335597038269043
0.0431520938873291
0.03620791435241699
0.03769564628601074
0.01934361457824707
0.02579331398010254
0.029294967651367188
0.04066872596740723
0.01389002799987793
0.03419375419616699
0.0401761531829834
0.031246423721313477
0.029792070388793945
0.01934361457824707
0.0034723281860351562
0.037199974060058594
0.02973008155822754
0.006942272186279297
0.024801254272460938
0.0074405670166015625
0.07839822769165039
0.01636362075805664
0.03574204444885254
0.021300792694091797
0.04315185546875
0.017887115478515625
0.048081398010253906
0.04761552810668945
0.011406898498535156
0.00991964340209961
0.022320032119750977
0.030752182006835938
0.04563188552856445
0.018352508544921875
0.030254840850830078
0.020830869674682617
0.013392210006713867
0.05108809471130371
0.07046318054199219
0.025791406631469727
0.05803251266479492
0.022815465927124023
0.021823644638061523
0.019345998764038086
0.005456209182739258
0.05356788635253906
0.0684804916381836
0.023270130157470703
0.025791645050048828
0.048143625259399414
0.034192800521850586
0.04761528968811035
0.012400388717651367
0.06001687049865723
0.03620743751525879
0.008928060531616211
0.016863584518432617
0.008928060531616211
0.013888359069824219
0.09969782829284668
0.03719806671142578
0.016864538192749023
0.05208015441894531
0.08084702491760254
0.08633899688720703
0.019343852996826172
0.023282766342163086
0.01835179328918457
0.026781320571899414
0.032239437103271484
0.03472161293029785
0.03273439407348633
0.00843191146850586
0.04067182540893555
0.03075098991394043
0.02136397361755371
0.034719228744506836
0.03471875190734863
0.018848180770874023
0.01887965202331543
0.051058292388916016
0.00942230224609375
0.016369342803955078
0.04116678237915039
0.014384031295776367
0.026815176010131836
0.007936954498291016
0.03196883201599121
0.02281475067138672
0.05459117889404297
0.015375852584838867
0.041138648986816406
0.010414600372314453
0.02529621124267578
0.009453535079956055
0.04758429527282715
0.04166436195373535
0.11110353469848633
0.015028953552246094
0.05310249328613281
0.021824359893798828
0.006447792053222656
0.04067349433898926
0.07492589950561523
0.03719973564147949
0.02083301544189453
0.012963294982910156
0.034256935119628906
0.027248620986938477
0.007439136505126953
0.029758214950561523
0.019870996475219727
0.012399911880493164
0.11057639122009277
0.01392054557800293
0.0064470767974853516
0.033698081970214844
0.02678370475769043
0.010910749435424805
0.03276801109313965
0.016864776611328125
0.01042032241821289
0.04708576202392578
0.0421907901763916
0.00889730453491211
0.015406131744384766
0.0480802059173584
0.020831584930419922
0.06497645378112793
0.00942230224609375
0.005952119827270508
0.018848419189453125
0.053072214126586914
0.019374608993530273
0.01339268684387207
0.006448030471801758
0.030782222747802734
0.0471189022064209
0.019335269927978516
0.03971123695373535
0.02474069595336914
0.02182459831237793
0.02628803253173828
0.022350549697875977
0.01091146469116211
0.05211353302001953
0.03571200370788574
0.04117274284362793
0.029254913330078125
0.008432149887084961
0.010416269302368164
0.07195138931274414
0.017328500747680664
0.017839670181274414
0.030781269073486328
0.02229022979736328
0.021822214126586914
0.016399621963500977
0.023808717727661133
0.008895635604858398
0.026319503784179688
0.041663408279418945
0.01223897933959961
0.03769564628601074
0.011905431747436523
0.029262065887451172
0.06649565696716309
0.003938198089599609
0.02033376693725586
0.028768062591552734
0.022319793701171875
0.020336151123046875
0.027777671813964844
0.012895584106445312
0.053566694259643555
0.01789069175720215
0.019806861877441406
0.043645620346069336
0.009424209594726562
0.033759355545043945
0.01435232162475586
0.020833730697631836
0.02975773811340332
0.009423017501831055
0.08035159111022949
0.03372788429260254
0.014879941940307617
0.011408567428588867
0.018847227096557617
0.01537632942199707
0.0431516170501709
0.03769564628601074
0.012399911880493164
0.046624183654785156
0.0391840934753418
0.037726640701293945
0.01540517807006836
0.015376806259155273
0.048111677169799805
0.07439970970153809

0.03620743751525879
0.017853736877441406
0.019374608993530273
0.0128936767578125
0.08335328102111816
0.017380952835083008
0.028738021850585938
0.037694454193115234
0.023313522338867188
0.03818988800048828
0.03872203826904297
0.006941556930541992
0.04562544822692871
0.04563403129577637
0.03124833106994629
0.041198015213012695
0.029231786727905273
0.028303146362304688
0.011904001235961914
0.025793790817260742
0.058992624282836914
0.013391733169555664
0.016861915588378906
0.024831771850585938
0.021859169006347656
0.04414010047912598
0.02526378631591797
0.02036738395690918
0.027248144149780273
0.02135944366455078
0.029761075973510742
0.023777008056640625
0.06894183158874512
0.03323197364807129
0.08630609512329102
0.05257558822631836
0.030255794525146484
0.03174161911010742
0.010912179946899414
0.012895822525024414
0.014415979385375977
0.019840240478515625
0.02529621124267578
0.024829864501953125
0.023400068283081055
0.030753612518310547
0.051613569259643555
0.022815704345703125
0.026782512664794922
0.02430558204650879
0.03099536895751953
0.008430957794189453
0.012398719787597656
0.01686406135559082
0.030256271362304688
0.06051206588745117
0.05604696273803711
0.012924432754516602
0.04907488822937012
0.016367435455322266
0.030256032943725586
0.03372764587402344
0.057534217834472656
0.035247087478637695
0.019840002059936523
0.030254364013671875
0.031279563903808594
0.0500645637512207
0.06001758575439453
0.03819012641906738
0.08187198638916016
0.07886409759521484
0.04761481285095215
0.04364800453186035
0.03872346878051758
0.0049533843994140625
0.01739025115966797
0.0550532341003418
0.02232503890991211
0.014849662780761719
0.05310225486755371
0.011907339096069336
0.007932901382446289
0.009922266006469727
0.017360925674438477
0.03422379493713379
0.022818803787231445
0.0386965274810791
0.015375614166259766
0.013890266418457031
0.04411005973815918
0.022847414016723633
0.029233932495117188
0.046622276306152344
0.0704646110534668
0.008897066116333008
0.00896000862121582
0.017331838607788086
0.025266170501708984
0.013917684555053711
0.008896589279174805
0.02532672882080078
0.04910421371459961
0.04163384437561035
0.02876758575439453
0.04116654396057129
0.0530705451965332
0.018847942352294922
0.00843191146850586
0.09774494171142578
0.005949974060058594
0.036241769790649414
0.03422117233276367
0.01537632942199707
0.021823644638061523
0.02232074737548828
0.008926868438720703
0.026288747787475586
0.00992274284362793
0.02232050895690918
0.06399130821228027
0.015878915786743164
0.02873373031616211
0.04067206382751465
0.04067111015319824
0.01587200164794922
0.012895822525024414
0.014879703521728516
0.08084893226623535
0.08287453651428223
0.03967094421386719
0.014384269714355469
0.017855405807495117
0.029234647750854492
0.045662641525268555
0.01881575584411621
0.007938385009765625
0.03872060775756836
0.017355918884277344
0.013889312744140625
0.055548906326293945
0.034194231033325195
0.11457443237304688
0.11308741569519043
0.035710811614990234
0.019376039505004883
0.018988847732543945
0.01187276840209961
0.028767824172973633
0.05803203582763672
0.023807525634765625
0.003968000411987305
0.009425163269042969
0.07142353057861328
0.014878511428833008
0.028272151947021484
0.04265594482421875
0.01590442657470703
0.01983785629272461
0.06696009635925293
0.013887882232666016
0.0952310562133789
0.04268932342529297
0.018320798873901367
0.027776718139648438
0.01438283920288086
0.02132701873779297
0.006945133209228516
0.021358013153076172
0.07737612724304199
0.016367673873901367
0.016336917877197266
0.02532792091369629
0.01832127571105957
0.004494428634643555
0.02579188346862793
0.02826857566833496
0.013392210006713867
0.04067349433898926
0.03471851348876953
0.007440090179443359
0.004929542541503906
0.02929067611694336
0.05158710479736328
0.014877796173095703
0.044637441635131836
0.05158710479736328
0.029262781143188477
0.10908794403076172
0.010416269302368164
0.04960012435913086
0.016367673873901367
0.06299352645874023
0.029758214950561523
0.04070544242858887
0.0540924072265625
0.008969545364379883
0.06636524200439453
0.018349409103393555
0.03223991394042969
0.053568363189697266
0.041663408279418945
0.011438846588134766
0.03072190284729004
0.020334243774414062
0.037215232849121094
0.05604839324951172
0.008400440216064453
0.06348943710327148
0.014879703521728516
0.010910272598266602
0.05161476135253906
0.012378931045532227
0.011933565139770508
0.015942811965942383
0.04808187484741211
0.009423494338989258
0.013887882232666016
0.06451129913330078
0.021801471710205078
0.01735997200012207
0.045134782791137695
0.0441439151763916
0.030779361724853516
0.006992816925048828
0.010444879531860352
0.0069468021392822266
0.004960060119628906
0.0892493724822998
0.01785421371459961
0.03273606300354004
0.02331376075744629
0.10862207412719727
0.1076662540435791
0.014879941940307617
0.026784420013427734
0.02777576446533203
0.06150364875793457
0.020336151123046875
0.08283281326293945
0.028271198272705078
0.0034711360931396484
0.012894630432128906
0.014382362365722656
0.015375375747680664
0.01835036277770996
0.010415792465209961
0.021823644638061523
0.014880180358886719
0.016367673873901367
0.02678394317626953
0.03174567222595215
0.014383316040039062
0.02132868766784668
0.00942373275756836
0.08828878402709961
0.05555272102355957
0.03872251510620117
0.019309282302856445
0.012894630432128906
0.012399911880493164
0.013392210006713867
0.00793600082397461
0.026288986206054688
0.04315066337585449
0.02231907844543457
0.024801015853881836
0.047615766525268555
0.01438283920288086
0.009424209594726562
0.027776002883911133
0.002975940704345703
0.04960012435913086
0.047617197036743164
0.03918266296386719
0.050127506256103516
0.01885199546813965
0.018843650817871094
0.025793075561523438
0.03025531768798828
0.03673410415649414
0.015373706817626953
0.028302907943725586
0.025296449661254883
0.05254387855529785
0.012399435043334961
0.014382123947143555
0.03574419021606445
0.03819680213928223
0.0123748779296875
0.017391681671142578
0.03769326210021973
0.031246185302734375
0.019343852996826172
0.01587224006652832
0.009920358657836914
0.017856359481811523
0.0401759147644043
0.020336389541625977
0.011902809143066406
0.029264450073242188
0.02876758575439453
0.014878511428833008
0.09324836730957031
0.017358779907226562
0.07985758781433105
0.013886690139770508
0.021327733993530273
0.09721803665161133
0.04612612724304199
0.16417717933654785
0.0500948429107666
0.031247854232788086
0.013888359069824219
0.010415792465209961
0.013888120651245117
0.021823883056640625
0.048111915588378906
0.007936477661132812
0.020832300186157227
0.010414600372314453
0.027776002883911133
0.012931346893310547
0.014879226684570312
0.04563117027282715
0.011385202407836914
0.045136451721191406
0.05009603500366211
0.01342010498046875
0.03171181678771973
0.024832487106323242
0.026287078857421875
0.010416507720947266
0.011404275894165039
0.02529597282409668
0.03816080093383789
0.006448030471801758
0.021825075149536133
0.015405893325805664
0.0813450813293457
0.009527206420898438
0.05155301094055176
0.0441746711730957
0.051056623458862305
0.029263973236083984
0.009952306747436523
0.054558515548706055
0.02780747413635254
0.02129507064819336
0.01537466049194336
0.05062389373779297
0.07040047645568848
0.015871763229370117
0.025327444076538086
0.01587200164794922
0.03964996337890625
0.014384269714355469
0.042157888412475586
0.030783414840698242
0.008925199508666992
0.03121805191040039
0.03276634216308594
0.021329164505004883
0.04665541648864746
0.042191505432128906
0.010382413864135742
0.026813507080078125
0.03273439407348633
0.00889730453491211
0.045660972595214844
0.010913610458374023
0.018320560455322266
0.03174471855163574
0.09324359893798828
0.016338348388671875
0.06199789047241211
0.11014413833618164
0.021296024322509766
0.017360210418701172
0.04516744613647461
0.005456209182739258
0.015901803970336914
0.03322958946228027
0.0421290397644043
0.017360448837280273
0.03323101997375488
0.04067182540893555
0.04067087173461914
0.04464125633239746
0.06398224830627441
0.0550541877746582
0.05902433395385742
0.030255556106567383
0.011904716491699219
0.02430272102355957
0.07737421989440918
0.0381922721862793
0.06547188758850098
0.029264450073242188
0.026784181594848633
0.013428449630737305
0.030717849731445312
0.028271198272705078
0.06695938110351562
0.018847942352294922

0.029792070388793945
0.05356764793395996
0.15028810501098633
0.041695594787597656
0.02678227424621582
0.013892412185668945
0.01583719253540039
0.02579331398010254
0.013390064239501953
0.0411992073059082
0.03568220138549805
0.01937127113342285
0.019842863082885742
0.04265570640563965
0.013425588607788086
0.03372812271118164
0.031216144561767578
0.01488041877746582
0.046625375747680664
0.01785421371459961
0.05062365531921387
0.017824411392211914
0.03769564628601074
0.011904239654541016
0.030256986618041992
0.015870332717895508
0.035218000411987305
0.056574344635009766
0.023777484893798828
0.052109479904174805
0.018848180770874023
0.014401912689208984
0.011410951614379883
0.009917974472045898
0.021361589431762695
0.027745962142944336
0.034223318099975586
0.01888108253479004
0.018815279006958008
0.008430719375610352
0.013392448425292969
0.035712480545043945
0.024302005767822266
0.02331233024597168
0.014383792877197266
0.022816181182861328
0.013887405395507812
0.024799585342407227
0.031249284744262695
0.03769397735595703
0.08580851554870605
0.03174328804016113
0.019869089126586914
0.012398719787597656
0.012896537780761719
0.02033543586730957
0.016894102096557617
0.014414310455322266
0.01389002799987793
0.015345573425292969
0.016399145126342773
0.03617715835571289
0.012893438339233398
0.026288270950317383
0.020831584930419922
0.037200212478637695
0.00991964340209961
0.018352270126342773
0.03868746757507324
0.0441439151763916
0.021327495574951172
0.04464221000671387
0.012399911880493164
0.019841670989990234
0.039182424545288086
0.04463982582092285
0.03422403335571289
0.013390779495239258
0.009424209594726562
0.04116702079772949
0.027776241302490234
0.05409526824951172
0.017390966415405273
0.04908132553100586
0.027808666229248047
0.044141530990600586
0.01091313362121582
0.021822214126586914
0.026783227920532227
0.02975940704345703
0.010942935943603516
0.06894350051879883
0.016834020614624023
0.03868865966796875
0.015374183654785156
0.05852842330932617
0.008927583694458008
0.057041168212890625
0.024333477020263672
0.038161277770996094
0.004462718963623047
0.11457586288452148
0.07046341896057129
0.0872957706451416
0.012401819229125977
0.01782536506652832
0.03323054313659668
0.006447792053222656
0.04464006423950195
0.017888307571411133
0.03475236892700195
0.08180761337280273
0.024300813674926758
0.030256032943725586
0.01636815071105957
0.08187460899353027
0.029756546020507812
0.01934337615966797
0.03568100929260254
0.041168212890625
0.034720420837402344
0.013391733169555664
0.0024802684783935547
0.0029764175415039062
0.013391494750976562
0.003472566604614258
0.0352170467376709
0.04414629936218262
0.01239633560180664
0.01286458969116211
0.052606821060180664
0.06596612930297852
0.013392925262451172
0.002480030059814453
0.0352170467376709
0.014386653900146484
0.022320032119750977
0.023312091827392578
0.08283352851867676
0.04315185546875
0.02678370475769043
0.028270244598388672
0.00793600082397461
0.01735973358154297
0.019344329833984375
0.030783414840698242
0.058474063873291016
0.002974271774291992
0.021854877471923828
0.013391971588134766
0.045601606369018555
0.04662346839904785
0.019344806671142578
0.040702104568481445
0.025297164916992188
0.007938385009765625
0.014383077621459961
0.00942230224609375
0.0382232666015625
0.05155444145202637
0.0069730281829833984
0.048612356185913086
0.04314923286437988
0.10214591026306152
0.02780604362487793
0.011437416076660156
0.004461765289306641
0.006447792053222656
0.03568005561828613
0.07142329216003418
0.006943941116333008
0.004463911056518555
0.013918876647949219
0.014383316040039062
0.007904291152954102
0.006448030471801758
0.05756545066833496
0.03670620918273926
0.05208253860473633
0.011904001235961914
0.009389638900756836
0.026784181594848633
0.02331233024597168
0.006447792053222656
0.039183855056762695
0.009424448013305664
0.024304628372192383
0.018352031707763672
0.01686263084411621
0.006447792053222656
0.032273292541503906
0.01534414291381836
0.036237478256225586
0.009423494338989258
0.014850854873657227
0.0064775943756103516
0.00793600082397461
0.004960775375366211
0.018351078033447266
0.013360023498535156
0.011439085006713867
0.0059201717376708984
0.03378415107727051
0.012865304946899414
0.017394304275512695
0.00857234001159668
0.04116702079772949
0.022539138793945312
0.04464125633239746
0.010416507720947266
0.018846750259399414
0.015873432159423828
0.025791168212890625
0.026782751083374023
0.03968000411987305
0.03521585464477539
0.001984119415283203
0.04265570640563965
0.009423971176147461
0.015375375747680664
0.03524923324584961
0.005952119827270508
0.012867927551269531
0.01587080955505371
0.013887643814086914
0.0625298023223877
0.03769397735595703
0.028771162033081055
0.012927532196044922
0.026259422302246094
0.06993460655212402
0.052110910415649414
0.0421605110168457
0.04513716697692871
0.09972572326660156
0.054032325744628906
0.01339411735534668
0.024333715438842773
0.05304145812988281
0.0034723281860351562
0.029263734817504883
0.005454540252685547
0.028272390365600586
0.002975940704345703
0.010911703109741211
0.008928298950195312
0.02532958984375
0.013390302658081055
0.027743101119995117
0.06348991394042969
0.03968024253845215
0.006942272186279297
0.06153440475463867
0.010911226272583008
0.06547021865844727
0.0991973876953125
0.08134222030639648
0.010912179946899414
0.10412859916687012
0.01735997200012207
0.05059099197387695
0.06698846817016602
0.0031545162200927734
0.01987147331237793
0.013970613479614258
0.0491032600402832
0.006447792053222656
0.009422779083251953
0.08980727195739746
0.15422391891479492
0.06649231910705566
0.020804405212402344
0.012894153594970703
0.005952119827270508
0.006475925445556641
0.15574336051940918
0.060491085052490234
0.0501253604888916
0.026754379272460938
0.005950212478637695
0.011904001235961914
0.020831823348999023
0.04811215400695801
0.013885974884033203
0.006447315216064453
0.00942230224609375
0.008928060531616211
0.05555248260498047
0.014385223388671875
0.056542396545410156
0.033745527267456055
0.05607795715332031
0.011906862258911133
0.04066944122314453
0.025295495986938477
0.017358064651489258
0.06445050239562988
0.02827143669128418
0.09126520156860352
0.07142210006713867
0.032767534255981445
0.011904478073120117
0.023772478103637695
0.018346071243286133
0.00896143913269043
0.08976268768310547
0.05112147331237793
0.01041412353515625
0.006447553634643555
0.018846511840820312
0.02132892608642578
0.08878374099731445
0.010910749435424805
0.2713131904602051
0.01934218406677246
0.0034720897674560547
0.010910272598266602
0.04315185546875
0.01636791229248047
0.0441436767578125
0.023311376571655273
0.019343852996826172
0.05359840393066406
0.015875816345214844
0.04761219024658203
0.021840333938598633
0.03072214126586914
0.013389825820922852
0.03471946716308594
0.010911941528320312
0.012897253036499023
0.03670334815979004
0.008927345275878906
0.010416030883789062
0.013887882232666016
0.006943225860595703
0.023342132568359375
0.009921550750732422
0.01094198226928711
0.019347190856933594
0.04017519950866699
0.014879226684570312
0.005455493927001953
0.039215803146362305
0.03668045997619629
0.0381922721862793
0.003966331481933594
0.033263444900512695
0.003974199295043945
0.03718733787536621
0.02727985382080078
0.026288509368896484
0.035248517990112305
0.040671586990356445
0.016865015029907227
0.028766632080078125
0.15323209762573242
0.008430242538452148
0.019841432571411133
0.0046613216400146484
0.010416030883789062
0.027279138565063477
0.01683497428894043
0.020861387252807617
0.14262604713439941
0.04067182540893555
0.030750274658203125
0.010415792465209961
0.02480030059814453
0.028768301010131836
0.02430415153503418
0.013888359069824219
0.01785588264465332
0.2882075309753418
0.007968664169311523
0.017384052276611328
0.011380434036254883
0.004463911056518555
0.15031814575195312
0.01732945442199707
0.017856836318969727
0.06302237510681152
0.07089352607727051
0.06699085235595703
0.07691144943237305
0.009422779083251953
0.017359018325805664
0.02082967758178711
0.0025200843811035156
0.046624183654785156
0.024800539016723633
0.03571295738220215
0.008430719375610352
0.09820747375488281
0.06894493103027344
0.01587200164794922
0.014878511428833008
0.011438846588134766
0.014353036880493164
0.06249499320983887
0.032239675521850586
0.014383316040039062
0.00446319580078125

0.11209702491760254
0.05455899238586426
0.05704188346862793
0.18004608154296875
0.0803520679473877
0.010910511016845703
0.003968000411987305
0.049138545989990234
0.06891083717346191
0.03078174591064453
0.0905001163482666
0.004960298538208008
0.005951404571533203
0.026256322860717773
0.004464149475097656
0.00793600082397461
0.003471851348876953
0.012433290481567383
0.022812604904174805
0.021823883056640625
0.0029456615447998047
0.0069732666015625
0.011408805847167969
0.01732802391052246
0.005951642990112305
0.014879465103149414
0.0029761791229248047
0.009456157684326172
0.009423494338989258
0.017359495162963867
0.01636815071105957
0.016371965408325195
0.0177457332611084
0.006448030471801758
0.010415792465209961
0.010912179946899414
0.014387130737304688
0.019342660903930664
0.014879226684570312
0.013886213302612305
0.006447553634643555
0.008433103561401367
0.01831793785095215
0.020334482192993164
0.015376091003417969
0.005951881408691406
0.008928060531616211
0.020826101303100586
0.006447553634643555
0.00942373275756836
0.003968000411987305
0.013392210006713867
0.012897253036499023
0.0089263916015625
0.005456447601318359
0.006447315216064453
0.007935285568237305
0.014383554458618164
0.026784181594848633
0.014879941940307617
0.003966569900512695
0.013888835906982422
0.027775287628173828
0.014383792877197266
0.012894868850708008
0.013391494750976562
0.026782512664794922
0.029264450073242188
0.0059528350830078125
0.008928775787353516
0.001984119415283203
0.007935762405395508
0.022320270538330078
0.015375375747680664
0.008928060531616211
0.0039632320404052734
0.023808002471923828
0.0034754276275634766
0.0064449310302734375
0.009406328201293945
0.004960060119628906
0.005983829498291016
0.013916969299316406
0.007935523986816406
0.01236867904663086
0.01342320442199707
0.016834020614624023
0.021358489990234375
0.01488041877746582
0.009920358657836914
0.01987147331237793
0.022815942764282227
0.007932901382446289
0.014879226684570312
0.003968000411987305
0.02132248878479004
0.010415315628051758
0.006945371627807617
0.0173647403717041
0.009919404983520508
0.007904529571533203
0.004463672637939453
0.015375375747680664
0.015376806259155273
0.006944417953491211
0.010421514511108398
0.015866518020629883
0.009453058242797852
0.011411905288696289
0.009423017501831055
0.010415792465209961
0.00446772575378418
0.00397038459777832
0.0034384727478027344
0.01441812515258789
0.008457183837890625
0.012396097183227539
0.003475189208984375
0.0069348812103271484
0.010390520095825195
0.010911941528320312
0.009206533432006836
0.023311138153076172
0.02480292320251465
0.008925914764404297
0.018847942352294922
0.01686406135559082
0.01686382293701172
0.014384269714355469
0.030255794525146484
0.00793600082397461
0.020336151123046875
0.016366958618164062
0.015870094299316406
0.03422284126281738
0.011904239654541016
0.005951881408691406
0.010416030883789062
0.014384031295776367
0.011903762817382812
0.009920358657836914
0.005951881408691406
0.0391843318939209
0.012892961502075195
0.0074388980865478516
0.01736307144165039
0.0069332122802734375
0.01388859748840332
0.009423494338989258
0.027776002883911133
0.00942373275756836
0.005455970764160156
0.004960298538208008
0.018352508544921875
0.012399673461914062
0.006946086883544922
0.008928060531616211
0.019840002059936523
0.00743865966796875
0.012399673461914062
0.011903762817382812
0.020336627960205078
0.025326251983642578
0.010411500930786133
0.008930683135986328
0.003968000411987305
0.017578125
0.01785588264465332
0.017856121063232422
0.013887643814086914
0.011936426162719727
0.007404804229736328
0.020336151123046875
0.009919881820678711
0.02479863166809082
0.019344806671142578
0.014383077621459961
0.01639866828918457
0.016861915588378906
0.014377832412719727
0.013863086700439453
0.031278133392333984
0.005449056625366211
0.00795125961303711
0.014876365661621094
0.00989389419555664
0.000993967056274414
0.024799346923828125
0.017889738082885742
0.010383844375610352
0.010447978973388672
0.005498409271240234
0.019343852996826172
0.006447315216064453
0.009424448013305664
0.006448030471801758
0.00892782211303711
0.003968000411987305
0.007439851760864258
0.013888120651245117
0.013393402099609375
0.01587057113647461
0.014879941940307617
0.014874935150146484
0.019377946853637695
0.008482217788696289
0.020337343215942383
0.00942373275756836
0.013883590698242188
0.022321224212646484
0.006457328796386719
0.004461050033569336
0.008957624435424805
0.005980491638183594
0.007436990737915039
0.014903783798217773
0.008409976959228516
0.01487874984741211
0.016861438751220703
0.002015352249145508
0.007921218872070312
0.0089263916015625
0.012431859970092773
0.004462480545043945
0.008463144302368164
0.006944179534912109
0.009917974472045898
0.04213070869445801
0.004481792449951172
0.0014617443084716797
0.015374422073364258
0.00545501708984375
0.006944179534912109
0.01686382293701172
0.00942230224609375
0.002481698989868164
0.012895345687866211
0.0034704208374023438
0.014415740966796875
0.00839996337890625
0.003968238830566406
0.02086329460144043
0.014873743057250977
0.02080702781677246
0.010911703109741211
0.009423255920410156
0.018321752548217773
0.015901565551757812
0.0173490047454834
0.007935285568237305
0.03372836112976074
0.0044612884521484375
0.026287555694580078
0.015871524810791016
0.006943941116333008
0.011407852172851562
0.006448268890380859
0.005951881408691406
0.006943941116333008
0.008432149887084961
0.0024797916412353516
0.006447553634643555
0.007440328598022461
0.008927583694458008
0.02480006217956543
0.017856597900390625
0.009920358657836914
0.004463911056518555
0.009919881820678711
0.01537632942199707
0.0044634342193603516
0.006943702697753906
0.0024793148040771484
0.008929014205932617
0.019343137741088867
0.007471561431884766
0.004464864730834961
0.009426355361938477
0.008928537368774414
0.005456209182739258
0.009423971176147461
0.00991964340209961
0.007440328598022461
0.01735973358154297
0.01785731315612793
0.019839048385620117
0.008431196212768555
0.03174400329589844
0.0049591064453125
0.013392210006713867
0.019840002059936523
0.0034711360931396484
0.010415315628051758
0.007935285568237305
0.01292729377746582
0.013392448425292969
0.008929252624511719
0.00892782211303711
0.011409759521484375
0.020309925079345703
0.016367435455322266
0.007439613342285156
0.013919591903686523
0.020799875259399414
0.010416507720947266
0.01735830307006836
0.009424209594726562
0.010911703109741211
0.006943941116333008
0.007935285568237305
0.008928298950195312
0.008462905883789062
0.017360210418701172
0.005951642990112305
0.02480006217956543
0.008401155471801758
0.0069429874420166016
0.00747227668762207
0.004928112030029297
0.005949735641479492
0.0024805068969726562
0.007468461990356445
0.011407852172851562
0.005455970764160156
0.007466554641723633
0.022820234298706055
0.0015225410461425781
0.008924007415771484
0.009886503219604492
0.02083277702331543
0.010414361953735352
0.005456209182739258
0.009424448013305664
0.017364025115966797
0.003468036651611328
0.018847942352294922
0.003467082977294922
0.015376567840576172
0.010910272598266602
0.01339411735534668
0.009920358657836914
0.008958578109741211
0.007464885711669922
0.009383678436279297
0.013870477676391602
0.007441282272338867
0.011407136917114258
0.010911941528320312
0.007438182830810547
0.011407852172851562
0.005951642990112305
0.023348331451416016
0.015345573425292969
0.001985311508178711
0.01091313362121582
0.005488157272338867
0.007437705993652344
0.016832351684570312
0.012896299362182617
0.028767824172973633
0.014380455017089844
0.02033257484436035
0.01934337615966797
0.010912179946899414
0.012895822525024414
0.01537632942199707
0.0044634342193603516
0.003968000411987305
0.009423017501831055
0.00793600082397461
0.014878988265991211
0.005468845367431641
0.01242971420288086
0.005950927734375
0.013557910919189453
0.019853830337524414
0.02481985092163086
0.003438234329223633
0.013423919677734375
0.010916709899902344
0.021824359893798828
0.015938758850097656
0.025325775146484375
0.011438846588134766
0.006977558135986328
0.012399673461914062
0.007956981658935547
0.016864299774169922
0.003936767578125
0.01835346221923828
0.014878034591674805
0.004960060119628906
0.010911941528320312
0.023841381072998047
0.028240203857421875
0.013886213302612305

0.015903711318969727
0.022288799285888672
0.0243380069732666
0.021300792694091797
0.009455442428588867
0.015374422073364258
0.008908271789550781
0.010942697525024414
0.01388692855834961
0.013888120651245117
0.0074920654296875
0.00837397575378418
0.012895345687866211
0.005455970764160156
0.010909557342529297
0.0218050479888916
0.022351980209350586
0.011406660079956055
0.004960298538208008
0.0054547786712646484
0.026289939880371094
0.02188253402709961
0.0059490203857421875
0.004467487335205078
0.01239919662475586
0.00991964340209961
0.003968000411987305
0.009920358657836914
0.003967761993408203
0.013391733169555664
0.013387680053710938
0.017385005950927734
0.02330493927001953
0.0049588680267333984
0.015902996063232422
0.004462242126464844
0.004846334457397461
0.011910200119018555
0.0009777545928955078
0.014910459518432617
0.02129840850830078
0.021822690963745117
0.006446361541748047
0.01686382293701172
0.01438450813293457
0.014879226684570312
0.00793600082397461
0.006447792053222656
0.003968000411987305
0.014879703521728516
0.005456686019897461
0.01240086555480957
0.013390064239501953
0.013887643814086914
0.014383077621459961
0.010415792465209961
0.00793600082397461
0.0065343379974365234
0.0029764175415039062
0.007439374923706055
0.014383316040039062
0.034223318099975586
0.009454011917114258
0.004965305328369141
0.008427143096923828
0.007440090179443359
0.035211801528930664
0.009454488754272461
0.01587200164794922
0.013856649398803711
0.018352508544921875
0.012398242950439453
0.009455442428588867
0.005450010299682617
0.011934995651245117
0.00792837142944336
0.014383316040039062
0.010392427444458008
0.006445646286010742
0.005456447601318359
0.020860910415649414
0.011404752731323242
0.0034728050231933594
0.00892019271850586
0.017335891723632812
0.01537466049194336
0.011408805847167969
0.007937431335449219
0.00843048095703125
0.009423971176147461
0.011904001235961914
0.007439851760864258
0.005952119827270508
0.00843191146850586
0.006943941116333008
0.006447792053222656
0.00843048095703125
0.01091313362121582
0.005950927734375
0.014383554458618164
0.0074388980865478516
0.012895584106445312
0.006942272186279297
0.013422489166259766
0.013361930847167969
0.01639723777770996
0.009392261505126953
0.008928060531616211
0.015407085418701172
0.010416269302368164
0.004464864730834961
0.010938882827758789
0.024798154830932617
0.013362646102905273
0.020830154418945312
0.008928060531616211
0.011904001235961914
0.003968000411987305
0.013887643814086914
0.004960060119628906
0.006943941116333008
0.003968000411987305
0.02830362319946289
0.007966279983520508
0.004464387893676758
0.005952596664428711
0.003985166549682617
0.005455493927001953
0.016368389129638672
0.005953550338745117
0.008430719375610352
0.00148773193359375
0.01787710189819336
0.01286458969116211
0.007439851760864258
0.018352031707763672
0.01636815071105957
0.00942373275756836
0.01438283920288086
0.02281475067138672
0.004959583282470703
0.00446319580078125
0.015376567840576172
0.017361164093017578
0.011406183242797852
0.0014879703521728516
0.009423971176147461
0.009424209594726562
0.01785588264465332
0.013391971588134766
0.028272151947021484
0.017361879348754883
0.012398719787597656
0.018847227096557617
0.007439613342285156
0.015413522720336914
0.045760393142700195
0.012401819229125977
0.017357826232910156
0.004463672637939453
0.026257991790771484
0.015902280807495117
0.009454011917114258
0.004464149475097656
0.021793603897094727
0.014878034591674805
0.010912418365478516
0.005982637405395508
0.005424976348876953
0.027807950973510742
0.02330803871154785
0.015346765518188477
0.007936477661132812
0.007437944412231445
0.014456033706665039
0.009454965591430664
0.014380455017089844
0.006951332092285156
0.018847942352294922
0.01835322380065918
0.025296688079833984
0.00548553466796875
0.014384269714355469
0.011904001235961914
0.010912179946899414
0.017885923385620117
0.008430004119873047
0.011409997940063477
0.0019838809967041016
0.011924982070922852
0.009423971176147461
0.01438450813293457
0.006919384002685547
0.013911962509155273
0.0034465789794921875
0.015873193740844727
0.017854690551757812
0.006945133209228516
0.0039675235748291016
0.009919166564941406
0.004463672637939453
0.012399673461914062
0.007440090179443359
0.012927770614624023
0.003968238830566406
0.01537632942199707
0.009454965591430664
0.00843358039855957
0.0069429874420166016
0.010441064834594727
0.013393402099609375
0.017353296279907227
0.01338958740234375
0.013862848281860352
0.009919404983520508
0.00644683837890625
0.006949424743652344
0.014904499053955078
0.009422779083251953
0.009421348571777344
0.008425712585449219
0.018353939056396484
0.022324800491333008
0.014377355575561523
0.020339488983154297
0.010446786880493164
0.022783756256103516
0.012400150299072266
0.011904001235961914
0.011932134628295898
0.009392499923706055
0.014383792877197266
0.016366004943847656
0.010911941528320312
0.006943464279174805
0.0035033226013183594
0.011904001235961914
0.005950927734375
0.012398719787597656
0.005484819412231445
0.011409521102905273
0.012926578521728516
0.007436990737915039
0.017828702926635742
0.011407613754272461
0.013883829116821289
0.012936592102050781
0.007955789566040039
0.009920358657836914
0.017849206924438477
0.015901803970336914
0.0074422359466552734
0.008423328399658203
0.008439064025878906
0.00740814208984375
0.02281475067138672
0.00892782211303711
0.028768301010131836
0.011902332305908203
0.020337343215942383
0.010910987854003906
0.00942373275756836
0.00446319580078125
0.0381929874420166
0.014383077621459961
0.006448507308959961
0.004959821701049805
0.00793600082397461
0.009919881820678711
0.015873193740844727
0.01190328598022461
0.005951642990112305
0.025327205657958984
0.029727935791015625
0.013391971588134766
0.002480030059814453
0.008927345275878906
0.013391494750976562
0.012981653213500977
0.00793600082397461
0.014879703521728516
0.007338762283325195
0.019840002059936523
0.030751943588256836
0.012400150299072266
0.010416269302368164
0.006447792053222656
0.003968000411987305
0.00892782211303711
0.006448268890380859
0.03819155693054199
0.009422779083251953
0.009920835494995117
0.009424686431884766
0.005454301834106445
0.007440328598022461
0.00991964340209961
0.019344568252563477
0.011904001235961914
0.02033543586730957
0.0044612884521484375
0.02780461311340332
0.023314237594604492
0.020833492279052734
0.018816709518432617
0.024799585342407227
0.00892949104309082
0.008462190628051758
0.01435232162475586
0.0034716129302978516
0.011406660079956055
0.016863107681274414
0.05260944366455078
0.008399248123168945
0.008958101272583008
0.011408567428588867
0.010417938232421875
0.02575850486755371
0.0054569244384765625
0.013423442840576172
0.04115867614746094
0.008927106857299805
0.010446786880493164
0.008428335189819336
0.011408090591430664
0.01686382293701172
0.019870281219482422
0.007935523986816406
0.006944417953491211
0.02281498908996582
0.022324085235595703
0.02033090591430664
0.018848419189453125
0.012894630432128906
0.011903524398803711
0.006947755813598633
0.010939598083496094
0.08581733703613281
0.008460760116577148
0.007908105850219727
0.007966041564941406
0.02182316780090332
0.012866497039794922
0.03177499771118164
0.010881900787353516
0.007439136505126953
0.00545501708984375
0.02132701873779297
0.009424209594726562
0.014913797378540039
0.02278423309326172
0.003968000411987305
0.029263019561767578
0.0069429874420166016
0.023812532424926758
0.007936477661132812
0.017885923385620117
0.0074384212493896484
0.03276705741882324
0.01587200164794922
0.009424209594726562
0.010416030883789062
0.009921550750732422
0.00796365737915039
0.01686692237854004
0.01897430419921875
0.03124833106994629
0.01091146469116211
0.016367435455322266
0.01835012435913086
0.04215741157531738
0.013886213302612305
0.010912895202636719
0.019870519638061523
0.01884913444519043
0.027280092239379883
0.004960298538208008
0.02725076675415039
0.010416030883789062
0.010912656784057617
0.025323152542114258
0.017328262329101562
0.022847652435302734
0.006944417953491211
0.017838478088378906
0.015381813049316406
0.004956483840942383
0.018848896026611328
0.04017829895019531
0.024302959442138672
0.008462190628051758
0.0024492740631103516
0.017855167388916016
0.01140904426574707
0.0069675445556640625
0.011378765106201172
0.01937580108642578
0.010421037673950195
0.014356136322021484
0.006478071212768555
0.036177635192871094
0.012895822525024414
0.010416030883789062

0.005455732345581055
0.010913372039794922
0.02083301544189453
0.05356788635253906
0.05704188346862793
0.025790929794311523
0.014880895614624023
0.009422540664672852
0.006943702697753906
0.013392210006713867
0.011904239654541016
0.008928060531616211
0.013919591903686523
0.005951881408691406
0.029265165328979492
0.008926630020141602
0.010416507720947266
0.005422830581665039
0.028765439987182617
0.011409282684326172
0.012926340103149414
0.009421348571777344
0.02480030059814453
0.008893251419067383
0.01983928680419922
0.008961200714111328
0.0074367523193359375
0.020832061767578125
0.004457235336303711
0.01091146469116211
0.011409282684326172
0.01683974266052246
0.009955406188964844
0.010442018508911133
0.009426593780517578
0.008896350860595703
0.02529740333557129
0.03227114677429199
0.020801782608032227
0.011901617050170898
0.008431196212768555
0.030751466751098633
0.012400388717651367
0.010417699813842773
0.007439851760864258
0.013888359069824219
0.047617197036743164
0.014382123947143555
0.013886690139770508
0.017853498458862305
0.010076522827148438
0.012398481369018555
0.010416269302368164
0.008928060531616211
0.008431196212768555
0.027311325073242188
0.004464149475097656
0.006944179534912109
0.007444143295288086
0.007470130920410156
0.008425712585449219
0.004961490631103516
0.008927583694458008
0.009918212890625
0.009420156478881836
0.0049555301666259766
0.0034723281860351562
0.011408329010009766
0.013389110565185547
0.007471323013305664
0.013388633728027344
0.006448030471801758
0.021333932876586914
0.00889730453491211
0.032765865325927734
0.016864538192749023
0.01537632942199707
0.014873266220092773
0.005430459976196289
0.008959770202636719
0.005449771881103516
0.006918907165527344
0.020366191864013672
0.003476381301879883
0.003464937210083008
0.009428024291992188
0.005948305130004883
0.014383792877197266
0.01388239860534668
0.014878273010253906
0.00793600082397461
0.00843048095703125
0.009455442428588867
0.010943412780761719
0.006448030471801758
0.00843191146850586
0.014883279800415039
0.01435089111328125
0.00843191146850586
0.005952119827270508
0.010910987854003906
0.01636791229248047
0.007936239242553711
0.017856359481811523
0.010911941528320312
0.031743526458740234
0.008431434631347656
0.003472566604614258
0.0064470767974853516
0.015375375747680664
0.018878698348999023
0.024802207946777344
0.016366004943847656
0.021327733993530273
0.0014903545379638672
0.017886638641357422
0.01243138313293457
0.012401580810546875
0.007933855056762695
0.01735520362854004
0.011409997940063477
0.006944179534912109
0.006447553634643555
0.010415792465209961
0.01636791229248047
0.022330760955810547
0.020821332931518555
0.03770589828491211
0.019343137741088867
0.016367435455322266
0.02182173728942871
0.011412620544433594
0.014909982681274414
0.007904767990112305
0.010414600372314453
0.012893199920654297
0.013390779495239258
0.009918689727783203
0.012399673461914062
0.012399911880493164
0.005951881408691406
0.014880180358886719
0.013392448425292969
0.008927345275878906
0.009423971176147461
0.005951881408691406
0.006943941116333008
0.019344806671142578
0.013391256332397461
0.022319555282592773
0.009951591491699219
0.006943702697753906
0.012399911880493164
0.008429527282714844
0.0064544677734375
0.007931947708129883
0.013888359069824219
0.014874935150146484
0.003968000411987305
0.005461215972900391
0.011874198913574219
0.01835179328918457
0.014382362365722656
0.012896060943603516
0.009424209594726562
0.007439851760864258
0.004464149475097656
0.0029757022857666016
0.022816181182861328
0.015375852584838867
0.005951881408691406
0.016864299774169922
0.014879941940307617
0.015376091003417969
0.008928298950195312
0.012895822525024414
0.012896060943603516
0.009920597076416016
0.00846242904663086
0.01240396499633789
0.0029718875885009766
0.008932113647460938
0.01338815689086914
0.017826318740844727
0.0019838809967041016
0.006448268890380859
0.01785564422607422
0.017886877059936523
0.004434108734130859
0.007464170455932617
0.011910438537597656
0.006937503814697266
0.010422229766845703
0.014850139617919922
0.00942230224609375
0.02727985382080078
0.014384269714355469
0.014384031295776367
0.005952119827270508
0.009423971176147461
0.019840002059936523
0.023808002471923828
0.00347137451171875
0.015871047973632812
0.020335912704467773
0.012895822525024414
0.013391971588134766
0.010911941528320312
0.005952119827270508
0.01686406135559082
0.009423017501831055
0.013888120651245117
0.010415077209472656
0.0034723281860351562
0.018883228302001953
0.011934518814086914
0.01044607162475586
0.0074503421783447266
0.011408090591430664
0.012898683547973633
0.007933378219604492
0.011881113052368164
0.009918689727783203
0.012400388717651367
0.013886690139770508
0.001984119415283203
0.006944417953491211
0.011903047561645508
0.014879703521728516
0.00793600082397461
0.022815704345703125
0.00793600082397461
0.007440328598022461
0.028272151947021484
0.012399673461914062
0.019342422485351562
0.006448030471801758
0.009423971176147461
0.019840002059936523
0.007936239242553711
0.012895584106445312
0.01041555404663086
0.010415792465209961
0.015376567840576172
0.003968000411987305
0.00892782211303711
0.011407613754272461
0.010416269302368164
0.012400150299072266
0.007935047149658203
0.005455732345581055
0.016368865966796875
0.006943464279174805
0.020335912704467773
0.014383792877197266
0.00793600082397461
0.008928775787353516
0.0044634342193603516
0.009920120239257812
0.013391733169555664
0.012896299362182617
0.03174400329589844
0.017359495162963867
0.005456447601318359
0.0079345703125
0.027776002883911133
0.010415792465209961
0.012400388717651367
0.006943464279174805
0.027776479721069336
0.031248092651367188
0.01735973358154297
0.02182292938232422
0.02185821533203125
0.018348217010498047
0.011377811431884766
0.0064465999603271484
0.005455493927001953
0.01587200164794922
0.015871763229370117
0.00793600082397461
0.019840002059936523
0.011904001235961914
0.014911651611328125
0.007904052734375
0.00793600082397461
0.008927345275878906
0.011407613754272461
0.01587200164794922
0.010447502136230469
0.009920835494995117
0.013887166976928711
0.009441614151000977
0.009454965591430664
0.012395620346069336
0.009396076202392578
0.0332331657409668
0.005951404571533203
0.02182292938232422
0.020833253860473633
0.013390541076660156
0.013887882232666016
0.006944417953491211
0.012399911880493164
0.014879941940307617
0.010416030883789062
0.005952119827270508
0.02678394317626953
0.026784420013427734
0.01140737533569336
0.01587200164794922
0.01835179328918457
0.009423971176147461
0.009424209594726562
0.024303436279296875
0.008431673049926758
0.02529621124267578
0.008431673049926758
0.009918928146362305
0.012398958206176758
0.012896060943603516
0.010416269302368164
0.004464149475097656
0.028302907943725586
0.02923274040222168
0.003968000411987305
0.003968238830566406
0.017854928970336914
0.010943412780761719
0.007941007614135742
0.008892297744750977
0.017359256744384766
0.005455493927001953
0.017854928970336914
0.008431434631347656
0.012403726577758789
0.008463382720947266
0.0074422359466552734
0.003966569900512695
0.00644683837890625
0.029752492904663086
0.025325775146484375
0.015343427658081055
0.008461952209472656
0.007436037063598633
0.010909795761108398
0.007959604263305664
0.0064542293548583984
0.024770736694335938
0.016399145126342773
0.006945610046386719
0.004456281661987305
0.014414310455322266
0.02678394317626953
0.006478309631347656
0.012396812438964844
0.011407136917114258
0.008433341979980469
0.011902809143066406
0.01636672019958496
0.015375852584838867
0.006944894790649414
0.002974987030029297
0.018848180770874023
0.013887405395507812
0.00843191146850586
0.008434534072875977
0.014911413192749023
0.012400388717651367
0.016863107681274414
0.015871524810791016
0.015409708023071289
0.016335725784301758
0.02179098129272461
0.01190328598022461
0.01884770393371582
0.035219430923461914
0.007413148880004883
0.009422063827514648
0.022817611694335938
0.006446123123168945
0.01686573028564453
0.014384031295776367
0.012398481369018555
0.01983928680419922
0.028304576873779297
0.013915538787841797
0.004457712173461914
0.013899803161621094
0.006943941116333008
0.009453535079956055
0.026783227920532227
0.008926868438720703
0.005456209182739258
0.013391971588134766
0.005455732345581055
0.01140141487121582
0.014880180358886719

0.01485443115234375
0.011407136917114258
0.016864299774169922
0.010942220687866211
0.004463911056518555
0.012369871139526367
0.011438846588134766
0.013857364654541016
0.021854639053344727
0.020303964614868164
0.01785588264465332
0.019342660903930664
0.007936954498291016
0.005952119827270508
0.01835179328918457
0.007440805435180664
0.006448507308959961
0.023807048797607422
0.017858028411865234
0.00991964340209961
0.019840240478515625
0.024303913116455078
0.023314714431762695
0.007935047149658203
0.0054585933685302734
0.037230491638183594
0.01735830307006836
0.008432626724243164
0.023839473724365234
0.009888172149658203
0.016398191452026367
0.010446786880493164
0.01441192626953125
0.02083563804626465
0.013358592987060547
0.008931398391723633
0.034720420837402344
0.01140737533569336
0.014879941940307617
0.0074388980865478516
0.018352270126342773
0.029790163040161133
0.009424924850463867
0.004992485046386719
0.006911039352416992
0.017857789993286133
0.015374183654785156
0.022835969924926758
0.03270387649536133
0.00895833969116211
0.01785588264465332
0.041634321212768555
0.007966995239257812
0.015377283096313477
0.027245759963989258
0.007439851760864258
0.00945591926574707
0.01950359344482422
0.017389774322509766
0.012400150299072266
0.07784128189086914
0.04761552810668945
0.010415315628051758
0.015871524810791016
0.007936477661132812
0.009919404983520508
0.009423971176147461
0.0029761791229248047
0.013888359069824219
0.00793600082397461
0.006447553634643555
0.013390541076660156
0.0024797916412353516
0.0034723281860351562
0.0039675235748291016
0.008926630020141602
0.02480030059814453
0.014879941940307617
0.015376091003417969
0.017855167388916016
0.006447553634643555
0.09622383117675781
0.01636672019958496
0.02480006217956543
0.008432865142822266
0.01739048957824707
0.017361164093017578
0.003966569900512695
0.009949922561645508
0.013393640518188477
0.01388859748840332
0.019835948944091797
0.012899160385131836
0.0079345703125
0.016873598098754883
0.006443500518798828
0.015405893325805664
0.005455732345581055
0.036704301834106445
0.02377629280090332
0.012928009033203125
0.012896060943603516
0.003472566604614258
0.003936290740966797
0.016842126846313477
0.06249523162841797
0.009424686431884766
0.039679527282714844
0.02383565902709961
0.022316694259643555
0.01292729377746582
0.012866020202636719
0.01884746551513672
0.016367673873901367
0.014386177062988281
0.024304628372192383
0.01983928680419922
0.012398719787597656
0.013887643814086914
0.021328210830688477
0.011408329010009766
0.014881134033203125
0.03475308418273926
0.02184748649597168
0.011873722076416016
0.021856307983398438
0.0069119930267333984
0.00843048095703125
0.011438369750976562
0.00893092155456543
0.0168607234954834
0.016423463821411133
0.021825551986694336
0.010910749435424805
0.01785731315612793
0.019343852996826172
0.014383792877197266
0.012430191040039062
0.01981043815612793
0.016893625259399414
0.040175437927246094
0.013391733169555664
0.00347137451171875
0.02033686637878418
0.0069429874420166016
0.024305343627929688
0.030257463455200195
0.009949445724487305
0.013887882232666016
0.013889074325561523
0.006447553634643555
0.006447792053222656
0.018847942352294922
0.016864299774169922
0.0014562606811523438
0.012429952621459961
0.01388096809387207
0.017359495162963867
0.010415792465209961
0.0128936767578125
0.02132892608642578
0.009454488754272461
0.01137685775756836
0.022350072860717773
0.02427387237548828
0.025792837142944336
0.026781797409057617
0.009464025497436523
0.009915351867675781
0.011902332305908203
0.02678513526916504
0.009954452514648438
0.008927345275878906
0.015369653701782227
0.003943681716918945
0.008457422256469727
0.012428045272827148
0.010884761810302734
0.01041722297668457
0.017360210418701172
0.02232217788696289
0.0262906551361084
0.017389774322509766
0.008402585983276367
0.006449460983276367
0.01388692855834961
0.016369104385375977
0.02527594566345215
0.007447242736816406
0.013421773910522461
0.0074350833892822266
0.020836591720581055
0.01933908462524414
0.009424448013305664
0.010909557342529297
0.017362594604492188
0.011904239654541016
0.015347719192504883
0.008960723876953125
0.012398958206176758
0.007904291152954102
0.012414216995239258
0.02380084991455078
0.022294998168945312
0.011902809143066406
0.01537466049194336
0.006943702697753906
0.0054569244384765625
0.018846988677978516
0.01835179328918457
0.006448030471801758
0.009424448013305664
0.036704063415527344
0.005456447601318359
0.01689434051513672
0.009918928146362305
0.02339005470275879
0.013837575912475586
0.0034418106079101562
0.00895237922668457
0.009424448013305664
0.013887882232666016
0.011407852172851562
0.015377044677734375
0.007942438125610352
0.011382102966308594
0.015374183654785156
0.00644683837890625
0.005955934524536133
0.008927345275878906
0.011408567428588867
0.007439136505126953
0.010416030883789062
0.014877796173095703
0.007439374923706055
0.003469705581665039
0.006446123123168945
0.010911703109741211
0.018352746963500977
0.01289820671081543
0.01041102409362793
0.007936239242553711
0.027286291122436523
0.025792598724365234
0.01385807991027832
0.018351316452026367
0.015376567840576172
0.02083110809326172
0.012399911880493164
0.011409759521484375
0.009425163269042969
0.01041722297668457
0.014391660690307617
0.011408329010009766
0.005952596664428711
0.027308940887451172
0.02675151824951172
0.019840478897094727
0.017855167388916016
0.005954742431640625
0.020335912704467773
0.01934504508972168
0.01686382293701172
0.02678513526916504
0.04413414001464844
0.01934361457824707
0.018352031707763672
0.03571367263793945
0.03471875190734863
0.02034759521484375
0.01686263084411621
0.009920835494995117
0.007935762405395508
0.03372621536254883
0.030253171920776367
0.009919166564941406
0.035215139389038086
0.006447315216064453
0.004957914352416992
0.012905359268188477
0.0074443817138671875
0.014887094497680664
0.012925148010253906
0.02972888946533203
0.01289820671081543
0.016863346099853516
0.022815942764282227
0.01140737533569336
0.011408567428588867
0.010912418365478516
0.02231884002685547
0.034223079681396484
0.0411684513092041
0.0064487457275390625
0.02281475067138672
0.027278900146484375
0.017360687255859375
0.027280569076538086
0.012398719787597656
0.013391494750976562
0.03323221206665039
0.01934337615966797
0.007437229156494141
0.0054547786712646484
0.008927345275878906
0.005951404571533203
0.013887166976928711
0.005455732345581055
0.027776718139648438
0.021327733993530273
0.01636815071105957
0.004451751708984375
0.009454727172851562
0.017828702926635742
0.007935762405395508
0.02135944366455078
0.00939321517944336
0.012403011322021484
0.01689291000366211
0.015006542205810547
0.006448984146118164
0.005454301834106445
0.011875391006469727
0.01937389373779297
0.006911754608154297
0.030256986618041992
0.014383077621459961
0.005980968475341797
0.011427164077758789
0.00994873046875
0.01286625862121582
0.004958629608154297
0.006447553634643555
0.00793600082397461
0.009920120239257812
0.005951881408691406
0.01388692855834961
0.011408090591430664
0.007935762405395508
0.004960298538208008
0.013391256332397461
0.011904716491699219
0.010911703109741211
0.026782751083374023
0.012398242950439453
0.01094365119934082
0.011903524398803711
0.012399673461914062
0.00892782211303711
0.008433341979980469
0.003000497817993164
0.01685166358947754
0.005949974060058594
0.010416269302368164
0.00148773193359375
0.015407800674438477
0.023807525634765625
0.014908790588378906
0.042711734771728516
0.013911247253417969
0.008928298950195312
0.007439136505126953
0.0029761791229248047
0.005975484848022461
0.01389622688293457
0.026782989501953125
0.010912895202636719
0.011903762817382812
0.010415792465209961
0.023311853408813477
0.003972768783569336
0.010418891906738281
0.013360261917114258
0.010416030883789062
0.009422540664672852
0.02086329460144043
0.017343997955322266
0.020830869674682617
0.012398719787597656
0.03025507926940918
0.01091313362121582
0.011407852172851562
0.019344806671142578
0.014383077621459961
0.013887643814086914
0.0024805068969726562
0.0029757022857666016
0.019840717315673828
0.007364749908447266
0.0069429874420166016
0.0064465999603271484
0.020816326141357422
0.03375720977783203
0.015841960906982422
0.010909557342529297
0.009423494338989258
0.012400627136230469
0.024799346923828125
0.006555318832397461
0.015872955322265625
0.012398719787597656
0.004463672637939453
0.01537466049194336

0.03274226188659668
0.020831584930419922
0.001983165740966797
0.004460811614990234
0.006447553634643555
0.007935762405395508
0.01736164093017578
0.007494449615478516
0.010417699813842773
0.015405893325805664
0.012372255325317383
0.011437416076660156
0.01137685775756836
0.011936426162719727
0.006944179534912109
0.013918399810791016
0.008894920349121094
0.007440328598022461
0.010415792465209961
0.008431673049926758
0.014889240264892578
0.02480173110961914
0.04215884208679199
0.008463144302368164
0.007947206497192383
0.0039517879486083984
0.00991964340209961
0.013887882232666016
0.027776002883911133
0.02281665802001953
0.029263734817504883
0.022325754165649414
0.007441282272338867
0.024304866790771484
0.010910511016845703
0.008927345275878906
0.005455493927001953
0.014877557754516602
0.013889551162719727
0.02579212188720703
0.012895345687866211
0.02480030059814453
0.006445169448852539
0.012433528900146484
0.006413936614990234
0.029761314392089844
0.006942272186279297
0.014383792877197266
0.011406421661376953
0.02033829689025879
0.016399860382080078
0.010383129119873047
0.012431859970092773
0.007442474365234375
0.016397953033447266
0.011376619338989258
0.015901565551757812
0.010415077209472656
0.011934995651245117
0.01983022689819336
0.010912179946899414
0.014881134033203125
0.005952358245849609
0.01487874984741211
0.009454011917114258
0.011408090591430664
0.011407852172851562
0.00991964340209961
0.0059528350830078125
0.010416746139526367
0.013390779495239258
0.007409572601318359
0.019344806671142578
0.013888359069824219
0.010386228561401367
0.007409811019897461
0.012896299362182617
0.015375375747680664
0.020364046096801758
0.012897968292236328
0.013881683349609375
0.013390302658081055
0.004461765289306641
0.014415979385375977
0.01633739471435547
0.011934041976928711
0.027249574661254883
0.018848657608032227
0.005982637405395508
0.022319793701171875
0.014362573623657227
0.019344329833984375
0.011904001235961914
0.008959770202636719
0.0035021305084228516
0.004463672637939453
0.009419441223144531
0.015406370162963867
0.0065457820892333984
0.013423442840576172
0.012469053268432617
0.009951591491699219
0.015486717224121094
0.02678394317626953
0.0054552555084228516
0.020832061767578125
0.03819108009338379
0.007439851760864258
0.005985736846923828
0.013888835906982422
0.0019505023956298828
0.012258768081665039
0.014385223388671875
0.010414361953735352
0.008432149887084961
0.027807235717773438
0.011408567428588867
0.00543975830078125
0.034718990325927734
0.0054891109466552734
0.011406660079956055
0.006447792053222656
0.008431673049926758
0.005984067916870117
0.011934280395507812
0.006447792053222656
0.009447813034057617
0.020342350006103516
0.011407136917114258
0.0054798126220703125
0.007935762405395508
0.005954742431640625
0.015375852584838867
0.012896060943603516
0.026784181594848633
0.02132868766784668
0.010911703109741211
0.019838333129882812
0.02579212188720703
0.013887643814086914
0.011408567428588867
0.010413169860839844
0.06944036483764648
0.0362093448638916
0.015374183654785156
0.06051182746887207
0.020335674285888672
0.018847942352294922
0.021328449249267578
0.024829864501953125
0.004953145980834961
0.007937431335449219
0.008428573608398438
0.014359235763549805
0.009424924850463867
0.016368865966796875
0.01636672019958496
0.011904001235961914
0.007439613342285156
0.01686573028564453
0.0074748992919921875
0.010909795761108398
0.011409759521484375
0.009435653686523438
0.01537632942199707
0.010911941528320312
0.005951881408691406
0.004464149475097656
0.010880708694458008
0.02480006217956543
0.02628779411315918
0.015407085418701172
0.016338348388671875
0.00942230224609375
0.016368389129638672
0.01488041877746582
0.00793600082397461
0.010911703109741211
0.010416030883789062
0.013888835906982422
0.005455732345581055
0.008928060531616211
0.006943941116333008
0.003968000411987305
0.01636791229248047
0.004464149475097656
0.010415792465209961
0.015375852584838867
0.010416030883789062
0.043184518814086914
0.015869617462158203
0.009424209594726562
0.005952119827270508
0.01091146469116211
0.012400627136230469
0.007929325103759766
0.020336151123046875
0.010912656784057617
0.016367673873901367
0.007936239242553711
0.020806312561035156
0.015375614166259766
0.016864538192749023
0.023310184478759766
0.009920358657836914
0.008463144302368164
0.030757427215576172
0.02628946304321289
0.008433818817138672
0.015865564346313477
0.018846511840820312
0.014879941940307617
0.02185511589050293
0.009923458099365234
0.008899927139282227
0.012893915176391602
0.009920120239257812
0.023311853408813477
0.01339268684387207
0.006943941116333008
0.005951642990112305
0.008432626724243164
0.00991964340209961
0.011407852172851562
0.005456209182739258
0.01735973358154297
0.0014872550964355469
0.008928537368774414
0.009424209594726562
0.004957437515258789
0.019839048385620117
0.005456447601318359
0.013391256332397461
0.008433103561401367
0.02083277702331543
0.012398481369018555
0.016864538192749023
0.006448030471801758
0.007439851760864258
0.009424209594726562
0.006447792053222656
0.014383792877197266
0.007936477661132812
0.007935523986816406
0.021823883056640625
0.008432149887084961
0.02480030059814453
0.0069463253021240234
0.008928060531616211
0.028272151947021484
0.007440090179443359
0.01735997200012207
0.00892782211303711
0.010912179946899414
0.013887643814086914
0.015872478485107422
0.017359495162963867
0.01983928680419922
0.004464626312255859
0.00793600082397461
0.046128034591674805
0.012400150299072266
0.009423017501831055
0.0069427490234375
0.003469228744506836
0.009454727172851562
0.010943174362182617
0.01487874984741211
0.013392448425292969
0.010910987854003906
0.01488494873046875
0.0049533843994140625
0.012424468994140625
0.01835155487060547
0.00592803955078125
0.009454727172851562
0.013362646102905273
0.0059854984283447266
0.03270745277404785
0.018344879150390625
0.015903472900390625
0.014875650405883789
0.004487037658691406
0.028774738311767578
0.026297807693481445
0.013889551162719727
0.010909318923950195
0.01686406135559082
0.011904001235961914
0.0044634342193603516
0.009454011917114258
0.02972888946533203
0.03572678565979004
0.009458065032958984
0.027765989303588867
0.007936477661132812
0.011904001235961914
0.02086639404296875
0.011404037475585938
0.011934757232666016
0.017856121063232422
0.01091146469116211
0.022815942764282227
0.013391971588134766
0.018351078033447266
0.012896060943603516
0.007439374923706055
0.018848180770874023
0.009423494338989258
0.026784181594848633
0.025295019149780273
0.015377521514892578
0.0024802684783935547
0.012400388717651367
0.006448030471801758
0.011918306350708008
0.006445407867431641
0.01438140869140625
0.03422427177429199
0.01289510726928711
0.00892186164855957
0.011903762817382812
0.015374422073364258
0.006943702697753906
0.016399145126342773
0.015872955322265625
0.010883331298828125
0.017854690551757812
0.008443117141723633
0.008927345275878906
0.014878511428833008
0.025793790817260742
0.00843048095703125
0.03323245048522949
0.011904478073120117
0.015375614166259766
0.009920358657836914
0.011406660079956055
0.00991964340209961
0.034224748611450195
0.01289510726928711
0.008432388305664062
0.03372764587402344
0.012898445129394531
0.0064792633056640625
0.009949684143066406
0.017827272415161133
0.011405467987060547
0.012431859970092773
0.025289297103881836
0.011939525604248047
0.017325878143310547
0.01391744613647461
0.014880180358886719
0.010415077209472656
0.010913372039794922
0.023310422897338867
0.01384735107421875
0.01388692855834961
0.014383316040039062
0.01143956184387207
0.01451420783996582
0.02036762237548828
0.028342247009277344
0.02777552604675293
0.029265642166137695
0.035216569900512695
0.011904239654541016
0.012894153594970703
0.010417938232421875
0.005963563919067383
0.003962039947509766
0.013888120651245117
0.012368440628051758
0.005453824996948242
0.01735997200012207
0.009952545166015625
0.006974220275878906
0.07585692405700684
0.030783891677856445
0.005919456481933594
0.018352508544921875
0.052079200744628906
0.009423255920410156
0.039679765701293945
0.01686382293701172
0.013393640518188477
0.006943941116333008
0.01686382293701172
0.018351316452026367
0.007936477661132812
0.021807432174682617
0.012400388717651367
0.03819108009338379
0.0049610137939453125
0.0362086296081543

0.013390064239501953
0.03227639198303223
0.03418898582458496
0.014414548873901367
0.013884544372558594
0.009916543960571289
0.016890287399291992
0.027775287628173828
0.012925863265991211
0.013396739959716797
0.05108785629272461
0.013390541076660156
0.019840478897094727
0.015868663787841797
TIEMPO TRANSCURRIDO: 171.47885131835938

In [17]:
x = datetime.datetime.now()
c.to_excel(x.strftime("%y%m%d-%H%M-") + criterios + '.xlsx')

end_total = time.time()

print('TIEMPO TRANSCURRIDO:', end_total-start_total)

TIEMPO TRANSCURRIDO: 199.11921644210815